### ISSUE TITLE
Allow asynchronous routes

### ISSUE THREAD

**Issue by geajack** [zalando/connexion#1012]
I'd love to be able to have asynchronous routes using `asyncio`. Like this:

```
async def get_user(user_id):
    name, age = await database.fetch_user(user_id)
    return {
        "name": name,
        "age": age
    }
```

I saw snippets using `aiohttp`, but it seems you need to return a `Response` object, but the very thing I like about Connexion for writing JSON-based APIs is that you can just return dictionaries and arrays.

Is anything like this on the roadmap? Or maybe even implemented already?

**Comment by cognifloyd** [comment]
You should be able to return a dict with aiohttp. Once #849 is merged (and released) you will be able to return a tuple of body and status code like with flask.
