### ISSUE TITLE
Swagger docExpansion option

### ISSUE THREAD

**Issue by insideshell** [zalando/connexion#1021]
### Description

Is there a way to configure the [docExpansion](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#docExpansion) option so that tags and models are collapsed by default?

### Expected behaviour

![image](https://user-images.githubusercontent.com/4362224/63348300-42b25580-c359-11e9-971b-a5b970bea79e.png)

The tag `pets` is collapsed by default.

### Actual behaviour

![image](https://user-images.githubusercontent.com/4362224/63348343-565dbc00-c359-11e9-8b55-c257706dd99a.png)

The tag `pets` is not collapsed by default and this is not configurable.

### Steps to reproduce

Just use the [methodresolver example](https://github.com/zalando/connexion/tree/master/examples/openapi3/methodresolver).
There is a way to collapse it from the URL: http://localhost:9090/v1.0/ui/?docExpansion=none
But I am wondering if it is possible during the application instantiation.

### Additional info:

Output of the commands:

- `python --version` : Python 3.6.8
- `pip show connexion | grep "^Version\:"` : 2.3.0

Thanks!

**Comment by RobbeSneyders** [comment]
You can pass UI configuration options via `options.openapi_console_ui_config`. [docs](https://connexion.readthedocs.io/en/latest/quickstart.html?highlight=console%20ui%20config#the-swagger-ui-console)
