### ISSUE TITLE
patch method should ignore required: true

### ISSUE THREAD

**Issue by drummerwolli** [zalando/connexion#1025]
### Description

the HTTP `PATCH`  method only partially updates an entity. This means that the entity is existing beforehand already. This means, that you can just send one attribute in a body to the PATCH endpoint with having some required fields, and it should still work

### Expected behaviour

sending and incomplete body to a PATCH endpoints results in a 200

### Actual behaviour

the schema is completely verified, no matter the HTTP method, and therefore throws a 400 because the object is not complete.

### Steps to reproduce

add this to your OpenAPI3.yaml:

```
paths:
  /entity/{id}:
    patch:
      operationId: "does.not.matter.here"
      parameters:
      - name: relational_datasource_id
        required: true
        in: path
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
              - name
              - connection_id
              - sql
              properties:
                id:
                  type: integer
                name:
                   type: string
                sql:
                   type: string
```

try now to patch this entity, but only try to update the sql field. connexion will complain that you did not supply the `name`, but it should not be needed.

### Additional info:

Output of the commands:

- `python --version : 3.7.4`
- `pip show connexion | grep "^Version\: 2.3.0"`

**Comment by mezba1** [comment]
Came across this issue recently, any update on this?

**Comment by dtkav** [comment]
This is what readOnly and writeOnly are for.
The spec is behaving as expected. You have marked the fields required, and it is validating your assertion.

**Comment by dtkav** [comment]
Here is some more info on readOnly and writeOnly:
https://swagger.io/docs/specification/data-models/data-types/#readonly-writeonly
