### ISSUE TITLE
Question: possible to have endpoints that are not in swagger?

### ISSUE THREAD

**Issue by tommyjcarpenter** [zalando/connexion#1028]
This is just a question.

Is it currently possible to add a route to the webhandler that isn't defined in the swagger/open api spec? Like and endpoint that's only supposed to be used for some administration or debugging purpose, but not publicized?

**Comment by drummerwolli** [comment]
I think by design connexion will not have this. if you don't want it to be accessed, then I would recommend securing it properly. it should still be documented, e.g. for admins ...

**Comment by hjacobs** [comment]
Yes, you can add arbitrary routes via the exposed Flask app.

**Comment by chrisinmtown** [comment]
@hjacobs would you please post a simple example of how to do this cleanly?

**Comment by RobbeSneyders** [comment]
You can also use the `add_url_route` method on the Connexion [app](https://connexion.readthedocs.io/en/2.9.0/autoapi/connexion/apps/index.html?highlight=add_url_rule#connexion.apps.AbstractApp.add_url_rule).
