### ISSUE TITLE
Won't build in official python Docker image

### ISSUE THREAD

**Issue by kleijnweb** [zalando/connexion#103]
Connexion won't install when building the official python image (2.7):

    Digest: sha256:66cb43facbc0356c19d9522cdeffe75efae19dc27f9ba4e73f1f4bbe470de9ca
    Status: Downloaded newer image for python:2.7-onbuild
    # Executing 3 build triggers...
    Step 1 : COPY requirements.txt /usr/src/app/
    Step 1 : RUN pip install --no-cache-dir -r requirements.txt
     ---> Running in 8ddfc3fa74f4
    Collecting connexion>=0.13 (from -r requirements.txt (line 1))
      Downloading connexion-1.0.19.tar.gz (1.0MB)
        Complete output from command python setup.py egg_info:
       Traceback (most recent call last):
         File "<string>", line 20, in <module>
         File "/tmp/pip-build-mCgXxP/connexion/setup.py", line 67, in <module>
           install_requires=get_install_requirements('requirements.txt'),
         File "/tmp/pip-build-mCgXxP/connexion/setup.py", line 27, in get_install_requirements
           content = open(os.path.join(__location__, path)).read()
       IOError: [Errno 2] No such file or directory: '/tmp/pip-build-mCgXxP/connexion/requirements.txt'

Other dependencies (gevent and pymongo) install just fine in the container.

To reproduce:

    echo 'FROM python:2-onbuild' > Dockerfile && \
        echo 'connexion>=1.0' > requirements.txt && \
        docker build .

**Comment by hjacobs** [comment]
@kleijnweb could you provide some more details and context (e.g. Dockerfile etc)? It's hard to see what's going wrong in your case. From the information you gave I would assume that you COPY the requirements file into the wrong directory (/usr/src/app) and run pip from another directory?

**Comment by kleijnweb** [comment]
As you can see in that last 'onliner', the Dockerfile contains nothing but 'FROM python:2-onbuild'. Just try the oneliner in an empty directory.

**Comment by hjacobs** [comment]
Thanks for reporting, seems to be a legit bug --- requirements.txt is missing from source .tar.gz

**Comment by hjacobs** [comment]
I did not see this bug as I'm using the Python 3 wheel package...

**Comment by hjacobs** [comment]
@kleijnweb OK, it's now fixed in 1.0.20

**Comment by kleijnweb** [comment]
Confirmed. Very quick, thanks :)
