### ISSUE TITLE
connexion.readthedocs.io (RTD) not up-to-date

### ISSUE THREAD

**Issue by sijis** [zalando/connexion#1030]
### Description
It seems that [readthedocs site](https://connexion.readthedocs.io/en/latest/) is not updated with recent documentation updates.

I was looking at issues related to `MethodView` and found PR #847. That PR includes documentation changes, namely a section in routing named `Automatic Routing with MethodViewResolver` but i'm not able to find it. 

### Expected behaviour

The section is available on RTD https://connexion.readthedocs.io/en/latest/routing.html.

### Actual behaviour
Section is not there.

### Steps to reproduce

Visit link: https://connexion.readthedocs.io/en/latest/routing.html

### Additional info:

N/A

**Comment by RobbeSneyders** [comment]
This has been fixed.
