### ISSUE TITLE
Is OpenAPI 3.0.0 supported by connexion?

### ISSUE THREAD

**Issue by mcocosila** [zalando/connexion#1031]
### Description
I'm using OpenAPI 3.0.0 in my spec yaml file.

I keep getting errors like 'no module found' or 'empty function name'. I moved around the python file and openapi spec file trying to work around the operationId not being resolved correctly.

Sample:
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/connexion/resolver.py", line 61, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/connexion/utils.py", line 75, in get_function_from_name
    raise ValueError("**Empty function name**")

### Expected behaviour
operationId to be resolved correctly

### Actual behaviour
Errors like 'no module found' or 'empty function name'.

### Steps to reproduce
python file named api.py located at project top level
function named hello in api.py python module

in openapi spec file:
operationId: api.hello

### Additional info:

Output of the commands:

- `python --version`
Python 3.7.4

- `pip show connexion | grep "^Version\:"`
Version: 2.3.0

**Comment by danie1k** [comment]
Take a look on #983 & #996

**Comment by danie1k** [comment]
You cannod define view functions (operations) in the same file where you define Connextion API. It won't work.
There are some cyclic imports that take place or something like that.

Just move your functon `hello` to any other py file.

**Comment by Abdullahabid3691** [comment]
sharing some related content of your .yml file would be helpful in order to trace the issue.
This can happen when you define `x-swagger-router-controller` instead of `x-openapi-router-controller` (in case of OAS3)
or the `operationId` parameter is not set correctly.

**Comment by RobbeSneyders** [comment]
OpenAPI 3.0.0 is supported by Connexion.
