### ISSUE TITLE
Shared objects between connexion endpoints and FlaskApp endpoints

### ISSUE THREAD

**Issue by caroee** [zalando/connexion#1033]
### Description
I have some global objects that need to be accessed and modified by endpoints specified in the yaml-file as well as endpoints defined directly in the API-script (via the FlaskApp.app endpoints).

Unfortunately, the endpoints do not seem to access the same objects (different threads?), so modifying the object via the yaml-endpoints does not affect the object seen by the directly defined endpoints and vice versa. 

I can fix this by putting the global into an external file and importing it but I wonder whether there is a better way.

### Expected behaviour
Global objects are shared between all endpoints, whether defined via yaml-file or added directly (FlaskApp.app endpoints)

### Actual behaviour
yaml-endpoints and directly defined endpoints run in different threads (?) and therefore do not see/modify the same object unless it is imported from an external file. 

### Steps to reproduce
yaml-file (swagger.yaml):

```
swagger: '2.0'
info:
  title: Test API
  version: 0.0.1
paths:
  /set_global:
    post:
      operationId: server.set_global
      parameters:
        - name: value
          in: query
          type: integer
      responses:
        '200':
          description: 'Success'
```

API script (server.py):
```
from connexion import FlaskApp

app = FlaskApp(__name__)
application = app.app

my_globals = {"global1": 0}

def set_global(value):
    my_globals["global1"] = value
    return str(my_globals["global1"])

@application.route("/get_global", methods=["GET"])
def get_global():
    return str(my_globals["global1"])

app.add_api("swagger.yaml")

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5010, debug=True)
```

Test:
```
import json
import requests

SERVER_URL = "http://0.0.0.0:5010/"

response = requests.get(SERVER_URL + "get_global")
print(json.loads(response.content))

response = requests.post(SERVER_URL + "set_global", params={"value": 1})
print(json.loads(response.content))

response = requests.get(SERVER_URL + "get_global")
print(json.loads(response.content))
```

Output:
```
0
1
0
```

Desired:
```
0
1
1
```

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.8
- `pip show connexion | grep "^Version\:"`
Version: 2.3.0

**Comment by sijis** [comment]
Its an older thread but I'm wondering if you are running into this situation: 
https://stackoverflow.com/questions/19277280/preserving-global-state-in-a-flask-application

In short, it sounds like having a global/shared state approach is not ideal because each request is likely using a different thread and it would lead to inconsistencies between user requests.

**Comment by dtkav** [comment]
Here's some information about the flask context:
https://flask.palletsprojects.com/en/1.1.x/appcontext/

you might be looking for `flask.g` for shared global state.
