### ISSUE TITLE
How to return multiple validation errors?

### ISSUE THREAD

**Issue by hitochan777** [zalando/connexion#1038]
### Description

Is there any way to capture and return all validation errors? 

### Expected behaviour

I want connexion to send response with an array of validation errors rather than a message which contains only one error message even if there are multiple errors.

### Actual behaviour

It returns only one error even if there are multiple validation error.

### Additional info:

I guess even if I use custom validator it is not possible to return an array of errors because [`validate_schema`](https://github.com/zalando/connexion/blob/b05bf6e2927c0d1f9a4c2b39f5ffc4ae786f72a7/connexion/decorators/validation.py#L177) method catches `ValidationError` and send its message as a part of a response. Precisely speaking, I can write a custom validator that returns `ValidationError`
 whose message contains multiple errors joined by some delimiters. But it is not a clean way of achieving what I want.

**Comment by danie1k** [comment]
I've had a similar issue, and made a workaround by monkey patching validator:
```python
import connexion


def parameter_validator_call(self, function):
    _checks = (
        ("query", "validate_query_parameter"),
        ("path", "validate_path_parameter"),
        ("header", "validate_header_parameter"),
    )

    @functools.wraps(function)
    def wrapper(request):
        if self.strict_validation:
            query_errors = self.validate_query_parameter_list(request)
            formdata_errors = self.validate_formdata_parameter_list(request)

            if formdata_errors or query_errors:
                raise ExtraParameterProblem(formdata_errors, query_errors)

        for param_name, validator_name in _checks:
            func: Callable = getattr(self, validator_name)
            errors = []
            for param in self.parameters.get(param_name, []):
                result = func(param, request)
                if result:
                    errors.append(result)

            if errors:
                return ...  # Custom logic for preparing Flask response with errors

        errors = []
        for param in self.parameters.get("formData", []):
            result = self.validate_formdata_parameter(param["name"], param, request)
            if result:
                errors.append(result)

        if errors:
            return ...  # Custom logic for preparing Flask response with errors

        return function(request)

    return wrapper


connexion.decorators.validation.ParameterValidator.__call__ =         parameter_validator_call
```

**Comment by hitochan777** [comment]
@danie1k Thanks, it seems like this is currently the best we can do :)
