### ISSUE TITLE
Typecasting?

### ISSUE THREAD

**Issue by kleijnweb** [zalando/connexion#104]
connexxion seems to pass Swagger integers as unicode strings. At least a note in the docs would be a start.

**Comment by hjacobs** [comment]
Depends on what you mean, type casting "partly" works, see e.g. https://github.com/hjacobs/connexion-example

Can you describe your situation / use case where it fails?

**Comment by kleijnweb** [comment]
To reproduce:

`swagger.yml`:

```yaml
swagger: '2.0'
host: localhost
paths:
  '/foo/{id}':
    get:
      operationId: api.get
      parameters:
        - in: path
          name: id
          type: integer
          format: int64
```

`api.py`:

```python
#!/usr/bin/env python2.7
import connexion

def get(id):
    return str(type(id))

app = connexion.App(__name__)
app.add_api('swagger.yml')
application = app.app

if __name__ == '__main__':
    app.run(port=8080)
```

```bash
http http://localhost:8080/foo/1
```

Actual:

```
HTTP/1.0 200 OK
Content-Length: 18
Content-Type: application/json
Date: Sat, 05 Dec 2015 17:53:49 GMT
Server: Werkzeug/0.11.2 Python/2.7.6

"<type 'unicode'>"
```

Expected:

```
HTTP/1.0 200 OK
Content-Length: 18
Content-Type: application/json
Date: Sat, 05 Dec 2015 17:53:49 GMT
Server: Werkzeug/0.11.2 Python/2.7.6

"<type 'int'>"
```

**Comment by kleijnweb** [comment]
Sidenote, this also works (`"<type 'unicode'>"`):

```yml
swagger: '2.0'
host: localhost
paths:
  '/foo/{id}':
    get:
      operationId: api.get
      parameters:
        - in: path
          name: id
          type: fantasia
```

It would be nice if connexion was a little more defensive, this way typos can lead to hard to track bugs.

**Comment by hjacobs** [comment]
True, that's a missing feature: Flask route converters should be supported http://flask.pocoo.org/docs/0.10/api/#url-route-registrations

**Comment by kleijnweb** [comment]
In the mean time, a small note in the README might save new users  some time. I myself was baffled when a `pymongo.find_one()` operation did not yield any results because the argument was not an integer. Naive, perhaps, but still.

**Comment by hjacobs** [comment]
@kleijnweb my personal recommendation (off topic): stay away from MongoDB :smirk: (we replaced a 5 node MongoDB cluster with a single node PostgreSQL :elephant:)

**Comment by hjacobs** [comment]
In general we need more documentation and tutorials for Connexion...

**Comment by kleijnweb** [comment]
It's only a dummy backend for an AngularJS app, so yeah, not worried about that.

Far as docs go, a simple example in the README with a note about how the arguments are passed (including type coercion -- or lack thereof) would go long way.

**Comment by hjacobs** [comment]
@kleijnweb you can check my pull request #105 which adds type casting for int and float path parameters using Flask path converters

**Comment by hjacobs** [comment]
changes now released in https://github.com/zalando/connexion/releases/tag/1.0.25

**Comment by kleijnweb** [comment]
@hjacobs What about arrays/dicts? Difficult?

**Comment by hjacobs** [comment]
@kleijnweb Flask supports custom "converts" in the path, so I don't think it's difficult --- I'm not sure what the semantics are for other types in "path" parameters (need to check Swagger spec)
