### ISSUE TITLE
path arguments of type number or integer can't be negative

### ISSUE THREAD

**Issue by logi** [zalando/connexion#1040]
The Swagger and OpenAPI specs don't say anything about arguments of type number or integer being restricted to non-negative values. However, passing a negative number in for a number or integer variable results in a `404 Not Found`.

This seems to be behaviour inherited from Flask's `int` and `float` converters which they inherited from Werkzeug. However, they added a `signed` flag to both of those converters in https://github.com/pallets/werkzeug/pull/1355 in December 2018 and that version seems to now be pulled in as a dependency by connexion

So now negative numbers can be supported by changing the `PATH_PARAMETER_CONVERTERS` lookup table in `flask_utils.py` to be:
```python
PATH_PARAMETER_CONVERTERS = {
    'integer': 'int(signed=True)',
    'number': 'float(signed=True)',
    'path': 'path'
}
```

This change won't be enough for us to change our strings to number since we would also need support for integers passed in for number parameters and so I won't set up an environment for making a pull request myself unless I can also fix #1041

**Comment by logi** [comment]
I can work around this in an application using Connexion with:
```python
from connexion.apis import flask_utils
from werkzeug.routing import BaseConverter

class NumberConverter(BaseConverter):
    """ Flask converter for OpenAPI number type """
    regex = r"[+-]?[0-9]+.*(\.[0-9]*)?"

    def to_python(self, value):
        try:
            return float(value)
        except ValueError:
            return float(value)

class IntegerConverter(BaseConverter):
    """ Flask converter for OpenAPI integer type """
    regex = r"[+-]?[0-9]+"

    def to_python(self, value):
        try:
            return int(value)
        except ValueError:
            return int(value)

flask_utils.PATH_PARAMETER_CONVERTERS['integer'] = 'integer'
flask_utils.PATH_PARAMETER_CONVERTERS['number'] = 'number'

connexion_app = connexion.FlaskApp(__name__)
connexion_app.app.url_map.converters["number"] = NumberConverter
connexion_app.app.url_map.converters["integer"] = IntegerConverter
```

At that point the `PATH_PARAMETER_CONVERTERS` dict is not actually needed.

**Comment by logi** [comment]
Is there any interest in a pull-request with the above changes?

**Comment by dtkav** [comment]
Hey @logi - these changes would definitely improve connexion.
There has been lots of confusion around this in the past, and I think your proposed changes provide a great solution.

**Comment by logi** [comment]
OK, I'll put together a change request when I have a bit of time.

**Comment by logi** [comment]
I have finally made PR https://github.com/zalando/connexion/pull/1306 fixing this and #1041
