### ISSUE TITLE
Short operation ids, made from 1 segment can not be resolved.

### ISSUE THREAD

**Issue by Frontrider** [zalando/connexion#1042]
### Description
Operation id's made out of 1 part, eg: `opration` instead of `app.operation` can not be resolved, at least not from any properly documented features.

I'm not in charge of this API, so I can't change it.

### Expected behaviour
`operation.py`'s get/post method get's resolved from the root folder.

### Actual behaviour
Throws an `ERROR:connexion.apis.abstract:Failed to add operation for` error.

### Steps to reproduce

add an operation id that has a 1 segment path.

### Additional info:

Output of the commands:

python version: 2.7.10 (can't update yet)
connexion version: 2.3.0

**Comment by Ruwann** [comment]
Connexion expects an operationId in the form of `module_name.func_name` ([documentation](https://connexion.readthedocs.io/en/stable/routing.html#endpoint-routing-to-your-python-views)).
It is not very clear what the root folder should be: this will be different when you are running the app in development mode (using `app.run()`) than when you are using for example `gunicorn`.

As mentioned in the docs, you can specify `x-swagger-router-controller` (Swagger 2) or `x-openapi-router-controller` (OpenAPI 3) to make the `operationId` relative. Alternatively, you can create a custom `Resolver` that does something similar when resolving the `operationId`.

**Comment by Ruwann** [comment]
@languitar Thanks for the insight, does PR #1419 match what you are looking for?

**Comment by languitar** [comment]
Yes, that would work.
