### ISSUE TITLE
Object of type ObjectId is not JSON serializable

### ISSUE THREAD

**Issue by belthaZornv** [zalando/connexion#1045]
### Description

When returning a record deriving from MongoDB - the encoder extended in the `flask app` doesn't serialise the `ObjectId`s

### Expected behaviour

Falls back on using `str(o)` in the `FlaskJSONEncoder` 

### Actual behaviour

Object of type ObjectId is not JSON serializable

### Steps to reproduce

Return a `dict` containing an `ObjectId`

```
from bson import ObjectID

return {"_id": ObjectId()}

```
### Additional info:

Of course, it is possible to do the following as a fix:

```
from bson.objectid import ObjectId
from connexion.apps.flask_app import FlaskJSONEncoder


class CustomJSONEncoder(FlaskJSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)

        return super().default(o)
```

and in the `app`:

`app.app.json_encoder = CustomJSONEncoder`

and it would work fine, although I believe it would be beneficial for the framework to attempt to convert to `str` or `to_dict` (by checking) prior to passing onto the default encoder.

Otherwise, good job! It's a pleasure using the framework :)

**Comment by dtkav** [comment]
My 2c: I don't think it makes sense for Connexion to know about mongo, or to make guesses about objects and automatically cast them to strings.

**Comment by belthaZornv** [comment]
I agree completely. - It would be nice to see more examples added though.
