### ISSUE TITLE
Ability to configure the HTTP header to retrieve JWT from

### ISSUE THREAD

**Issue by callkalpa** [zalando/connexion#1064]
### Description
I am trying to use JWT authentication in my API. I am following example: https://github.com/zalando/connexion/tree/master/examples/openapi3/jwt. 

My issue is, in the API call, JWT comes in a different (custom) HTTP header rather than in `Authorization`.

### Expected behaviour

Ability to define a header to retrieve JWT from. May be a user defined function, something similar to `x-bearerInfoFunc`.

### Actual behaviour

In current implementation, it is hard coded to retrieve JWT from `Authorization` header, 
https://github.com/zalando/connexion/blob/2.4.0/connexion/decorators/security.py#L163

**Comment by dtkav** [comment]
I think you want to use the API key security scheme.
That scheme will allow you to specify the header that you'd like to use.
https://github.com/zalando/connexion/blob/master/examples/openapi3/apikey/openapi.yaml
