### ISSUE TITLE
Explore using jsonschema to validate requests

### ISSUE THREAD

**Issue by jmcs** [zalando/connexion#108]
Swagger's [Schema Objects](http://swagger.io/specification/#schemaObject) follow the [JSON Schema] so using (http://json-schema.org/) [jsonschema](https://pypi.python.org/pypi/jsonschema) to validate the requests can make connexion much simpler.

**Comment by hjacobs** [comment]
True, we should try it out

**Comment by valgog** [comment]
One should be really careful as JSON parsing is the heaviest operation in connexion for now.

**Comment by hjacobs** [comment]
JSON Schema validation was released in https://github.com/zalando/connexion/releases/tag/1.0.28

Please check and report any issues..

**Comment by hjacobs** [comment]
@jmcs can we close this issue?
