### ISSUE TITLE
Default values not dependent on _in type (query, form, path)

### ISSUE THREAD

**Issue by fzonneveld** [zalando/connexion#1082]
### Description

Strict validation is on.
Swagger yaml contains default value for a parameter with "in:  query". Validation always fails because the validation includes the default value in the form data as an extra unexpected parameter.

### Expected behaviour
Should work

### Actual behaviour
Does not work

### Steps to reproduce
query parameter with default value and strict validation enabled (this will check the input form data)

### Additional info:
```
--- a/connexion/decorators/uri_parsing.py
+++ b/connexion/decorators/uri_parsing.py
@@ -133,14 +133,14 @@ class AbstractURIParser(BaseDecorator):
                 resolved_param[k] = values[-1]
 
         # set defaults if values have not been set yet
-        resolved_param = self.set_default_values(resolved_param, self.param_schemas)
+        resolved_param = self.set_default_values(resolved_param, self.param_schemas, _in)
 
         return resolved_param
 
-    def set_default_values(self, _dict, _properties):
+    def set_default_values(self, _dict, _properties, _in):
         """set recursively default values in objects/dicts"""
         for p_id, property in _properties.items():
-            if 'default' in property and p_id not in _dict:
+            if 'default' in property and property['in'] == _in and p_id not in _dict:
                 _dict[p_id] = property['default']
             elif property.get('type', False) == 'object' and 'properties' in property:
                 _dict.setdefault(p_id, {})
```

**Comment by dtkav** [comment]
I have an open PR that cleans up the breaking commit here #1110 - it should also resolve this issue.

**Comment by bwo** [comment]
would you consider making a 2.4.1 release? 2.4.0 is broken, and 2.5.0 doesn't run under python 2. (yes, I know, we're working on it. this is part of the upgrade path.)
