### ISSUE TITLE
Simple HTTP Cache Using Resty E-Tags

### ISSUE THREAD

**Issue by kleijnweb** [zalando/connexion#109]
REST has well known semantics that make it relatively easy to employ E-Tags for both caching and (optimistic) concurrency control. I'm mostly interested in caching right now.

Simple implementation:

 - Serve from memory if available, remove when invalidated
 - Enforce a limit based on byte length, pop when exceeded
 - POST on `/resource` invalidates` /resource`
 - PUT, PATCH or DELETE on `/resource/1` invalidates `/resource/1` __and__ `/resource` (but not `/resource/2`)
 - GET `/resource` and `/resource/1` are saved using url-based E-Tags

This can be relatively easily implemented using Varnish, but that's not the point. Use cases might differ but for me personally it is going to be faster to implement this than get the infra needed for Varnish (don't ask). Or at least that's my assumption, not hindered by any intimate knowledge of the platform :stuck_out_tongue_winking_eye: Once implemented, it definitely going to be faster than getting Varnish set up for anyone else.

Thoughts, hints? Flask decorators seem the way to go, but anything more concrete maybe?

**Comment by danballance** [comment]
I'm not familiar enough with the code to contribute constructively right now, but I did just want to add that this would be a nice feature to have.

When you say cached in memory, might this be configurable to use something like memcached? Or would setting up memcached be as much work as Varnish and defeat the purpose?

**Comment by kleijnweb** [comment]
It'd be less work from your perspective as what I was referring to would encompass writing the needed VCL. For me, writing the VCL and implementing this into Flask/Connexion would be comparable.

When I say 'platform', I mean Python->Flask->Connexion. And when I say 'in memory' I mean Flask running indefinitely. Although writing/reading to/from memcached would probably be trivial to add.

**Comment by danballance** [comment]
:+1:

**Comment by kleijnweb** [comment]
I just realized I'm being silly :blush: A 304 does not need a body, so there's no need to keep the responses in memory. The client should keep its own cache.

**Comment by kleijnweb** [comment]
@hjacobs @danballance 

I created a gist of what I came up with. Totally untested and is not going to plug-in into connextion as is. I'm looking for some feedback.

Gist: https://gist.github.com/kleijnweb/f11ae17446ab6e72107d

Basically it:

1. Enables content-hash based ETagging by default. The cache then (you can plugin anything that supports `get`, `set` and `has`) contains the current ETags, indexed by URI path.
2. Optionally enables server-side caching, in which case the cache also contains the response data, and hits are returned as `200` instead of `304`.
3. Includes the concurrency control from #111: when trying to modify and passing If-Match, it has to match the ETag in the cache (if it exists), otherwise a 412 is returned (planning on adding an option that makes the header required and throws 428 when missing).
4. Optionally uses RESTy behavior, using a counter as ETag instead of hashing the content, and invalidating all segments in a path (probably skip numeric values later). Probably allow the counter version in non-resty versions too.

I would really appreciate some feedback. And some pointers on integration (note the TODO's). Thanks.

**Comment by danballance** [comment]
Hi,

I'm not really qualified to comment on your TODO concerns. I'll leave that to someone more ecperienced with the code base I think! But in principle it looks good to me. ETag support working "out of the box" would be a really nice feature I think and I could see myself using this. Even so, I wonder if it should be switched on via a config setting and not be on by default?

**Comment by kleijnweb** [comment]
As with any type of caching, you should at least be able to disable it. The "by default" above refers to the plugin, not connexion. I feel it would make sense so handle ETag related headers by default, but suspect that type of decision is better handled separate from adding the option.

**Comment by hjacobs** [comment]
BTW (as a side note): uWSGI supports some kind of "cache" memory region for server-side caching (uWSGI has "better" concurrency behavior than Python with GIL), see http://uwsgi-docs.readthedocs.org/en/latest/PythonModule.html#cache-functions

**Comment by kleijnweb** [comment]
Hmm. That reminds me to add an internal optimistic locking mechanism. Just validating that the ETag hasn't changed since the request started would do :)

**Comment by LappleApple** [comment]
@kleijnweb @danballance @hjacobs Going through the issues on this project and this one's pretty old. What would you guys like to do here? Should I close it, or do you want to leave it open for something?

**Comment by kleijnweb** [comment]
@LappleApple You can close it. Don't have the time for it right now.
