### ISSUE TITLE
Regression in 2.4.0: spurious ERRORs logged saying "Function argument not defined in specification"

### ISSUE THREAD

**Issue by arel** [zalando/connexion#1092]
### Description

Connexion produces spurious ERRORs that function arguments are not defined in schema, *even though they are.* These errors appear in connexion version `2.4.0` and do not in `2.3.0`. The errors appear for every request.

I find the error appears in cases when a formData argument coexists with query arguments that have a default value.

For example:

```
2019-12-05 10:47:00,123 connexion.operations.swagger2 ERROR    Function argument 'queryArg1' not defined in specification
2019-12-05 10:47:00,123 connexion.operations.swagger2 ERROR    Function argument 'queryArg2' not defined in specification
2019-12-05 10:47:00,123 connexion.operations.swagger2 ERROR    Function argument 'queryArg3' not defined in specification
```

Seems like it might be related to an old bug #522.

### Expected behaviour

No errors should be produced when arguments are defined in spec.

### Actual behaviour

Errors are produced.

### Steps to reproduce

```yaml
  ...
  /orgs/{org_id}/resource:

    post:
      operationId: "controllers.create_resource"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "org_id"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
      - name: "queryArg1"
        in: "query"
        description: ""
        enum: [all, one, two, three]
        default: "all"  # NOTE has default value
        type: "string"
      - name: "queryArg2"
        in: "query"
        description: ""
        default: false  # NOTE has default value
        type: "boolean"
      - in: "query"
        name: "queryArg3"
        type: "boolean"
        default: false  # NOTE has default value
        description: ""
      - in: "formData"  # NOTE in formData
        name: "upload_file"
        required: true
        type: "file"
        description: "The file to upload."
      responses:
        200:
          description: "successful operation"
        404:
          description: "Not found"

```

In python, we have something like this:

```python
def create_resource(org_id, queryArg1='all', queryArg2=False, queryArg3=False):
    return {"ok": True}
```

### Additional info:

Output of the commands:

- `python --version`

Python 3.7.5

- `pip show connexion | grep "^Version\:"`

Version: 2.4.0

**Comment by dtkav** [comment]
`connexion.operations.swagger2` hasn't changed in a long while.
My guess is that it's related to this PR #791 but I haven't had a chance to track it down fully.

somewhat unrelated: using a POST request with query params is not a very common thing to do AFAIK. Why not include these fields in the formdata?

**Comment by osma** [comment]
I'm also getting these errors with 2.4.0. In my case, all the parameters are in formData:

```
      parameters:
        - $ref: '#/parameters/project_id'
        - name: text
          in: formData
          description: input text
          required: true
          type: string
        - name: limit
          in: formData
          description: maximum number of results to return
          required: false
          type: integer
          default: 10
        - name: threshold
          in: formData
          description: 'minimum score threshold, below which results will not be returned'
          required: false
          type: number
          default: 0
```

Here is the corresponding function signature:

```
def suggest(project_id, text, limit, threshold):
```

I get the error messages for the `limit` and `threshold` parameters, which have default values set in the spec. If I remove the default values from the spec, the errors go away.
