### ISSUE TITLE
New Branch for v2; Master for v3

### ISSUE THREAD

**Issue by cognifloyd** [zalando/connexion#1096]
### Description
There are several pending PRs where it would be nice to start merging in backwards incompatible changes for a version 3. Can we please create a new `stable-v2` branch for ongoing fixes to v2 and then use master to start including the v3 changes?

@dtkav, @hjacobs, @jmcs - What do you think? What else could we target for v3?

Pending v3 changes: #760 #828 #1095

**Comment by hjacobs** [comment]
@cognifloyd I propose to switch to Calendar Versioning (#1100) and try to be backwards compatible, but break it when needed. I think SemVer is an illusion (as we would not really maintain any v2 branch) and I would rather like to roll forward and do quicker iterations. Connexion users can always decide whether they want to update or not, but at some point they would need to update (as there is no maintenance for old major versions).

**Comment by RobbeSneyders** [comment]
Closing in favor of #1395
