### ISSUE TITLE
Option to disable validatorUrl

### ISSUE THREAD

**Issue by exdevlin** [zalando/connexion#110]
This option was implemented in https://github.com/swagger-api/swagger-ui/issues/630 but has not made its way here. It would be nice to have the option available in the swagger.yaml to either use a different validator or disable the validator indicator at the bottom of the UI page. The API I'm currently building out is an internal one, so we'd rather not be hitting an external validator.

**Comment by hjacobs** [comment]
:+1: sounds like a reasonable request

**Comment by hjacobs** [comment]
Online validator is now disable by default, released in https://github.com/zalando/connexion/releases/tag/1.0.38
