### ISSUE TITLE
Suggestion: generate AWS Lambdas / Azure Functions that implement an OpenAPI spec

### ISSUE THREAD

**Issue by robertlagrant** [zalando/connexion#1103]
### Suggestion
AWS Lambdas / Azure Functions stand up a single endpoint. To keep the magic of spec-first, it's possible to wrap an entire Flask app in a function, but that loses the point of Serverless.

It would be great to have a way to directly generate the functions in a project, based on an OpenAPI file.

**Comment by hjacobs** [comment]
I think this would be out of scope for this project (Connexion), but feel free to start a new project for serverless OpenAPI functions.

**Comment by dtkav** [comment]
Closing as out of scope. Please reopen if I missed something!
