### ISSUE TITLE
Modify or add to the CSS for Swagger UI

### ISSUE THREAD

**Issue by ahuston-indigoag** [zalando/connexion#1106]
### Description
To use the Swagger UI get token Authorization with AUTH0, we need to add a JS file that copies the audience from the request parameters to the request body. This requires modifying or adding CSS on startup that initializes the JS. See https://community.auth0.com/t/auth0-swagger/19954/10

### Expected behaviour
We expected to find documentation on modifying Connexion's Swagger UI CSS, or some CSS file within connexion that could be changed.

### Actual behaviour
We are unable to find JS or CSS files in the connexion source, or documentation on how to modify them.

### Steps to reproduce
connexion arthuston$ find . -name '*.cs'
connexion arthuston$ find . -name '*.js'

### Additional info:

Output of the commands:

- `python --version`
Python 3.7.2

- `pip show connexion | grep "^Version\:"`
Version: 2.4.0

**Comment by dtkav** [comment]
https://github.com/zalando/connexion/blob/master/README.rst#the-swagger-ui-console

Please see this section of the readme.

**Comment by dtkav** [comment]
I'm going to close this for now - please reopen if you aren't able to get it to work by following the linked section of the documentation above, or you need more help.

**Comment by eharvey71** [comment]
Greetings, I'd like to re-open this for different reasons. Happy to create a new issue. 

I simply want to remove the topbar from the default swagger-ui.css. The documentation in the link above disucsses disabling the UI completely. I would like to find a way to make a few subtle updates to the CSS. I'm wrapping the API UI into a route and placing behind authentication, so it will appear seamlessly as a page within my application. Thank you!
