### ISSUE TITLE
pip install in py2.7 pulls in unsupported 2.5.0

### ISSUE THREAD

**Issue by spacether** [zalando/connexion#1108]
### Description

pip installing connection in a py2.7 env pulls in unsupported 2.5.0

### Expected behaviour

One of the older releases should be installed instead

### Actual behaviour

The newest release 2.5.0 is pulled in

### Steps to reproduce

```
virtualenv venv -p /usr/local/bin/python
source venv/bin/activate
pip install connexion
```
Inspect the terminal to see what version was installed and we see:
```
Collecting connexion
  Using cached https://files.pythonhosted.org/packages/fa/ce/e3f760c75176282ddb8c5600ed9849aa09873fbaf7f9503832ee8041c855/connexion-2.5.0-py2.py3-none-any.whl
```

### Additional info:

Output of the commands:

- `python --version` Python 2.7.15
- `pip show connexion | grep "^Version\:"` Version: 2.5.0

**Comment by spacether** [comment]
This was resolved by the above merge

**Comment by hjacobs** [comment]
Released: https://github.com/zalando/connexion/releases/tag/2.5.1
