### ISSUE TITLE
Support not just API-first but API-design first

### ISSUE THREAD

**Issue by fosrias** [zalando/connexion#1115]
### Description
Currently, connexion does not appear to allow design first workflows where one works out an 
API design modification in their api description file in the source repo that connexion is running. It always tries to add a path for an operation and if there is no function implementing a path, you get an error trying to resolve the function and if you don't have an operationId it errors. There is no ability to skip a path currently and so there is no possibility or work on APIs and run mock services, etc. unless that design function is done outside of version control or without actually running the application (which means I cannot incrementally implement my new design).

Am I missing something or is there a way to do this that is not documented?

### Desired behaviour
Ideally, I can add a `x-connexion-skip` flag, or something to that effect, to tell connexion to ignore a particular operation (with some logging to warn this is happening). This would allow developers to make changes to an API doc, create new resources before they are implemented, and then also incrementally implement those changes, which is actually API-first IMO (i.e. design first).

Would you be open to a pull request to implement this?

**Comment by fosrias** [comment]
nm. Just set resolver_error=501 and you are fine.

**Comment by hjacobs** [comment]
@fosrias feel free to submit a PR to improve the docs for the next person hitting the same issue.

**Comment by cognifloyd** [comment]
@fosrias How did you set `resolver_error`? Did you use the `--stub` cli option? Or something else?

**Comment by fosrias** [comment]
@cognifloyd 
```python
app = connexion.FlaskApp( __name__, specification_dir=spec.parent, 
        options=settings.CONNEXION_OPTIONS
)
api = app.add_api(
        spec.name,
        resolver=settings.CONNEXION_RESOLVER,
        resolver_error=settings.CONNEXION_RESOLVER_ERROR,
)
```
@hjacobs Will work on PR soon.
