### ISSUE TITLE
Question: V1 Support

### ISSUE THREAD

**Issue by hmajid2301** [zalando/connexion#1118]
### Description

I am currently using connexion v1.5.3. I would like to add a fix to an bug related to x-nullable support and $refs (#1070). Is there any way to merge in my fix ? I cannot currently upgrade to connexion version 2 (easily). I don't see a v1 branch but seeing as there is now a v2 and v3 branch could we add a v1 branch for some backwards compatibility ? 

Thanks

**Comment by hjacobs** [comment]
I don't think we can or want to support the old v1 release, but I created some "v1_unsupported" branch from the v1.5.3 tag so your bugfix might find a home: https://github.com/zalando/connexion/tree/v1_unsupported

**Comment by hmajid2301** [comment]
Thank you very much :)
