### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by bilalshaikh42** [zalando/connexion#1121]
Hello,
Sorry for creating an issue for a minor question, but I was just wondering when the next release onto PyPI would be? I am working on a project that needs to install connexion via pip and needs the changes implemented in the last commit. 

Thanks!

**Comment by dtkav** [comment]
There's no fixed release schedule. Thanks for letting us know you'd like to see a new release.
In the meantime you can use:
```
pip install git+https://github.com/zalando/connexion.git@f6e8b8c9ea9f34714d87d20f4cb2230cba18610e#egg=connexion
```
