### ISSUE TITLE
Request parameters with `object` schema is not parsed with special characters

### ISSUE THREAD

**Issue by aysegulpekel** [zalando/connexion#1129]
### Description

While parsing a request with `object` schema and sending its parameters with special characters, it doesn't get parsed and returns None type. 

### Expected behaviour
If such query is requested: 
[GET] "http://localhost:80/path/1/queries?sort[so$me&sort.order]=desc" 
we expect to get parsed argument as: `sort=so$me&sort.order`

### Actual behaviour

"http://localhost:80/path/1/queries?sort[so$me&sort.order]=desc" - we get `sort=None`

### Steps to reproduce
Swagger template has the reference of sort object as follows:
```
paths:
  /query/{id}:
    get:
      operationId: "app.controller.query.function"
      - name: sort
        required: false
        in: query
        style: deepObject
        explode: true
        schema:
          type: object
          additionalProperties:
            type: string
      responses:
        200:
          description: "successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  query_id:
                    type: string
```

### Additional info:

Output of the commands:

- `python --version` = Python 3.7.4
- `pip show connexion | grep "^Version\:"` =  2.5.1

**Comment by dtkav** [comment]
there is a small section in the OpenAPI spec that limits the allowed characters unless you explicitly allow them with `allowReserved`, which we may want to look into before releasing this.

**Comment by hjacobs** [comment]
i.e. the regex should be changed to NOT include `:/?#[]@!$&'()*+,;=` characters

**Comment by drummerwolli** [comment]
will check tomorrow to extend this

**Comment by drummerwolli** [comment]
actually the spec is not forbidding those values, it's just mentioning that you need to encode those, and `allowReserved` is making them available without encoding. but technically they are always allowed. where is the decoding of the URI parameters happening? it's before this regex applies, or? @hjacobs @dtkav

**Comment by hjacobs** [comment]
I think the URI parsing is already done (e.g. by Flask when using `request.args`), so we should be fine (?).

**Comment by dtkav** [comment]
Thanks for digging into it @drummerwolli 
Thank makes sense to me. Both werkzeug (for Flask) and yarl (for aiohttp) should be doing the right (`allowReserved: false`) behavior as far as I can tell.

**Comment by drummerwolli** [comment]
i will then leave it as it is ...
