### ISSUE TITLE
Request: collection_endpoint_name should route to 'get' function, not 'search' function

### ISSUE THREAD

**Issue by caffeinatedMike** [zalando/connexion#1141]
Reviewing the `RestyResolver` and the sibling `MethodViewResolver` code and I'm curious why it defaults to the `search` function of the `MethodView` class. In following true REST conventions doesn't it make more sense for an empty GET `/something` endpoint to be routed to the `MethodView`'s `get` function? That way all function names within the class are REST verbs.

I get that that would mean both `/something/{abc}` and `/something` would route to the same function, but it should be the developer's responsibility to provide a parameter in the `get` function that defaults to None.

Thoughts?

**Comment by dtkav** [comment]
Hey @caffeinatedMike - IIRC the reason for having a different name (`search`) for collections is that some other HTTP methods also call the `get` method (like HEAD).

The name for collections is an init argument to `RestyResolver` and `MethodViewResolver` though, so I think you can specify `get` here: https://github.com/zalando/connexion/blob/master/connexion/resolver.py#L74

**Comment by caffeinatedMike** [comment]
Ahh, I did see that line in the code but didn't think about setting it when instantiating the app. Thanks!
