### ISSUE TITLE
Feature Request: Allow easier customization of Swagger UI through App config dictionary

### ISSUE THREAD

**Issue by caffeinatedMike** [zalando/connexion#1142]
Currently, in order to customize the Swagger UI it involves using the `swagger_ui_bundle` package and working with the `index.j2` jinga file. What I propose is we eliminate the need for the additional dependency and bundle it automatically with the `connexion` package. 

## How...?  

- ...would this look?  
[Swagger UI app config dict](https://github.com/flasgger/flasgger#swagger-ui-and-templates)   
And an example of a config:  
  
```python3  
app.config['SWAGGER'] = { 
    # Webpage's Tab Name
    'title': 'TestAPI', 
    # Allows selection of ui2 or ui3
    'uiversion': 3,
    # Setting this would mean we're not using Swagger 2.0, but OpenAPI 3.0.1
    'openapi': '3.0.1', 
    # Allows easily setting the favicon
    'favicon': LazyString(lambda: url_for('static', filename='logo.png')), 
    # Allows easily setting your own custom styling for the Swagger UI
    'swagger_ui_css': LazyString(lambda: url_for('static', filename='swagger-ui.css')),
    # Allows setting all available options provided to the Swagger UI configuration
    # https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
    'doc_expansion': 'none'
}
```  
 - ...would this function?  
 
  We can use the Flasgger package as an example of how to provide [ui2 and ui3 templating](https://github.com/flasgger/flasgger/tree/master/flasgger). It includes many optional jinga variables that can be set in the App config dict highlighted in the above code.  

## Why...?  
- Do I focus on the Flasgger package so much?  
  1. It provides the same core functionality as `connexion`, making it prime competition:  
     * Swagger UI 2 & 3 doc generation  
     * Restful architecture option using `flask-restful`'s `Resource`s  
     * Optional strict validation of content  
  2. It provides a level of control over the UI that `connexion` currently lacks.  
  3. It has the added benefit of no external package dependencies for Swagger docs. That means it's more easily maintainable, more appealing to end-users in terms of get-up-and-go (no pip extras) and allowed for the above proposed fine-grain control over look and feel.  
  4. I was using Flasgger to deal with my Swagger API design and implementation, but quickly found out that when I wanted to update to the new OpenAPI specs that the package just doesn't have the ability to fully accommodate OpenAPI specs. The most important missing key component of that being there is currently no validation of incoming data when utilizing the new OpenAPI specs. 
- Did I switch to `connexion` if there is so much about Flasgger that I liked?
  1. The support is night-and-day. If you look at the unanswered issues over there you'll quickly realize how slow the development and bug-resolution is. Whereas here you can tell that the community is vibrant and responsive and available to converse about issues and proposals.  
  2. Support for continual validation of incoming data against OpenAPI 3 specs. This is a huge deal for me because when a package is unable to validate incoming content for an API it becomes a non-starter. That's what the frameworks are meant to do, properly validate.  
  3. Another big deciding factor for me was the auto-routing, which is amazing. While it might seem trivial to add the routes and resources, it saves frustration when adding new resources and endpoints since you're able to manage all the routing from a single file (the spec file).

**Comment by RobbeSneyders** [comment]
We explicitly split the ui bundle into a dependency so it only needs to be installed when needed (#406). You can pass UI configuration options via `options.openapi_console_ui_config`. [docs](https://connexion.readthedocs.io/en/latest/quickstart.html?highlight=console%20ui%20config#the-swagger-ui-console)
