### ISSUE TITLE
ImportError: cannot import name 'FileStorage' from 'werkzeug'

### ISSUE THREAD

**Issue by bijualappatt** [zalando/connexion#1149]
### Description
Getting below import error when using connexion 1.1.15
cannot import name 'FileStorage' from 'werkzeug'

### Expected behaviour
import connexion should work without issues

### Actual behaviour
File "/opt/bitnami/python/lib/python3.7/site-packages/connexion/decorators/validation.py", line 9, in <module>
    from werkzeug import FileStorage
ImportError: cannot import name 'FileStorage' from 'werkzeug' (/opt/bitnami/python/lib/python3.7/site-packages/werkzeug/__init__.py)

### Steps to reproduce
pip install connexion == 1.1.15

import connexion

### Additional info:
The issue started on Feb 7, 2020 as werkzeug ver 1.0.0 released. 
werkzeug is a dependency of connexion and ver 1.0.0 is installed as a pre-requisite from Feb 07, 2020.
Workaround : Install werkzeug ver 0.16.1 before installing connexion

Output of the commands:
 
- `python --version`  Python 3.7.4
- `pip show connexion | grep "^Version\:"`  Version: 1.1.15

**Comment by dneuhaeuser-zalando** [comment]
This has already been fixed with https://github.com/zalando/connexion/pull/1044

**Comment by htjain** [comment]
I am also seeing this error since yesterday. 

> 
> $ ./pip show connexion | grep "^Version\:"
> Version: 2.0.0
>

**Comment by jmcs** [comment]
Have you tried using the most recent version of Connexion (2.6.0)? 2.0.0 is more than one year old.

**Comment by htjain** [comment]
@jmcs  thanks. Using latest version +   `werkzeug==0.16.1   `solved this problem.

**Comment by eranhirs** [comment]
We were using ` connexion==2.2.0` and started getting this error.
Using `connexion==2.6.0` (without specifying any `werkzeug` dependencies) solved the problem.

**Comment by WRossStreet** [comment]
I've upgraded to 2.6.0 from 1.5.3 and a number of calls get this error:

'bytes' object has no attribute 'update'

coming from connexion/decorators/validation.py, line 161

any ideas how to fix this?

**Comment by binchick-in** [comment]
My use case is a **Flask Swagger API**

I pinned to the following packages and my build resolved the issue.
```
Werkzeug==0.15.6
Flask==1.1.1
connexion==1.5.3
```

To help those that might be searching for this, here is my error

```
Traceback (most recent call last):
  File "./wsgi.py", line 10, in <module>
    from swagger_server.server import app
  File "./swagger_server/server.py", line 4, in <module>
    import connexion
  File "/usr/src/app/py3_env/lib/python3.6/site-packages/connexion/__init__.py", line 3, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/usr/src/app/py3_env/lib/python3.6/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/usr/src/app/py3_env/lib/python3.6/site-packages/connexion/apis/abstract.py", line 14, in <module>
    from ..operation import Operation
  File "/usr/src/app/py3_env/lib/python3.6/site-packages/connexion/operation.py", line 10, in <module>
    from .decorators.response import ResponseValidator
  File "/usr/src/app/py3_env/lib/python3.6/site-packages/connexion/decorators/response.py", line 12, in <module>
    from .validation import ResponseBodyValidator
  File "/usr/src/app/py3_env/lib/python3.6/site-packages/connexion/decorators/validation.py", line 10, in <module>
    from werkzeug import FileStorage
ImportError: cannot import name 'FileStorage'
```

While this might not be **_THE_** solution, it seems to have worked for me at this time.

I'll be experimenting with different versions but since this is a fresh issue popping up, I wanted to get something out here to help those pulling their hair out.

**Comment by peschue** [comment]
I am using conda and the same problem appeared when updating in conda to the latest versions:

connexion                 2.3.0                      py_0  
flask                     1.1.1                      py_0  
werkzeug                  1.0.0                      py_0  

After updating to the latest versions using the channel conda-forge, it now works as expected!

connexion                 2.6.0                      py_0    conda-forge
flask                     1.1.1                      py_1    conda-forge
werkzeug                  1.0.0                      py_0    conda-forge

**Comment by NikolaiT** [comment]
I know this doesn't help in any way whatsoever, but Python is just broken in so many ways when you want to use it for production stuff. 

It never works. It's extremely confusing what version of python to use, what virtualenv tool (virtualenv, pipenv, ...) , what package manager (pip, pip3, conda, easy_install, ..........), where actual configuration is stored...

In my opinion, it was a huge mistake to allow two supported versions of python to co-exist. I know I know, backwards compatibility, but honestly, when production software makes use of such code:

```python

if PY2K:
    import thread
else:
    import _thread as thread
```

it's just broken and needs to be dropped.

**Comment by andvazqu** [comment]
Same use case and issue as binchick-in. These versions solved the problem for us:
flask=1.1.1 werkzeug=0.16.0 connexion=2.3.0

**Comment by glroman** [comment]
% conda uninstall connexion # removed connexion-2.3.0
% pip install connexion  # installed 2.6.0

Problem gone.  (and werkzeug==1.0.0)

**Comment by ramgrandhi** [comment]
Just by pinning **connexion==2.6.0** in *requirements.txt* file fixed the issue!

**Comment by cognifloyd** [comment]
Hmm. It looks like connexion needs to declare werkzeug as a direct dependency and not rely on our dep to flask to pull that in.

**Comment by Santhosh-KS** [comment]
Looks like they moved the FileStorage under datastructrues.

```python
from werkzeug.datastructures import FileStorage
```

Solved the problem for me.

**Comment by patrickkwang** [comment]
Thanks @ulidtko for the rundown. It sounds like this is not fixable _per se_ because it does not affect the latest version of connexion. However, we may be able to prevent something similar from happening again in the future by adding an explicit dependency on werkzeug with version <2.0. Yes?

**Comment by ulidtko** [comment]
Hey @patrickkwang yes that's right; it's fixable but in Swagger, they need a change to emit `requirements.txt` with more up-to-date `connexion`. Maybe you, or anyone else really, could submit a PR doing that. This repo, I think, requires no change.

`werkzeug < 2.0` is definitely a good idea! Major version updates are exactly for API-breaking changes (a-la the `FileStorage` update) and those should never happen automatically. For one, declaring `werkzeug` explicitly is the right thing to do; but adding upper major version bound is extra-nice, and will definitely help everybody.

**Comment by ulidtko** [comment]
BTW here's that PR against Swagger bumping `connexion`, finally filed https://github.com/swagger-api/swagger-codegen-generators/issues/780

When that is merged & released, this issue may finally rest in peace.

**Comment by georgegoldman** [comment]
> @jmcs thanks. Using latest version + `werkzeug==0.16.1 `solved this problem.

it worked quickly well

**Comment by ulidtko** [comment]
Hey all, just a quick update.

Since [this fix][1] got merged and released a while ago, nobody should get bitten by this issue anymore.

If you do — please make sure to use connexion at least 2.7.0 version.

The last thing to do before closing this issue is merging #1302 which should be easy & safe (current Werkzeug is 1.0.1).

[1]: https://github.com/swagger-api/swagger-codegen-generators/commit/45812fd7b4953af57831041ae6315ddec1595760
