### ISSUE TITLE
Cache a pandas DataFrame with Flask-Cache

### ISSUE THREAD

**Issue by PickHub** [zalando/connexion#1154]
### Description
I'm getting an error when using FlaskCache with Connexion. Are there any alternatives?

I have a function that reads a CSV and creates a pandas DataFrame. Instead of doing that for every request I'd like to cache the DataFrame for multiple requests.

### Actual behaviour
I'm creating the cache as follows:

```
from flask.ext.cache import Cache

app = connexion.App(__name__, swagger_ui=True)
cache = Cache(app,config={'CACHE_TYPE': 'simple'})
```

This brings the following error in "flask_caching\__init__.py", line 166:
`base_config = app.config.copy()`
AttributeError: 'App' object has no attribute 'config'

### Additional info:

Output of the commands:

- `python --version` 3.6.5
- `pip show connexion | grep "^Version\:"` 1.0.129
- Windows 10

**Comment by dtkav** [comment]
Try this:
```
app = connexion.App(__name__, swagger_ui=True)
flask_app = app.app
cache = Cache(flask_app, config={'CACHE_TYPE': 'simple'})
```
You need to access the flask app under the hood.

**Comment by PickHub** [comment]
Perfect, thanks!
