### ISSUE TITLE
Installing latest connexion with pip gives '2018.0.dev1' version

### ISSUE THREAD

**Issue by qasimalbaqali** [zalando/connexion#1155]
### Description
When installing connexion with swagger-ui using pipenv 
`pipenv install "connexion['swagger-ui']"` the version that get installed is `2018.0.dev1` instead of `2.6.0`

### Expected behaviour
The version `2.6.0` is installed

### Actual behaviour
Version `2018.0.dev1` is installed instead

### Steps to reproduce
`pipenv install "connexion['swagger-ui']"`

### Additional info:

Output of the commands:

- `python --version` Python 3.7.4
- `pip show connexion | grep "^Version\:"` Version: 2018.0.dev1

**Comment by kvdb** [comment]
Same problem here.
Worked around it by ignoring that prerelease in ``Pipfile``:

`connexion = {extras = ["swagger-ui"],version = "!=2018.0.dev1"}
`

**Comment by Ruwann** [comment]
I believe this was fixed (I can't seem to reproduce it anymore), please reopen if not so.
