### ISSUE TITLE
How to use HTTPS ?

### ISSUE THREAD

**Issue by rudyces** [zalando/connexion#1157]
### Description
I made a connexion API and i do not succeed to go from HTTP to HTTPS
Is it even possible ? I don't see any exemples on it.

Here is the entrypoint of my API:

```
def main():
    flask_app = connexion.FlaskApp(
        __name__,
        port=9090,
        specification_dir='test/')

    flask_app.add_api(TEST_FILE)

    if flask_app.app.config['ENV'] == 'prod':
        serve(flask_app, port=9090)
    else:
        flask_app.run()

```

If i can add `ssl_context=context` (like in flask) somewhere it will be perfect but I cannot see where to put it.

Do I need to edit my schemes in my swagger files too ?

Thank you for your help.

**Comment by dtkav** [comment]
Hey @rudyces - I recommend terminating SSL using a reverse proxy like nginx or caddy.

**Comment by rudyces** [comment]
Thanks @dtkav, so there is absolutely no way to give an argument like `ssl_context` as an argument from what I see

**Comment by rudyces** [comment]
I setted up a gunicorn server to launch the app using SSL at the end.
