### ISSUE TITLE
Completely stopped by "No authorization token provided" 

### ISSUE THREAD

**Issue by JuergenSimon** [zalando/connexion#1177]
### Description

Using the following security scheme:

      "JwtTokenAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-access-token"
      }

Adding it to paths like so:

      "paths": {
            "/logout": {
            "post": {
            "operationId": "app.auth.logout",
            "description": "Logging off",
            "security": [
                {
                  "JwtTokenAuth": []
                }
            ]
            ...
      }

### Expected behaviour
After obtaining a token, setting header x-access-token to token results in access granted to secured endpoints. 

### Actual behaviour
*ANY* request to secured endpoints is categorically denied with the following message:

      {
            "detail": "No authorization token provided",
            "status": 401,
            "title": "Unauthorized",
            "type": "about:blank"
      }

### Steps to reproduce
* Secure endpoint with said schema and try accessing it. 

### Additional info:

Output of the commands:

- `python --version`: Python 3.7.6
- `pip show connexion | grep "^Version\:"`: Version: 2.6.0

**Comment by JuergenSimon** [comment]
Note: in startup console displays the following message: `x-apikeyInfoFunc missing`

**Comment by JuergenSimon** [comment]
Update: what did not work was the two parameters: 
    
    ...
     "in": "header",
    "name": "x-access-token"
    ....

in the security scheme definition. While according to standard this should work, connexion does not support it. The only way to denote the token in the header is to use the header format:

   'Authorization: Bearer <encoded jwt token>'

After changing over to this format in my requests, it started working. However, the ticket should be used to make connexion comply with the standard in this.

**Comment by asofiasbo** [comment]
I'm having the same problem... But I can see the token is sent in the Head
<img width="553" alt="Captura de ecrã 2020-04-24, às 12 00 05" src="https://user-images.githubusercontent.com/22176365/80206136-bfea4480-8623-11ea-88ee-b0e6c0675d89.png">
er with the format you mentioned, @JuergenSimon. Still, the response is "No authorization token provided"

I think the problem can maybe be related to the incompatibilities of versions used, but I already tried different versions and the problem persists. 

Here are the versions I'm using: 

```
requests==2.18.4
gunicorn==19.8.1
connexion==2.6.0
condu==2.0.0b10
Flask-PyMongo==2.2.0
Flask-JWT-Extended==3.17.0
Flask-Cors==3.0.7
```

I also get the warning about the x-apikeyInfoFunc missing (I was previously using connexion 1.4).

**Comment by asofiasbo** [comment]
I'm having the same problem... But I can see the token is sent in the Header with the format you mentioned, @JuergenSimon. Still, the response is "No authorization token provided". 
<img width="553" alt="Captura de ecrã 2020-04-24, às 12 00 05" src="https://user-images.githubusercontent.com/22176365/80206328-05a70d00-8624-11ea-92d7-d1357742fc9c.png">

I think the problem can maybe be related to the incompatibilities of versions used, but I already tried different versions and the problem persists.

Here are the versions I'm using:
```
requests==2.18.4
gunicorn==19.8.1
connexion==2.6.0
condu==2.0.0b10
Flask-PyMongo==2.2.0
Flask-JWT-Extended==3.17.0
Flask-Cors==3.0.7
```

I also get the warning about the x-apikeyInfoFunc missing (I was previously using connexion 1.4).

**Comment by eanunez** [comment]
As per documentation, https://connexion.readthedocs.io/en/latest/security.html in the **ApiKey Authentication** section, _"With Connexion, the API security definition must include a x-apikeyInfoFunc or set APIKEYINFO_FUNC env var"_.

You have to add this line in the securitySchema, `x-apikeyInfoFunc: app.YourTokenFunction`. You would end up having, 
```
"JwtTokenAuth": {
    "type": "apiKey",
    "in": "header",
    "name": "x-access-token"
    "x-apikeyInfoFunc: app.YourTokenFunction"
  }
```
Then you do your token authentication in `app.YourTokenFunction`. Hope this helps.
