### ISSUE TITLE
improve 415 error response

### ISSUE THREAD

**Issue by Gra55h0pper** [zalando/connexion#1181]
### Description
I think error response 415 should be improved.

### Expected behaviour
{
  "detail": "Invalid Content-type (text/html), expected JSON data",
  "status": 415,
  "title": "Unsupported Media Type",
  "type": "about:blank"
}

### Actual behaviour
{
  "detail": null,
  "status": 415,
  "title": "Invalid Content-type (text/html), expected JSON data",
  "type": "about:blank"
}

### Steps to reproduce
set 'Content-Type': 'text/html' in request header.

### Additional info:

Output of the commands:

- `python --version`
Python 3.7.5
- `pip show connexion | grep "^Version\:"`
Version: 2.6.0

Great package by-the-way!!

**Comment by Ruwann** [comment]
Fixed by #1185
