### ISSUE TITLE
Python 3.8 asyncio.coroutine deprecated

### ISSUE THREAD

**Issue by szborows** [zalando/connexion#1182]
### Description

In Python 3.8 `@asyncio.coroutine` was deprecated. It's gonna be removed in Python 3.10. I saw other PRs that stop using `loop` parameter, but still `@asyncio.coroutine` is used in multiple places.

### Expected behaviour

No warnings should be displayed when using connexion.

### Actual behaviour

```
/builds/[redacted]/.tox/py38/lib/python3.8/site-packages/connexion/apis/aiohttp_api.py:48
  /builds/[redacted]/.tox/py38/lib/python3.8/site-packages/connexion/apis/aiohttp_api.py:48: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def problems_middleware(request, handler):
```

### Steps to reproduce

Run any tests on Python 3.8 (requirements we use: `connexion[aiohttp, swagger-ui]==2.6.0`

### Additional info:

Output of the commands:

- `python --version`: `Python 3.8.2`
- `pip show connexion | grep "^Version\:"`: `Version: 2.6.0`

**Comment by cognifloyd** [comment]
Yes, that's a possibility now that we've increased the minimum version of python to 3.6.
Getting rid of asyncio.coroutine is one of the changes I was hoping to see following #977. 
Since then #990 #1056 #1058 have cleaned up our minimum version so we can use async/await now.

**Comment by szborows** [comment]
PR opened. I wonder about this -0.005% coverage problem:

https://coveralls.io/builds/29514899/source?filename=connexion%2Fapis%2Faiohttp_api.py#L324

can you please take a look and give advice?
