### ISSUE TITLE
Finding operation on Connexion API by operation_id

### ISSUE THREAD

**Issue by fosrias** [zalando/connexion#1187]
I do not see a helper method on a connection API to be able to get an operation on an API based on its operation_id. Is there such a method?

If not, would you be open to adding a PR to add such a helper method?

Need this to simplify generating and adding links and URI templates into a response.

Thx.

**Comment by vashek** [comment]
I solved it with this piece of code:

```
import flask
from typing import ...

import users_db


def _link_to_user(user: users_db.User) -> str:
    url_root = flask.request.url_root.rstrip("/")
    return f"{url_root}/users/{user.db_id}"  # don't forget to url-escape if you can't be sure it's an int


ResponseTuple = Tuple[Any, int, Dict[str, str]]


def post(body: Dict[str, Any]) -> ResponseTuple:
    """Create a new user"""
    ... do something to make new_user ...
    try:
        new_user.save(TENANT)
    except UserAlreadyExists:
        return f"user already exists", 409, {}
    return {"db_id": new_user.db_id}, 201, {"Location": _link_to_user(new_user)}
```

(Any feedback is welcome, by the way.)
But I also think a more general version of my _link_to_user() should be in Connexion.
(By the way, in my case I can be sure that `user.db_id` is int, so I believe it's fine, but more generally you would need to url-quote the variable you're inserting into the URL.)

**Comment by fosrias** [comment]
@vashek Thanks. That actually is not solving what I want, which is access to the path definition as the SSOT for the operation and then use that. In your case, you have encoded path info in your `_ _link_to_user` functionality.

But more generally, there is no ability to access an operation in a spec directly for general purpose use beyond my sample use cases, which is really what I am addressing here.

**Comment by fosrias** [comment]
Turns out, can do this in a custom resolver so closing this.

**Comment by vashek** [comment]
For the benefit of anyone looking for the same thing (such as myself three years later apparently), see #924.
