### ISSUE TITLE
How to access tokeninfo response in handler function?

### ISSUE THREAD

**Issue by mnylen** [zalando/connexion#1188]
Is it somehow possible to access/pass the full oauth tokeninfo response to the handler function?

We have added some non-standard fields to our tokeninfo response and it'd be nice to be able to pass them to the handler function.

Right now it seems only the `sub` field from the response can be passed to the handler function as `user` argument. Would it be possible to add similar support for the whole tokeninfo response?

**Comment by glroman** [comment]
If you're using oauth2 security, each protected call gets a `user` and `token_info` parameter passed (if defined.

**Comment by mnylen** [comment]
Thanks. Maybe this should be documented somewhere? The documentation only speaks of 'user' parameter.

In https://github.com/zalando/connexion/blob/master/docs/security.rst

> The sub property of the Token Info response will be passed in the user argument to the handler function.

**Comment by glroman** [comment]
Agree; I found the other parameter by reading the code.

**Comment by dtilchin** [comment]
👍 
I just had to figure this out by reading the code as well.
For clarity to anyone having the same issue, the return value of the auth handler function (this is true of bearer auth at least) goes winds up in `connexion.context['token_info']`.
