### ISSUE TITLE
Dead link in README to a blog post

### ISSUE THREAD

**Issue by dtilchin** [zalando/connexion#1215]
### Description

The link "Zalando Tech blog post API First" in [README.rst](https://github.com/zalando/connexion/blame/master/README.rst#L73) is dead (404). There is an [archive.org snapshot](https://web.archive.org/web/20160304091414/https://tech.zalando.com/blog/on-apis-and-the-zalando-api-guild/), for reference.

I'd open a PR to just remove it, but I'm not sure what the authors' intentions are.

### Expected behaviour

All links in README.rst lead to a functional page

### Actual behaviour

The link "Zalando Tech blog post API First" leads to a 404 page.

### Steps to reproduce

Click the "API First" link in the README (https://tech.zalando.com/blog/on-apis-and-the-zalando-api-guild/)

**Comment by hjacobs** [comment]
Thanks for pointing this out!

**Comment by hjacobs** [comment]
@dtilchin I changed it to link to RESTful API guidelines instead: https://github.com/zalando/connexion/pull/1216
