### ISSUE TITLE
how to use uwsgi_metrics?

### ISSUE THREAD

**Issue by dfeinzeig** [zalando/connexion#122]
i see that if uwsgi_metrics is installed it seems to create timers.  how would i use this?

**Comment by hjacobs** [comment]
You would need to initialize the module (see https://github.com/zalando-stups/connection-tracker/blob/master/app.py#L162) and expose the metrics via HTTP (https://github.com/zalando-stups/connection-tracker/blob/master/swagger.yaml#L26).

NOTE: The linked "Connection Tracker" app (https://github.com/zalando-stups/connection-tracker) is really hacked together and I would not use it as a good example of how to set up a Connexion app!

**Comment by dfeinzeig** [comment]
Cool, thanks!  I'll give it a try!

**Comment by hjacobs** [comment]
@dfeinzeig no problem, just file an issue (as you did) for any questions or problems you might have :smile:
