### ISSUE TITLE
Using custom decorators for controllers

### ISSUE THREAD

**Issue by redamith2** [zalando/connexion#1223]
### Description

to re use code, I have created custom InternalError Decorators, that 

I am aware that we have **app.add_error_handler()** function, but I was wondering if there was a way to wrap controller methods with decorators

### Additional info:

Output of the commands:

- `python --version` 3.6
- `pip show connexion | grep "^Version\:"` 2.6

**Comment by hjacobs** [comment]
Python decorators work as usual, so you can add a decorator with some wrapper logic to your handler function.
