### ISSUE TITLE
helloworld example doesn't work (404)

### ISSUE THREAD

**Issue by Ploppz** [zalando/connexion#1225]
### Description

I cloned the repo, then
```
$ cd examples/openapi3/helloworld
$ ./hello.py
```
Then pressed the link in the [README](https://github.com/zalando/connexion/blob/master/examples/openapi3/helloworld/README.rst) (http://localhost:9090/v1.0/ui/)
I get 404.

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
$ python --version
Python 3.8.2
$ pip show connexion | grep "^Version\:"
Version: 2020.0.dev1
```

**Comment by RobbeSneyders** [comment]
Hi @Ploppz, I cannot reproduce. Feel free to reopen if you can provide more info.
