### ISSUE TITLE
Using Multiple Authentication Types

### ISSUE THREAD

**Issue by p4l1ly** [zalando/connexion#1228]
### Description

The OpenAPI specification talks about boolean connectives (in disjunctive normal form) of authentication types https://swagger.io/docs/specification/authentication/

Connexion supports only disjunction of authentication types, no conjunctions. Even the disjunction does not work as expected: e.g. two basic auths cannot be used in disjunction because the first one raises OAuthProblem if it fails.

### Additional info:

Output of the commands:

- `python --version` `Python 3.8.2`
- `pip show connexion | grep "^Version\:"` `Version: 2020.0.dev1`

**Comment by RobbeSneyders** [comment]
This was fixed by #1290.
