### ISSUE TITLE
Q: how to add Prometheus client /metrics endpoint to Connexion app?

### ISSUE THREAD

**Issue by chrisinmtown** [zalando/connexion#1245]
This is a question, but I don't know how to tag it as such, please do so.

### Description

Would like to extend an existing connexion-based REST app that's run using gevent.pywsgi.WSGIServer() with the Prometheus client library (https://pypi.org/project/prometheus-client/). The goal is to expose a /metrics endpoint that will answer stats when hit via GET.

The Prometheus quickstart doc suggests starting an HTTP server, but of course I already am running one, so that seems wrong.

Some searching suggests that I should define an app that has the /metrics handler method, and it should delegate to the app created by connexion, basically WSGI app chaining, but I'm not sure if that's preferable.

If absolutely necessary I suppose I could add a fake API spec YAML file mapping /metrics to a method in the controller module.

This is vaguely related to issue #1028, how to add an endpoint/method that is not in the OpenAPI spec.

Would also appreciate guidance on how to report to Prometheus the method (e.g., "GET"), the endpoint (e.g., "health"), etc. that are in the OpenAPI spec without repeating them in the controller method.  For example this is just *wrong*:

```
def get_healthcheck():
    counter.labels(method='get', endpoint='/healthcheck').inc()
    ...
```

### Expected behaviour

The webapp will answer requests to /metrics with Prometheus-generated content

### Actual behaviour

N/A

### Steps to reproduce

N/A

### Additional info:

Using Python 3.8 and latest version of connexion, please see code extract below.

```
    import connexion
    from gevent.pywsgi import WSGIServer

    app = connexion.App(__name__, specification_dir=".")
    app.add_api("openapi.yaml", arguments={"title": "My Title"})
    http_server = WSGIServer(("", 10000), app)
    http_server.serve_forever()
```

Thanks in advance for hints, tips, suggestions.

**Comment by chrisinmtown** [comment]
Found a workable solution here:

[](https://www.programcreek.com/python/example/105488/prometheus_client.CollectorRegistry)

Now my code looks like this:

```
import connexion
from prometheus_client import CollectorRegistry, generate_latest, multiprocess

app = connexion.App(__name__, specification_dir=".")
app.add_api("openapi.yaml", arguments={"title": "My Title"})


# python decorators feel like black magic to me
@app.app.route('/metrics', methods=['GET'])
def metrics():  # pylint: disable=unused-variable
    # /metrics API shouldn't be visible in the API documentation,
    # hence it's added here in the create_app step
    # requires environment variable prometheus_multiproc_dir
    registry = CollectorRegistry()
    multiprocess.MultiProcessCollector(registry)
    return generate_latest(registry)
```

**Comment by RobbeSneyders** [comment]
Thx for figuring this out and reporting back @chrisinmtown!
