### ISSUE TITLE
How to ignore to validate the parameters and request bodies ?

### ISSUE THREAD

**Issue by Huangkai1008** [zalando/connexion#1247]
### Description
Hello! I use other tools to validate the inputs in my project, how to ignore the validation by connexion? I see a parameter called `validate_responses`, can you provide similar parameter or method for this situation，thank you very much !

### Expected behaviour
connexion not to validate the inputs

### Actual behaviour
connexion always validate the inputs

### Steps to reproduce
N/A

### Additional info:
N/A

Output of the commands:

- `python --version`: Python 3.6.5
- `pip show connexion | grep "^Version\:"`: Connexion 2.7.0

**Comment by RobbeSneyders** [comment]
Hi @Huangkai1008, you can override the validators used for parameter and request body validation. See [docs](https://connexion.readthedocs.io/en/2.9.0/request.html?highlight=validator_map#custom-validators).
