### ISSUE TITLE
How to define free form object in parameters?

### ISSUE THREAD

**Issue by Zedmor** [zalando/connexion#1248]
I am trying to write config for OpenAPI with intention to resolve request like this:
http://127.0.0.1:5000/api/v1/statistics?stratifications=color,blue,bodytype,normal
or
http://127.0.0.1:5000/api/v1/statistics?stratifications=color,blue,bodytype,normal,height,170
or just
http://127.0.0.1:5000/api/v1/statistics?stratifications=color,grey

into object that will get passed to my function. 

so get_statistics will get called with

stratifications=`{'color': 'grey'}` etc 
Idea is that keys and values could be different every time and not bonded to fixed schema

This is what I am writing in the config:

```/statistics:
    get:
      tags: [statistics]
      operationId: mariner_telemetry.api.v1.statistics.endpoints.get_statistics
      {% if not disable_security %}
      security:
        - jwt: [statistics]
        {% endif %}

      parameters:
        - in: query
          name: stratifications
          description: Stratifications of statistic
          schema:
            type: object
          style: form
          explode: false
```

but this results in 

`is not of type 'object'`

error in jsonschema since jsonschema expect dictionary and getting string `color,blue,bodytype,normal,height,170` instead. Are there way to add encoder there? I though style define encoder but it seems to be not the case.

**Comment by RobbeSneyders** [comment]
Hi @Zedmor, you can [use a different `URIParser`](https://connexion.readthedocs.io/en/2.9.0/request.html#type-casting). In your case, you should be able to use the `OpenAPIURIParser` with the [`style` parameter](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#style-examples).
