### ISSUE TITLE
Typo in request handling documentation

### ISSUE THREAD

**Issue by fhaase2** [zalando/connexion#1253]
### Description

https://connexion.readthedocs.io/en/latest/request.html

Typo in documentation

### Expected behaviour

connexion.decorators.uri_parsing.AbstractURIParser

### Actual behaviour

**connextion**.decorators.uri_parsing.AbstractURIParser

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by aminalaee** [comment]
@RobbeSneyders is fixed and can be closed

**Comment by RobbeSneyders** [comment]
Thanks @aminalaee!
