### ISSUE TITLE
Documentation mistake in request handling

### ISSUE THREAD

**Issue by fhaase2** [zalando/connexion#1254]
### Description

https://connexion.readthedocs.io/en/latest/request.html

For overwriting the uri parser, in the documentation it is stated:

`options = {'uri_parsing_class': Swagger2URIParser}`

### Expected behaviour

It must be `options = {'uri_parser_class': Swagger2URIParser}`
https://github.com/zalando/connexion/blob/bed4b95205205861bd6014282d0f61d50231d3ac/connexion/options.py#L125-L131

### Actual behaviour
It is `options = {'uri_parser_class': Swagger2URIParser}`

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by aminalaee** [comment]
@fhaase2 This is fixed and can be closed

**Comment by RobbeSneyders** [comment]
Thx @aminalaee!
