### ISSUE TITLE
AioHttpApp.get_root_path returns string, not pathlib.Path

### ISSUE THREAD

**Issue by ioggstream** [zalando/connexion#1256]
### Description

AioHttpApp.get_root_path returns string
FlaskApp.get_root_path returns pathlib.Path

### Expected behaviour

Both return the same type, eg. pathlib.Path

### Actual behaviour

They use different types. This complicates tests.

### Steps to reproduce

See code.

### Additional info:

Python 3.7.7
Version: 2020.0.dev1

**Comment by Ruwann** [comment]
Thanks for the report! It indeed makes sense that AioHttpApp also returns a `pathlib.Path` instance
