### ISSUE TITLE
Respect "required: false" specification on headers

### ISSUE THREAD

**Issue by miguelgf** [zalando/connexion#1261]
### Description
Based on the OpenAPI 3, the "headers" key on a response, respects the `Map[string, Header Object | Reference Object]` interface, and checking the [Header Object](https://swagger.io/specification/#header-object) the description says:

> The Header Object follows the structure of the Parameter Object with the following changes:

Checking the [Parameter Object](https://swagger.io/specification/#parameter-object), one of the properties says:

> required | boolean | Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

But Connexion doesn't take into account this, and always force to be defined the headers on the response, even if it's optional (like for example when following the [RFC 8288](https://tools.ietf.org/html/rfc8288)).

### Expected behaviour
If a header is `required: false`, the lack of the header on the response shouldn't raise `NonConformingResponseHeaders`

### Actual behaviour
It raises `NonConformingResponseHeaders`

https://github.com/zalando/connexion/blob/master/connexion/decorators/response.py#L62

### Steps to reproduce

With this openapi schema

```
openapi: 3.0.0
info:
  title: Test
  version: 0.0.1
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: Example headers
          content:
            application/json:
              schema:
                type: object
                required:
                 - data
                properties:
                  data:
                    type: string
                    nullable: true
                    example: null
          headers:
            link:
              schema:
                type: string
              required: false
```

With a response without `link` header, it will fail with:

```
{
  "detail": "Keys in header don't match response specification. Difference: link",
  "status": 500,
  "title": "Response headers do not conform to specification",
  "type": "about:blank"
}
```

### Additional info:

Output of the commands:

- `python --version`: 3.8.2
- `pip show connexion | grep "^Version\:"`: 2.7.0

**Comment by cchadha2** [comment]
That makes sense. Looks like that method needs updating anyway to directly use set operations between dict views instead of creating sets (now that python 2.7 support has been dropped).
