### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by Jiehong** [zalando/connexion#1262]
Hi everyone,

This projects seems to be idle, and no PR have been merged since April 25th.

What is the official status of this project?

Is Zalando still considering working on it?

Any visibility would be appreciated ;)

**Comment by cchadha2** [comment]
I’d also like to know as I was looking to help fix some open issues. @hjacobs any idea if you guys will be reviewing PRs again soon?

**Comment by scoulomb** [comment]
Same on my side, this project is great. Hope it will not die.  Maybe we could extend maintainer role to non Zalando employees?

**Comment by ag1989** [comment]
Same on our side, we already wrote a few small applications based on connexion and love it!

**Comment by plattenschieber** [comment]
Push from my side. Is there anything happening? Will this project be opened to community driven contributions? There are a bunch of open PRs.

**Comment by ag1989** [comment]
Push from my side too. We used connexion in a series of applications, which are not of significant relevance, however, stepping back to plain flask is something I would like to avoid.

**Comment by Jiehong** [comment]
I suppose connexion is really no longer supported by Zalando (no commit, no news).

If someone goes for an official supported fork, let us know in this issue.

**Comment by ddurham2** [comment]
@hjacobs, would you mind giving an update on the status of connexion?  All projects can wax and wane, other priorities show up, but is it going to continue to be supported at this repo at any level?  If not, it would be a help to the community to know that now rather than continue wondering.

Thank You

**Comment by hjacobs** [comment]
Sorry for the long radio silence, update on maintenance status and moving forward is in https://github.com/zalando/connexion/issues/1365#issuecomment-867644177
