### ISSUE TITLE
Update doc about routing for openapi operations

### ISSUE THREAD

**Issue by xiaoyu-wu** [zalando/connexion#1266]
The document about routing says "you can include `x-swagger-router-controller` in your operation definition, making operationId relative"
while, in fact, to add OpenAPI operations, it is `x-openapi-router-controller` that should be added to operation definition.

**Comment by Abdullahabid3691** [comment]
This took me long to figure this issue out ... @xiaoyu-wu you are right!

**Comment by RobbeSneyders** [comment]
Fixed in #1353
