### ISSUE TITLE
How to use asyncpg & aiohttp with connexion?

### ISSUE THREAD

**Issue by CMCDragonkai** [zalando/connexion#1277]
I'm trying to figure out how to use asyncpg and aiohttp with connexion.

I can create an aiohttp server. However it doesn't seem obvious how I'm supposed to pass the asyncpg pool into the handlers.

The asyncpg pool construction is asynchronous requiring an `await asyncpg.create_pool()`.

But where should be called? It cannot be done at top level of a Python module. It must be wrapped inside a function.

```
import connexion
import asyncpg

async handler_get():
    # how to use db pool?
    pass

async def main():
    db = await asyncpg.create_pool()
    app = connexion.AioHttpApp(__name__, only_one_api=True)
    app.add_api('./openapi.yaml')
    app.run(host=host, port=port)

# how to run the main()?
```

How do I get access to the internal event loop and ensure that the db pool is accessible to my async handlers?

The handlers should not be creating the pool. The pool should be started already before the handlers are even handling anything.

**Comment by CMCDragonkai** [comment]
A more general question is how do I get into the async/await stack that connexion seems to be hiding, so I can start/create asynchronous resources that can be shared among all of my async handlers when using aiohttp as the server backend of connexion.

**Comment by mvalkon** [comment]
@CMCDragonkai I think your questions is not so much a question for Connexion (although some parts do apply) than it is to how aiohttp makes shared resources available to connection handlers and initialises them when asynchronous calls are needed. I might not be able to fully answer your question but perhaps I can give some direction.

For initialising async resources, you can use the [on_startup](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.Application.on_startup) hooks to register function calls that will be executed at application startup.

[Aiohttp documentation](https://docs.aiohttp.org/en/v3.0.1/faq.html#where-to-put-my-database-connection-so-handlers-can-access-it) suggest that database objects should be stored in the application instance. It can be treated as a dictionary, so you may simply create a key and store the initialised object as a value.

Here's an example, which I have not tested but should work. You might want to read the aiohttp documentation for how to run functions at application shut down to gracefully close connections.

```python
async def initialise_db(app):
     app['db'] = await asyncpg.create_pool()

async def handler_get(request):
   db = request.app['db']
   # do db things here

def create_app():
    connexion_wrapper = connexion.AioHttpApp(__name__, only_one_api=True)
    connexion_wrapper.add_api('./openapi.yaml')
    connexion_wrapper.app.on_startup.append(initialise_db)
    return app

if __name__ == '__main__':
   app = create_app()
   app.run()
```
