### ISSUE TITLE
Possible to not implement an endpoint?

### ISSUE THREAD

**Issue by mikkoi** [zalando/connexion#1282]
### Description

Sometimes you might need to document an endpoint but either leave it unimplemented or implement it outside Connexion, e.g. in Apache. Could there be an x-swagger-? definition which makes Connexion skip an endpoint?

**Comment by RobbeSneyders** [comment]
When adding an API, you can set the `resolver_error` to configure Connexion to provide an error response for paths that are not yet implemented: [docs](https://connexion.readthedocs.io/en/latest/routing.html?highlight=resolver#endpoint-routing-to-your-python-views).
