### ISSUE TITLE
Optional request bodies throw validation error

### ISSUE THREAD

**Issue by ccann** [zalando/connexion#1288]
### Description
I have a route where I've specified an optional request body and when I hit that route without providing one I get: 

```json
{
  "detail": "None is not of type 'object'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

### Expected behaviour
A `requestBody` with `required: false` should be optional. 

### Actual behaviour
A `requestBody` with `required: false` is still required. 

### Steps to reproduce
I have a specification like so:
```yaml
  /foobar/{id}/complete:
    post:
      operationId: app.complete_foobar
      summary: "yada yada"
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                parts:
                  type: array
                  items:
                    type: object
                    properties:
                      etag:
                        type: string
                      part_number:
                        type: integer
                        format: int32
                    required: ['etag', 'part_number']
              required: ['parts']
        required: false. # <-- this is the specification
# ...
```

I hit that route with the swagger UI and an empty request body.

### Additional info:
The swagger specification for `requestBody`:

```required | boolean | Determines if the request body is required in the request. Defaults to false.```

https://swagger.io/specification/

Output of the commands:

- `python --version` 
Python 3.8.5
- `pip show connexion | grep "^Version\:"`
2.7.0

**Comment by ccann** [comment]
It appears to be the case that adding `x-nullable: true` like so has the desired effect:

```yaml
     requestBody:
        content:
          application/json:
            schema:
              type: object
              x-nullable: true
```

**Comment by 20Aditya** [comment]
Hi, I tried this workaround but I'm getting a different error:
`The browser (or proxy) sent a request that this server could not understand.`

I have described it in detail here, can you have a look?
https://github.com/spec-first/connexion/issues/1317#issuecomment-1058864811
