### ISSUE TITLE
Serving swagger 2.0 and openapi 3.0 at the same time

### ISSUE THREAD

**Issue by Jane85** [zalando/connexion#1289]
### Description
We use  have an application which needs to support two versions of APIs at the same time. Version 1 uses swagger 2.0 and version 2 uses openapi 3.0. When both versions are enabled, the swagger UI of version 1 API can be accessed successfully but the version 2 API cannot be accessed. The applications gives the following error

```
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

But when only the version 2 API is enabled, the swagger UI can be accessed successfully.

### Expected behaviour

When the application serve both API versions, the swagger UI of both should be accessible

### Actual behaviour

When the application serve both API versions, only the swagger UI of the API version which uses swagger 2.0 can be accessed.

### Additional info:

Output of the commands:

- `python --version`: 3.6.5
- `pip show connexion | grep "^Version\:"`: 2.6

**Comment by pchanial** [comment]
I've encountered this issue as well. It looks like the workable version is the one that is first imported through add_api.
For reference, when the swagger spec is imported first, the openapi spec ui will be displayed through swagger-ui as
```
swaggerswagger
http://example.com/api
Explore
```
and when the openapi spec is imported first, there is a blank page for the swagger spec ui.

Simple way to reproduce the problem:
app.py
```
import connexion

app = connexion.App(__name__, specification_dir='./')
app.add_api('swagger.yaml')
app.add_api('openapi.yaml')
app.run(host='127.0.0.1', port=8080)
```
swagger.py
```
def test_swagger():
    return 'SWAGGER', 200
```
openapi.py
```
def test_openapi():
    return 'OPENAPI', 200
```
swagger.yaml
```
swagger: "2.0"
info:
  title: "{{title}}"
  version: "1.0"
basePath: /swagger/v1
paths:
  /test:
    get:
      description: Test with swagger
      summary: Test using swagger specification.
      operationId: swagger.test_swagger
      produces:
        - text/plain
      responses:
        '200':
          description: Success response
          schema:
            type: object
```
openapi.yaml
```
openapi: 3.0.0
info:
  title: '{{title}}'
  version: '1.0'
paths:
  '/test':
    get:
      summary: Test using OpenAPI specification.
      description: Test with OpenAPI
      operationId: openapi.test_openapi
      responses:
        '200':
          description: Success response
          content:
            text/plain:
              schema:
                type: string
servers:
  - url: /openapi/v1
```

**Comment by IgorWang** [comment]
same issue!! any one has suggesstion???

**Comment by RobbeSneyders** [comment]
This one took me a while to figure out.

We are looking for the static files of the UI in the correct place:
https://github.com/zalando/connexion/blob/803cf638785223b3a9321c4ad5bbe371a61e38b6/connexion/apis/flask_api.py#L301-L310

But apparently Flask has an unexpected way of determining which template to serve when using `render_template` ([docs](https://flask.palletsprojects.com/en/2.0.x/blueprints/#templates)) (pallets/flask#1361):

> The template folder is added to the search path of templates but with a lower priority than the actual application’s template folder. That way you can easily override templates that a blueprint provides in the actual application. **This also means that if you don’t want a blueprint template to be accidentally overridden, make sure that no other blueprint or actual application template has the same relative path**. When multiple blueprints provide the same relative template path the first blueprint registered takes precedence over the others.

So when we render `index.j2`, the index file of the blueprint / connexion API that was first registered is loaded each time.
https://github.com/zalando/connexion/blob/803cf638785223b3a9321c4ad5bbe371a61e38b6/connexion/apis/flask_api.py#L299
This index file contains the path to the other files that need to be fetched, which is different between Swagger 2 and OpenAPI 3. So we're looking for the wrong files in the right place.

There doesn't seem to be an easy way to change the template lookup behavior of `render_template`, but we can use `render_template_string` instead to explicitly load the correct template ourselves. I'm submitting a PR with this fix.

**Comment by RobbeSneyders** [comment]
Thanks for the report @Jane85 and minimal working example @pchanial!
