### ISSUE TITLE
No similar mechanism as in Flask to initialize before_first_request for each thread

### ISSUE THREAD

**Issue by dwgui1974** [zalando/connexion#1301]
### Description
When Flask works with Gunicorn, you can initialize some setting and load deep learning models at before_first_request section for each thread so each thread can work independently. I did not find a way for connexion. Can you tell me how to do that?

### Expected behaviour
Initialize some setting and load deep learning models at before_first_request section for each thread so each thread can work independently.

### Actual behaviour
In Flask, you can initialize before first request like this:
@app.before_first_request
def before_first_request_func():
    init()

But I am not aware of such mechanism with Connexion.

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Hi @dwgui1974, you can access the flask app via `app.app`:

```Python
app = connexion.FlaskApp(__name__)
app.add_api('swagger.yaml')

flask_app = app.app

@flask_app.before_first_request
def before_first_request_func():
    init()
```
