### ISSUE TITLE
CustomRequestBodyValidator - return problem() does not work, we have to raise an exception - BadRequestProblem.

### ISSUE THREAD

**Issue by bhargaviurs** [zalando/connexion#1305]
This is what worked for me finally.. **return problem()** does not work for some reason. we have to raise an exception. 

class CustomRequestBodyValidator(RequestBodyValidator):

    def validate_schema(self, data, url):
        if self.is_null_value_valid and is_null(data):
            return None
        try:
            self.validator.validate(data)
        except ValidationError as exception:
            LOG.error(
                "{url} validation error: {error}".format(url=url, error=exception),
                extra={"validator": "body"},
            )
            # return problem(400, "Bad Request test", str(exception))        DOES NOT WORK
            raise BadRequestProblem("Bad Request test", str(exception))    WORKS

        return None

app = connexion.App(__name__)
app.add_api(
    "app.yaml",
    strict_validation=True,
    validate_responses=True,
    validator_map={"body": CustomRequestBodyValidator},
)

_Originally posted by @bhargaviurs in https://github.com/zalando/connexion/issue_comments/706469183_

**Comment by RobbeSneyders** [comment]
Hi @bhargaviurs I don't see why this is an issue. Feel free to reopen with more information if you think it is.
