### ISSUE TITLE
Having tag names with | (pipe) symbols in them causes connexion to create modules with names which are unimportable

### ISSUE THREAD

**Issue by tzickel** [zalando/connexion#1308]
### Description

Having tag names with | (pipe) symbols in them causes connexion to create modules with names which are unimportable.

The idea for using | is suggested as an option for hierarchical grouping of tags:
https://github.com/swagger-api/swagger-ui/issues/5969

### Expected behaviour

Everything should run properly.

### Actual behaviour

Trying to run the server gets:
ModuleNotFoundError: No module named 'openapi_server.controllers.a|b' (see the | there?)

### Steps to reproduce

create an spec file with | in the tag names.

### Additional info:

Python 3.9 with connexion 2.7.0

**Comment by Ruwann** [comment]
Hi @tzickel , could you provide an example with the spec you are using? I'm not able to reproduce the error: modifying the helloworld example to use tags with pipe symbols runs fine for me.

**Comment by tzickel** [comment]
Hmm... Looking back, I guess the issue was then a bug in openapi-generator for a python server for tag names that had | in them..
