### ISSUE TITLE
Pass formData parameters as keyword arguments to handler function

### ISSUE THREAD

**Issue by jvgutierrez** [zalando/connexion#132]
Hi

formData parameters (flask.request.form) should be mapped as keyword parameters like query or body parameters.

Is this feature on the roadmap?

**Comment by hjacobs** [comment]
@jvgutierrez we don't have any "roadmap" :smirk: 

Could you reference the OpenAPI Spec regarding this feature?

**Comment by jvgutierrez** [comment]
Sure, it's documented here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterIn

example from OpenAPI 2.0 spec:
```
tags:
- pet
summary: Updates a pet in the store with form data
description: ""
operationId: updatePetWithForm
consumes:
- application/x-www-form-urlencoded
produces:
- application/json
- application/xml
parameters:
- name: petId
  in: path
  description: ID of pet that needs to be updated
  required: true
  type: string
- name: name
  in: formData
  description: Updated name of the pet
  required: false
  type: string
- name: status
  in: formData
  description: Updated status of the pet
  required: false
  type: string
responses:
  '200':
    description: Pet updated.
  '405':
    description: Invalid input
security:
- petstore_auth:
  - write:pets
  - read:pets
```

**Comment by hjacobs** [comment]
:+1: I personally don't "need" this, but happy to see contributions :smirk:

**Comment by hjacobs** [comment]
Released in https://github.com/zalando/connexion/releases/tag/1.0.50
