### ISSUE TITLE
Helloworld 404 error

### ISSUE THREAD

**Issue by abruscino-eng** [zalando/connexion#1321]
### Description
Hello,
I'm trying to run [helloworld example](https://github.com/zalando/connexion/tree/master/examples/openapi3/helloworld) and when I try to access the [link](http://localhost:9090/v1.0/ui/) I received 404 error:
`{
"detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
"status": 404,
"title": "Not Found",
"type": "about:blank"
}` 

### Steps to reproduce
1- Clone [repo](https://github.com/zalando/connexion)
2- Go to folter connexion/examples/openapi3/helloworld/
3- Create venv `python3 -m venv env`
4- Activate venv 
5- Run command `pip install connexion`
6- Follow instructions on file [README.rst](https://github.com/zalando/connexion/blob/master/examples/openapi3/helloworld/README.rst)

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.9
- `pip show connexion | grep "^Version\:"`
Version: 2.7.0

**Comment by Ruwann** [comment]
I believe you need an extra install to access the ui: `pip install connexion[swagger-ui]`

When following the steps you listed, I get the following message:

> The swagger_ui directory could not be found.
>     Please install connexion with extra install: pip install connexion[swagger-ui]
>     or provide the path to your local installation by passing swagger_path=\<your path\>

**Comment by abruscino-eng** [comment]
Tks for the answer. I didn't pay attention to this message.
