### ISSUE TITLE
Validation mechanism seems to incorrectly hoist `additionalProps` flag to consuming schema

### ISSUE THREAD

**Issue by prometheas** [zalando/connexion#1322]
### Description

Hey everyone. I believe I've found a small but troublesome error in the application of the `additionalProps` flag, when validating a schema for an object A that references object B, which disallows additional properties.

For example, given a schema such as the following:

```yaml
components:
  schemas:
    A:
      allOf:
        - $ref: "#/components/schemas/B"
        - type: object
          properties:
            createdAt: { type: string, format: date-time }
    B:
      type: object
      properties:
        firstName: { type: string }
        lastName: { type: string }
      additionalProps: false
```

I would expect that an object `{ firstName: 'foo', lastName: 'bar', otherProp: 'baz' }` should fail, when validated against `B`, on account of its extra property, `foo`. I would also expect, however, that an object `{ firstName: 'foo', lastName: 'bar', createdAt: '2020-01-01T00:00:00.000Z', otherProp: 'baz' }` validated against schema `A` should NOT fail for the presence of the `otherProp` property.

The fact that it does suggests that the validation mechanism is incorrectly "hoisting" the `additionalProps: false` flag up to the validation efforts applied against `#/components/schema/A`.

### Expected behaviour

I would expect that `otherProp`'s presence when validating an object against `#/components/schema/A` NOT results in a validation failure.

### Actual behaviour

The object fails validation.

### Steps to reproduce

Sadly, I only see this behavior from a web service, though I am not myself someone proficient in its code base.

### Additional info:

Output of the commands:

Python: 3.8.0
Connexion: 2.6.0

**Comment by Ruwann** [comment]
Why should the additionalProperties not be respected? The object you specify is not valid against schema B, so it fails against schema A as well, because A validates against schema B, and the other schema specified there.

> To be valid against allOf, the data provided by the client must be valid against all of the given subschemas.

https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by prometheas** [comment]
I may be overlooking something here, but using an `allOf`, by definition, creates a superset of two (or more) other schema definitions, which will compound the properties of all referenced schema definitions.

Why else use an `allOf` except to achieve a compound schema, composed of all the properties of its referenced components schemas?

**Comment by Ruwann** [comment]
How does it create a superset, I am not aware of this definition and can't seem to find it in the spec? As far as I can tell from the spec, nothing gets 'created'.

> `allOf` takes an array of object definitions that are validated _independently_ but together compose a single object.

See also: https://json-schema.org/understanding-json-schema/reference/combining.html#allof

If your example is invalid against schema B, why would it be valid against schema A?

In any case, this seems more like a jsonschema issue than a connexion issue.

**Comment by prometheas** [comment]
Yes, having reviewed the spec material you've cited, I am forced to agree with your position. I appreciate your taking the time to review the concern and engage in the conversation, and I offer my apologies, @Ruwann, for my not having first researched the specification myself before posting this issue.

Stay safe and healthy.
