### ISSUE TITLE
Help: sample code of connexion download file

### ISSUE THREAD

**Issue by xiaochaowu** [zalando/connexion#1325]
### Description

Dear All, 
I am programing a swagger server base on connexion which will download file. But I cannot find any resource about this topic. Can somebody give me a sample code or any help?

Best regards!

**Comment by RobbeSneyders** [comment]
Hi @xiaochaowu 
The OpenAPI documentation ([Swagger 2](https://swagger.io/docs/specification/2-0/describing-responses/#response-that-returns-a-file), [OpenAPI 3](https://swagger.io/docs/specification/describing-responses/#response-that-returns-a-file)) and framework documentation (Flask, aiohttp) should provide all information that is needed. 
Closing for now, but feel free to reopen if something connexion specific is holding you back.
