### ISSUE TITLE
Connexion does not convert query parameters with hyphens to underscores in python code

### ISSUE THREAD

**Issue by Liam-Deacon** [zalando/connexion#1329]
### Description

Hi, I have a set of query parameters like the following:

```yaml
openapi: '3.0.3'
# ...
components:
    parameters:
        CreatedByQuery:
            name: created-by
            in: query
            schema:
                type: string
```

I expected that when using this query parameter on an endpoint, that the call to the python controller function would have a `created_by="someone"` keyword argument as a snake_case representation of the kebab-case query (or even `createdBy="someone"` if we are in Javascript lowerCamelCase land) , but instead I simply get `createdby="someone"` without any spaces, which was unexpected! 

Is this intended behaviour and is there any way to specify how the query names get converted to python kwarg names?

### Additional info:

Output of the commands:

- `python --version` -> `Python 3.8.5`
- `pip show connexion | grep "^Version\:"` -> `Version: 2.7.0`

**Comment by RobbeSneyders** [comment]
Hi @Liam-Deacon,
As [mentioned in the documentation](https://connexion.readthedocs.io/en/latest/routing.html#parameter-name-sanitation), all characters not allowed in Python are removed during parameter name sanitation. 

There is however the undocumented [`pythonic_params`](https://github.com/zalando/connexion/blob/df7ec12f4548438636ce5a5a6704fccce2dbc2dc/connexion/operations/abstract.py#L72) argument, which allows to change the behavior to what you're looking for. We should add this to the documentation.

We also might want to make this the default behavior in the next major release.
