### ISSUE TITLE
Option to change endpoints modules locations

### ISSUE THREAD

**Issue by Ragnar-Oock** [zalando/connexion#1330]
### Description
I have a decent amount of endpoints and I'd like to have them in a separated module rather than at the root of the project, unfortunately, I didn't find any solution to change the location where connexion looks for the flask views. I could have changed the `operationId` key in the swagger, but it wasn't suitable for the already existing front end app.
To work around this issue I created a wrapper around the `RestyResolver` and changed the behavior of the `resolve_function_from_operation_id` method to append the default module name to the importation path (see code below).

```python
from connexion.resolver import RestyResolver


class CustomRestyResolver(RestyResolver):
    def resolve_function_from_operation_id(self, operation_id):
        operation_id = self.default_module_name + "." + operation_id
        return super().resolve_function_from_operation_id(operation_id)
```

### Expected behavior
It should be possible to provide a root path for endpoints modules. Something like `RestyResolver(root_path='path to endpoint views')`
I expected `default_module_name` to serve as a root path for endpoints modules import.

### Actual behavior
No option is available to change the default root path.

### Additional info:

Output of the commands:

- `python --version`: 3.6.0
- `pip show connexion | grep "^Version\:"`: 2.7.0

**Comment by RobbeSneyders** [comment]
Hi @Ragnar-Oock, this is exactly what the `default_module_name` parameter does. Please provide a minimal working example if this doesn't work for you.

**Comment by Ruwann** [comment]
The `default_module_name` is only used when the `operationId` is not specified; when `operationId` is specified, it overrides the `RestyResolver` behaviour and the basic Resolver behaviour is used.

I'm not entirely sure this is something that connexion should provide, as I think it makes sense to just subclass the `Resolver` as you did.
