### ISSUE TITLE
missing documentation example for Oauth2 x-tokenInfoFunc and/or TOKENINFO_FUNC

### ISSUE THREAD

**Issue by Ragnar-Oock** [zalando/connexion#1331]
The example provided in the [minimal OAuth example application](https://github.com/zalando/connexion/tree/master/examples/swagger2/oauth2) demonstrates how to use the deprecated `x-tokenInfoUrl` and `TOKENINFO_URL`. A new example using the preferred method `x-tokenInfoFunc` or `TOKENINFO_FUNC` should replace it.

Additionally, adding the detailed signature (parameters and return value) of the expected function would make using this functionality easier for newcomers.

**Comment by RobbeSneyders** [comment]
An example of `x-tokenInfoFunc` is available [here](https://github.com/zalando/connexion/tree/master/examples/swagger2/oauth2_local_tokeninfo).
