### ISSUE TITLE
Doesn't parse the request body method get (only at "PATCH", "POST", "PUT") - unclear error message

### ISSUE THREAD

**Issue by 99ACA** [zalando/connexion#1333]
### Description
Create rest-api with swagger version 2.0 endpoint get method with body parameters.
Get error : [endpoint-name] missing 1 required positional argument: 'param name'

### Expected behaviour
Write error/warning options
- While parsing the swagger that detect get message with incorrect param (body)
- Write warning that the body parameters will be drop. 

[[Get method should not get body param](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET)]

### Actual behaviour
Remove the parameter write the following error message:
[endpoint-function-name] missing 1 required positional argument: 'param name'

### Steps to reproduce
Create get methods with param in the body

### Additional info:
The validation done in the code at file connexion/operations/abstract.py
Line: line 270  -> **if self.method.upper() in ["PATCH", "POST", "PUT"]:** only bind args to those methods types.

Output of the commands:

- `python --version`
Python 3.8.5
- `pip show connexion | grep "^Version\:"`
Version: 2.6.0

**Comment by RobbeSneyders** [comment]
Hi @99ACA,
The `missing 1 required positional argument` error is thrown when your view function has a required parameter which is not provided by the request.
