### ISSUE TITLE
Maintenance status of this project?

### ISSUE THREAD

**Issue by languitar** [zalando/connexion#1334]
I am seeing a lot of issues pile up here and also the latest commit appeared half a year ago. Can someone clarify what the maintenance status of this project is? Does connexion still play a role for Zalando and will continue to be maintained?

**Comment by ddurham2** [comment]
I too am concerned.   Anyone aware of a more active fork?

**Comment by aramcap** [comment]
I'm interested too.

**Comment by gavinmh** [comment]
I am also interested.

**Comment by NorthDecoder** [comment]
Perhaps they have switched to  [openapi-generator](https://github.com/OpenAPITools/openapi-generator).  See [companies / projects-using-openapi-generator](https://github.com/OpenAPITools/openapi-generator#4---companiesprojects-using-openapi-generator) and then search for Zalando.

**Comment by ddurham2** [comment]
I've never cared for the openapi-generator (and others) because it generates server stubs, but if you ever modify your spec and need to generate the server code again, you basically have to start over.. at least that seems to be the case.  Correct me if I'm wrong.    It's fine if you're openapi spec is never going to change, but during developement, it's not helpful.

**Comment by languitar** [comment]
I any case, two openapi generator modules for python result in connexion as the used framework.

**Comment by M-Reimer** [comment]
Maybe this is a possible alternative: https://github.com/p1c2u/openapi-core

**Comment by sisp** [comment]
While gathering alternatives to Connexion: [`falcon-oas`](https://github.com/grktsh/falcon-oas) (which uses [`python-oas`](https://github.com/grktsh/python-oas))

`falcon-oas` is based on [Falcon](https://github.com/falconry/falcon/), so this is not a Flask-based solution. But IMHO `falcon-oas` is well-written and well-tested. It's not feature-complete though to be honest. I've used it quite a bit and it has worked well for me so far.

**Comment by BorjaEst** [comment]
> Perhaps they have switched to [openapi-generator](https://github.com/OpenAPITools/openapi-generator). See [companies / projects-using-openapi-generator](https://github.com/OpenAPITools/openapi-generator#4---companiesprojects-using-openapi-generator) and then search for Zalando.

The reason why "Zalando" appears there is because they are contributors. When you generate a Server Stub for python-flask you can see connexion is used on th requirements.txt:

```txt
connexion[swagger-ui] >= 2.6.0; python_version>="3.6"
# 2.3 is the last version that supports python 3.4-3.5
connexion[swagger-ui] <= 2.3.0; python_version=="3.5" or python_version=="3.4"
# connexion requires werkzeug but connexion < 2.4.0 does not install werkzeug
# we must peg werkzeug versions below to fix connexion
# https://github.com/zalando/connexion/pull/1044
werkzeug == 0.16.1; python_version=="3.5" or python_version=="3.4"
swagger-ui-bundle >= 0.0.2
python_dateutil >= 2.6.0
setuptools >= 21.0.0
```

**Comment by hjacobs** [comment]
The project maintenance status and how to move forward is now clarified in https://github.com/zalando/connexion/issues/1365#issuecomment-867644177
