### ISSUE TITLE
How can I remove explore toolbar from the render

### ISSUE THREAD

**Issue by smolendawid** [zalando/connexion#1337]
I am wondering whether it's possible to remove the explore toolbar from the documentation using some **code**?

**Comment by RobbeSneyders** [comment]
Connexion exposes options to change the generated UI.

You can either pass a `swagger_ui_config` with [parameters to change the default UI](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/), or you can pass `openapi_console_ui_from_dir` to provide custom files for the UI.

You can find an example on how to use it in our tests:
https://github.com/zalando/connexion/blob/df7ec12f4548438636ce5a5a6704fccce2dbc2dc/tests/api/test_bootstrap.py#L89-L93
