### ISSUE TITLE
How to handle multiple simultaneous versions with header-based/media-type versioning strategy?

### ISSUE THREAD

**Issue by samkots** [zalando/connexion#1346]
### Description
I'm aware that versioning should be [avoided](https://opensource.zalando.com/restful-api-guidelines/#113), but when you have to, [media-type based versioning strategy is recommended](https://opensource.zalando.com/restful-api-guidelines/#114).

I'm assuming that I will have one spec file per version. So, to maintain two versions, I will have `petstore-v1.yaml` and `petstore-v2.yaml` files. Please correct me if I'm wrong.
As I'll be using header based/media-type based versioning approach, the URL(base path) will stay the same.
In that case, how to call `app.add_api()` for multiple `yaml` files that contain the same URL but different versions?

### Actual behaviour

When I try the following:

```python
app = connexion.App(__name__, specification_dir='./openapi/')
app.add_api('petstore-v1.yaml')
app.add_api('petstore-v2.yaml')  # With same URL (or base path): "/petstore/api"
```

I get following error:
```
AssertionError: A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x7fe114da66d0> and <flask.blueprints.Blueprint object at 0x7fe114da6710>. Both share the same name "/petstore/api". Blueprints that are created on the fly need unique names.
/root
```

### Additional info:

gunicorn is used

Output of the commands:

- `python --version` -> Python 3.7.4
- `pip show connexion | grep "^Version\:"` -> Version: 2.6.0

**Comment by RobbeSneyders** [comment]
Hi @samkots. I would recommend to define both versions in the same API spec. You can define multiple media types for an endpoint ([swagger 2](https://swagger.io/docs/specification/2-0/mime-types/), [openapi 3](https://swagger.io/docs/specification/media-types/)).

**Comment by frejonb** [comment]
@RobbeSneyders Is it documented how to handle each type in the controller? Is it just reading the `Accept` or `Content-Type` headers? To return the different types, is it enough do do like
```
if request.headers['requester-uuid'] == '...':
  return Response_1, 200
else:
  return Response_2, 200
```

**Comment by RobbeSneyders** [comment]
Yes, indeed!
Validation of multiple response types is not perfectly supported though (#593), but any work an that would be appreciated.

**Comment by frejonb** [comment]
Indeed. It seems that sticking to the same `mimetype` for all responses works fine (with the toy example I tried). Though my previous comment doesn't quite work. Currently we need to return a `ConnexionResponse` in order to set the `Content-Type`. The reason seems to be that the response created from the `Tuple` sets the `content_type` argument, and this is not allowed by https://github.com/aio-libs/aiohttp/blob/5b23426dea3a2b8a62035355e8af5ff8f16bd735/aiohttp/web_response.py#L541

**Comment by samkots** [comment]
Thanks @RobbeSneyders! That solves the issue for request and response payloads.
Additionally, if the query parameters are changing between the versions, how will we handle that?

**Comment by frejonb** [comment]
@samkots would that be considered changing the URI semantics? If so the guideline is against that. I would create a new resource variant handled in a different endpoint

**Comment by RobbeSneyders** [comment]
@samkots from a technical perspective you should be able to do this by defining the parameters both in your spec and view function as optional. There's no clear way to distinguish the old and new query parameters in the spec though (except for maybe marking the old ones as deprecated), so you might want to define a new endpoint as @frejonb mentioned instead.

**Comment by samkots** [comment]
Thanks @RobbeSneyders :)
