### ISSUE TITLE
Unexpected value passed to handler when calling endpoint and not specifying the value for an array query parameter

### ISSUE THREAD

**Issue by mikhailantoshkin** [zalando/connexion#1357]
### Description
Calling an endpoint and not specifying the value for an array query parameter results in handler receiving `['']`

### Expected behaviour
I'm not quite sure how it's supposed to behave. On one hand, it is logical that an empty scv string should be represented with an empty list. On the other hand, it will be somewhat ambiguous. But I'm sure it's not supposed to be `['']`

### Actual behaviour
Handler is receiving `['']`

### Steps to reproduce
I have created a basic [example](https://github.com/mikhailantoshkin/connexion-emtpy-csv)
Use `swagger.yaml`  like this
```
swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /v1.0

paths:
  /foo:
    get:
      operationId: empty.foo_get
      parameters:
        - name: message
          description: Some message.
          in: query
          type: array
          items:
            type: string
      responses:
        200:
          description: greeting response
          schema:
            type: string
```
and run the basic server

```
import connexion


def foo_get(message):
    return 'You send the message: {}'.format(message), 200


if __name__ == '__main__':
    app = connexion.FlaskApp(__name__, port=9090, specification_dir='swagger/')
    app.add_api('swagger.yaml', arguments={'title': 'Example'})
    app.run()
```

when calling `http://localhost:9090/v1.0/foo?message=` response will be
```
"You send the message: ['']"
```

### Additional info:

Output of the commands:

- `python --version` Python 3.9.2
- `pip show connexion | grep "^Version\:"` Version: 2.7.0

**Comment by goDeni** [comment]
Got same problem !

**Comment by mikhailantoshkin** [comment]
Also if you specify format for the string inside the array like 
```
items:
 type: string
 format: uuid
```
It returns 400 with quite unhelpful `'' is not uuid` message, imo

**Comment by RobbeSneyders** [comment]
Not sure how this is unexpected.

Current behavior seems consistent to me:
`http://localhost:9090/v1.0/foo?message=bar` --> `['bar']`
`http://localhost:9090/v1.0/foo?message=` --> `['']`.
`http://localhost:9090/v1.0/foo?message=,bar` --> `['', 'bar']`

If you want to be able to pass an empty list to connexion, I would recommend to drop the `message=` from the query string, and make the `message` argument from your view function:
```
http://localhost:9090/v1.0/foo
```

```python
def foo_get(message=None):
    if message = None:
        message = []
    return 'You send the message: {}'.format(message), 200
```

It's also not connexion but Flask (actually Werkzeug) that parses the query string. So if you don't have access to the client to change which query string is sent, you can try to:
- monkeypatch Flask/Werkzeug behavior
- [Use a custom `URIParser` in connexion](https://connexion.readthedocs.io/en/latest/request.html#type-casting) to process the arguments before sending them to the view function.
