### ISSUE TITLE
Return `Deprecation` header when an operation is deprecated

### ISSUE THREAD

**Issue by ioggstream** [zalando/connexion#1361]
### Description

When I set `deprecated: true` on an operation I want to return `Deprecation: true` header

### Expected behaviour

add `Deprecation: true` header

### Actual behaviour

nothing

### Steps to reproduce

- set "deprecated: true" in OAS
- curl |& grep -i depre

**Comment by Ruwann** [comment]
Hi @ioggstream, I understand from looking at the OpenAPI spec, `deprecated: true` does not necessitate setting the `Deprecation` header:

deprecated | `boolean` | Declares this operation to be deprecated. Consumers SHOULD refrain from usage of the declared operation. Default value is `false`.
-- | -- | --

In addition, I understand this header is currently still in a draft phase (https://datatracker.ietf.org/doc/draft-ietf-httpapi-deprecation-header/, https://github.com/psf/requests/issues/5724)

If you want, you could always set this header yourself for the deprecated operations.
