### ISSUE TITLE
Use different Swagger UI openapi.json URL than API BASE_PATH? (reverse proxy)

### ISSUE THREAD

**Issue by marusinp** [zalando/connexion#1363]
### Description

* I have a simple flask app w/ openapi running in k8s cluster. 
* base path of the api set on the application level in Flask app is `/api`:
```python
...
app = connexion.App(__name__, specification_dir='./openapi/')
app.add_api('openapi.yaml', arguments={'title': 'Flask app'}, base_path='/api', pythonic_params=True)
...
```
* I use nginx as a reverse proxy on production. Flask app is exposed at endpoint `flask-app` in the reverse proxy config. So at endpoint `my-web-page.com/flask-app/api/ui`. I am able to see the Swagger UI. 

### Actual behaviour

* Swagger UI is unable to load the openapi.json definition - I'm getting 404 and 
```
Failed to load API definition.
Fetch error: Not Found /api/openapi.json
```
Swagger UI is sending a GET request to `my-web-page.com/api/openapi.json` (makes sense, since app is obviously unaware of the nginx reverse proxy running in a different k8s pod), but the API specification JSON is not there since Flask app is behind a reverse proxy.
* openapi.json is exposed at `my-web-page.com/flask-app/api/openapi.json` (notice the only difference between Swagger UI request and actual location being `/flask-app` set in nginx). 
* the API & Flask app are working as expected, only problem is the non-working Swagger UI. 

### Expected behaviour

Is there a way to change the Swagger UI request URL on the application level? because this issue could be solved by a simple nginx rewrite (e.g. `rewrite ^/(api/.*)$ /flask-app/$1 last;`). Unfortunately I can't handle this issue on a nginx level (various reasons). 

---

Output of the commands:

- `python --version`: Python 3.9
- `pip show connexion | grep "^Version\:"` 2.7.0

**Comment by RobbeSneyders** [comment]
Hi @marusinp, we have an [example](https://github.com/zalando/connexion/blob/main/examples/openapi3/reverseproxy/app.py) for a connexion API behind a reverse proxy. Does this help you?

**Comment by IgorWang** [comment]
any progress?
