### ISSUE TITLE
Switch default branch from "master" to "main"

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#1369]
As mentioned in #1365: we want to switch from `master` to `main`. 

We already had new PRs to `main`:  #1367 #1366 

@RobbeSneyders I think I can just change the default branch in GitHub to "main", so the repo view looks "correct" (e.g. updated CI/CD badge). Are you OK with switching the default branch?

![Screenshot_2021-06-25_20-02-27](https://user-images.githubusercontent.com/510328/123467014-4b78b000-d5f0-11eb-98f9-d970b785dbf2.png)

**Comment by RobbeSneyders** [comment]
Sounds good to me.

As far as I understand, Zappr is automatically applied to the default branch though, so we might want to update the Zappr config first.

**Comment by hjacobs** [comment]
Switched to `main`.
