### ISSUE TITLE
200 response as text/plain while 401 response application/json -- allowed?

### ISSUE THREAD

**Issue by ryran** [zalando/connexion#1399]
### Description

_200 response as text/plain while 401 response application/json -- allowed?_  
If so, then there seems to be a bug somewhere, because when I do this, the 200 response gets forced to json.

Background:

I've got a big api that's been working great for more than a year. The only part we need to talk about is the `/auth` path. If clients post an appropriate secret (and args) in a json request to `/auth`, they get a 200 response with a plain-text JWT. All good.

As I was improving the yaml definition, I decided to flesh out the error responses -- replacing the simple descriptions with actual json objects that match what the api provides to clients. I.e., the error responses in something like this:

```yaml
openapi: 3.0.3
paths:
  /auth:
    post:
      operationId: auth_generate_session_token
      x-openapi-router-controller: swagger_server.controllers.authorization_controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        "200":
          description: JWT token
          content:
            text/plain:
              schema:
                type: string
              x-content-type: text/plain
      responses:
        "401":
          description: Unauthorized -- Various possible reasons
```

... got changed to something like this:

```yaml
        "401":
          $ref: '#/components/responses/Unauthorized'
```

But of course, here's what that really ends up being:

```yaml
        "401":
          description: Unauthorized -- Various possible reasons
          content:
            application/json:
              schema:
                # $ref: '#/components/schemas/Error'
                type: object
                description: Default error
                properties:
                  status:
                    type: integer
                    minimum: 100
                    maximum: 599
                    description: HTTP Status Code
                    example: 404
                  title:
                    type: string
                    description: HTTP Error Title (usually 1-3 words)
                    example: Not Found
                  detail:
                    type: string
                    description: HTTP Error Detailed Description
                    example: App does not exist
```

### Expected behaviour vs Actual behavior

When I make this change to the openapi yaml definition (changing `401` response from simple description-only to a json object), the server's `200` responses go from plain-text to json, so instead of something like:

```
# (curl -v output)
< HTTP/2 200 
< server: nginx
< date: Mon, 12 Jul 2021 19:57:24 GMT
< content-type: text/plain; charset=utf-8
< content-length: 231
< 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.xxxTCXY
```

... I get something like:

```
# (curl -v output)
< HTTP/2 200 
< server: nginx
< date: Mon, 12 Jul 2021 19:51:21 GMT
< content-type: application/json
< content-length: 234
< 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.xxx707w"
```

I.e., the string is wrapped in quotes with a newline added.

### Steps to reproduce

If I comment out the whole `content` block from the `401` response, so that only the description is there, all is well. As soon as I enable json for one response code, it forces the `200` response to also be json. Is this expected? Is there anything I can do about it?

### Additional info:

```
$ python --version
Python 3.6.8

$ pip show connexion | grep "^Version\:"
Version: 2.8.0
```

PS: I posted [a thread about the openapi spec](https://community.smartbear.com/t5/Swagger-Open-Source-Tools/Does-openapi-3-allow-200-response-text-plain-amp-amp-401/m-p/219848/highlight/true#M1944) in the smartbear community forums. Not sure if anything will come of that.

**Comment by RobbeSneyders** [comment]
Thanks for the report @ryran.
Lack of support for multiple mime types on a single endpoint is a known limitation of connexion (#593) which we would like to solve in a next major version. I'll close this one to centralize the discussion in the existing issue.
