### ISSUE TITLE
Support Flask 2.0

### ISSUE THREAD

**Issue by shirblc** [zalando/connexion#1401]
### Description

So Flask 2.0 was released in May this year. Are there any plans on adding support for Flask 2 in Connexion? Connexion 2.7 worked perfectly fine with Flask 2 (we've been using this combination since late May), but for some reason 2.8 and 2.9 require the previous version of Flask, which means right now we can't update Connexion (as we're already using Flask 2). So I was wondering, why does connexion require an earlier version of Flask now? And are there plans for supporting Flask v2?

**Comment by RobbeSneyders** [comment]
Thanks for the report @shirblc. We recently added upper limits to the connexion dependencies. I submitted #1402 to check if Flask 2.0 breaks anything. I think we can bump the version if it doesn't, but connexion will probably not support all new functionality yet (like `async` routes for example).

**Comment by shirblc** [comment]
No worries about the new features, I'm sure it'll take some time anyway and we can wait. Thank you for the quick response and your great work maintaining this project!

**Comment by RobbeSneyders** [comment]
@hjacobs should we release a patch version for this?

**Comment by tomdesair** [comment]
@RobbeSneyders or @hjacobs, do you have a planned release date for the patch version that supports Flask 2.0?

Currently we're stuck on Connexion version 2.7.0 because our projects were already upgrade to Flask 2.0.1 before Connexion version 2.8.0 and 2.9.0 were released.

**Comment by bcurnow** [comment]
Any word on the patch release? I'm stuck because I need both Flask 2.x features as well as Connexion version 2.8 or higher.

**Comment by miguelgf** [comment]
@tomdesair @hjacobs @RobbeSneyders is there a date to release the 2.10 version? It will have this (and other issues) fixed, it would be really helpful

**Comment by nomad-software** [comment]
Is there any movement on a new release please? I can't update my dependencies because the latest release doesn't support Flask v2. We currently have to pin Connexion to v2.7.0.

**Comment by RobbeSneyders** [comment]
Hi all, sorry for the delay. We're depending on Zalando maintainers to release a new version to PyPi, but they've been unavailable for a while. I've released version 2.10.0 with this change and uploaded it to a new PyPi project for now. You can find the release [here](https://github.com/zalando/connexion/releases/tag/2.10.0).

**Comment by RobbeSneyders** [comment]
Release 2.10.0 which fixes this issue is now also available under the main [connexion](https://pypi.org/project/connexion) PyPi repository.
