### ISSUE TITLE
Array of objects in query parameter if urlencoded throws Bad request error

### ISSUE THREAD

**Issue by Kausshalk78** [zalando/connexion#1407]
### Description
As captured in issue https://github.com/zalando/connexion/issues/1316, the array of objects in query parameter is not supported by the current version. I tried few workarounds to get a way around this known issue and be able to pass array of objects to the python function.

Workaround 1: Tried to send an array of objects in the query parameter by url encoding it, but I get 400 Bad request error.
     URL encoded array of object to be sent: _[{"model":1,"number":2},{"model":4}]_
     Request: _getCarDetails?car=%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D'_

Workaround 2: Encode the array of object along with the query parameter (include key "car" in this case), I receive the array of object in the python function as dict with the passed array of object as key.
     URL encoded array of object along with query param to be sent: _car=[{"model":1,"number":2},{"model":4}]_
     Request: _/getCarDetails?car%3D%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D'_

### Expected behaviour
For the given query request :
```
getCarDetails?car=%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D
```
we would expect something like:
```
{cars: [{model: 1, number: 2}, {model: 1}]}
```
### Actual behaviour
```
Workaround 1:
Request sent: _getCarDetails?car=%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D'_

Response received:
{
  "detail": "'[{\"model\":1' is not of type 'object'\n\nFailed validating 'type' in schema['items']:\n    {'example': {'model': 1, 'number': 3},\n     'properties': {'model': {'maximum': 255,\n                              'minimum': 0,\n                              'type': 'integer'},\n                    'number': {'maximum': 255,\n                               'minimum': 0,\n                               'type': 'integer'}},\n     'required': ['model'],\n     'type': 'object',\n     'x-scope': ['']}\n\nOn instance[0]:\n    '[{\"model\":1'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

Workaround 2:
Request sent: _/getCarDetails?car%3D%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D'_
  
Log from python code:
[{'{"model":1,"number":2},{"model":4}': ''}]

Response:
127.0.0.1 - - [27/Jul/2021 04:48:18] "GET /getCarDetails?car%3D%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D HTTP/1.1" 204 -
```

### Steps to reproduce

**openapi spec used for testing this:**
```
openapi: 3.0.0
info:
  description: Returns car details
  title: Car Api
  version: 1.0.0
servers:
- url: /
paths:
  /getCarDetails:
    get:
      description: Returns car details
      operationId: get_car_details
      parameters:
      - description: SNSSAI query object
        in: query
        name: car
        schema:
          type: array
          items:
            $ref : '#/components/schemas/Car'
          default: []
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Car'
                type: array
          description: Car details
      summary: Returns car details
      x-openapi-router-controller: test.test
components:
  schemas:
    Car:
      example:
        model: 1
        number: 3
      properties:
        model:
          maximum: 255
          minimum: 0
          type: integer
        number:
          maximum: 255
          minimum: 0
          type: integer
      required:
      - model
      type: object
```
** Add following code  to receive the callback and print the "car" value**
```
test/test.py

def get_car_details(car):
    print(car)
```

And send request: _getCarDetails?car=%5B%7B%22model%22%3A1%2C%22number%22%3A2%7D%2C%7B%22model%22%3A4%7D%5D'_

### Additional info:

Output of the commands:

- `python --version`
```
Python 3.6.8
```
- `pip show connexion | grep "^Version\:"`
```
Version: 2.7.0
```

**Comment by RobbeSneyders** [comment]
Hi @Kausshalk78. I don't think straight url encoding of json is valid against the OpenAPI spec. Arrays and objects should be [serialized](https://swagger.io/docs/specification/serialization/) when passed as a query parameter.
