### ISSUE TITLE
Stop / reduce logging

### ISSUE THREAD

**Issue by MichalVasut** [zalando/connexion#1417]
Is there a way to stop or reduce logging?

You can either 
* limit all application logging to certain level (DEBUG, INFO, WARNING, ...) - that's to broad and not suitable
* limit concrete connexion loggers (ie. `connexion.operations.abstract`) to certein level - that's too narrow and connexion has lot of different loggers, which can be good for development of connexion itself, but is nuisance otherways
  * this way I've managed to create list of many `connexion.*` loggers and reduce logging to some amount (using `structlog.get_logger(logger_name).setLevel(logging.WARNING)`), but there are still some huge logs on DEBUG level that starts with
    * `Attaching x-scope to {` 
    * `Ref #/components/`
    * `Dereferencing {`

Is there some way to get rid of these logs? Or even better select logger via wildcard somehow? ie `connexion.*`?

Thanks for answer.

Michal

PS: Asked same question on StackOverflow: https://stackoverflow.com/questions/68897873/change-logging-level-for-all-connexion-loggers-at-once

**Comment by MichalVasut** [comment]
> Loggers can be organised in namespaces using dots. Have you tried doing:
> 
> ```
> logging.getLogger('connexion').setLevel(logging.WARNING)
> ```
> 
> > Logging is performed by calling methods on instances of the Logger class (hereafter called loggers). Each instance has a name, and they are conceptually arranged in a namespace hierarchy using dots (periods) as separators. For example, a logger named ‘scan’ is the parent of loggers ‘scan.text’, ‘scan.html’ and ‘scan.pdf’.
> 
> [Source](https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial)

**Comment by MichalVasut** [comment]
Just tried this approach

```python
logging.getLogger('connexion').setLevel(logging.WARNING)
```

and it doesn't work for me - placed after instantiation of Connexion (`connexion.App(__name__)`) also before (but this is nonsense)

**Comment by Ruwann** [comment]
Could you perhaps share a minimal reproducible example as the suggested approach does work for me when I try it.

**Comment by Ruwann** [comment]
Could it be that these are logs from `openapi-spec-validator` (which is a dependency of connexion)? The logs you describe can be found there:

https://github.com/p1c2u/openapi-spec-validator/blob/327a4c1cf6184bc17fc21b43a00978e34582b704/openapi_spec_validator/validators.py#L30

https://github.com/p1c2u/openapi-spec-validator/blob/5a326ed0e7b1e1db8cb692a82dc05d4af145fa42/openapi_spec_validator/decorators.py#L42-L44

Closing this for now, but feel free to reopen if there is something connexion can/should do.
