### ISSUE TITLE
Support for flask 2.x?

### ISSUE THREAD

**Issue by alanbchristie** [zalando/connexion#1420]
### Description
We have been using connexion `2.7.0` and flask `2.0.1` but recently encountered a `Extra formData parameter(s) annotations not in spec` fault. This appears to be fixed by #1374 as the fault does not occur when we use connexion `2.8.0` or `2.9.0`. Annoyingly there's a new dependency restriction with connexion 2.8 (and 2.9) that explicitly rejects the use of Flask 2.

Is there a plan to support flask 2?

### Expected behaviour
`pip install -r requirements.txt ` to pass when using connexion and flask 2.0.1

### Actual behaviour
Does not support flask 2, with this error: -
```
ERROR: Cannot install connexion==2.9.0 and flask==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested flask==2.0.1
    connexion 2.9.0 depends on flask<2 and >=1.0.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Steps to reproduce
Use these requirements: -

```
connexion[swagger-ui] == 2.9.0
flask == 2.0.1
```

### Additional info:

Output of the commands:

- `python --version`
```
Python 3.9.6
```
- `pip show connexion | grep "^Version\:"`
```
Version: 2.9.0
```

**Comment by Ruwann** [comment]
Hi @alanbchristie , this was also reported in #1401 and addressed in #1402 . 

@hjacobs  Can we release a new patch version for this?

**Comment by alanbchristie** [comment]
Thanks - moving back to flask `1.1.2` wasn't too difficult for us (even though we some some time moving from 1 to 2) but the ability to return to 2.0 would be handy (we can't use flask `1.1.3` or `1.1.4` because it does not support jinja2 v3, which we need!).

**Comment by Pragnya02** [comment]
Hi, is the fix ready for this? I am using Flask 2.0 for the new async feature but am unable to integrate with connexion because of the dependency conflict.

**Comment by Pragnya02** [comment]
Seems like installing connexion 2.7 is work around for now, it doesn't have the conflict with flask 2.x

**Comment by ykharko** [comment]
Hi guys, any ideas when support of flask 2.x might be released? As I can see at least dependency requirements updates are already in main branch.
Am I right it's going to be released with 2.10 version? 
In theory when new version is supposed to be released?

**Comment by nomad-software** [comment]
Is there any movement on a new release please? I can't update my dependencies because the latest release doesn't support Flask v2. We currently have to pin Connexion to v2.7.0.

**Comment by RobbeSneyders** [comment]
Hi all, sorry for the delay. We're depending on Zalando maintainers to release a new version to PyPi, but they've been unavailable for a while. I've released version 2.10.0 with this change and uploaded it to a new PyPi project for now. You can find the release [here](https://github.com/zalando/connexion/releases/tag/2.10.0).

**Comment by alanbchristie** [comment]
Worrying. If connexion development is effectively dead is it time to fork the repo and create a new "official" connexion2?

**Comment by idoy10** [comment]
We are also using connexion and we get 

> connexion 2.9.0 requires flask<2,>=1.0.4, but you have flask 2.0.2 which is incompatible.
> connexion 2.9.0 requires werkzeug<2.0,>=1.0, but you have werkzeug 2.0.2 which is incompatible.

Please update as soon as possible if there is going to be a change that we can update also other packages !!

**Comment by RobbeSneyders** [comment]
@alanbchristie We are currently only dependent for PyPi access. We released the `connexion2` package so people in this thread are unblocked. We are fully able to continue development on this repository.
@idoy10 if you are blocked by this, please install the `connexion2` package which contains the newest version.

**Comment by idoy10** [comment]
> `connexion2` package

Would you please provide a link to connexion2 and how to use it?
Thanks

**Comment by alanbchristie** [comment]
Initial build seems to work, so thanks for the new `2.10.0` release.

For others, the flask-related requirements for my tests (using Python 3.10.0) are: -

```
connexion2[swagger-ui] == 2.10.0
flask == 2.0.2
flask-migrate == 3.1.0
flask-sqlalchemy == 2.5.1
```

**Comment by RobbeSneyders** [comment]
Release 2.10.0 which fixes this issue is now also available under the main [connexion](https://pypi.org/project/connexion) PyPi repository.
