### ISSUE TITLE
How to use a subclass of Flask with connexion?

### ISSUE THREAD

**Issue by danieljacobs1** [zalando/connexion#1426]
### Description

Is there a way of using a subclass of `flask.Flask` with `connexion`?  We're [subclassing `flask.Flask`](https://flask.palletsprojects.com/en/2.0.x/patterns/subclassing/) because we need to slightly customise the behaviour.

From
https://github.com/zalando/connexion/blob/2dfd57dafbedff99c0a32616079f80c21b9de6d9/connexion/apps/flask_app.py#L21-L28
it looks like `flask.Flask` cannot be overridden - is that right? Or have we missed something?

Thanks.

**Comment by Ruwann** [comment]
Indeed, there isn't a clean way you are able to subclass `flask.Flask`. One option could be to subclass `connexion.FlaskApp` and overwrite the `create_app` method to call your flask subclass instead of `flask.Flask`.
