### ISSUE TITLE
JSON parameter not passed to endpoint handling function when using multipart/form-data request

### ISSUE THREAD

**Issue by AlbyST** [zalando/connexion#1428]
### Description
I need to send a binary file, along with a JSON payload, with a single POST request to the server. For this purpose I'm using a multipart/form-data request described using the openapi 3.0 specification that is then run through the Connexion framework.

Below is the OpenAPI specification I'm using:

```yaml
openapi: 3.0.0
info:
  title: TEST SERVICE API
  version: 0.1.0
servers:
  - url: https://127.0.0.1:8080/test-api
  - url: http://127.0.0.1:8080/test-api
paths:
  /test_multipart_endpoint:
    post:
      description: Multipart Request Test Endpoint.
      requestBody:
        content: 
          multipart/form-data: # Media Type
            schema:            # Request Payload
              type: object
              properties:      # Request Parts
                payload:       # Part1 (Object)
                  type: object
                  properties:
                    field1:
                      type: string
                    field2:
                      type: string
                  required:
                    - field1
                    - field2
                binary_file:  # Part 2 (Binary File)
                  type: string
                  format: binary
              required:
                - payload
                - binary_file
            encoding:
              payload:
                contentType: application/json
                style: form
                explode: true
              binary_file:
                contentType: application/octet-stream
      responses:
        '200':    # Status Code
          description: Success
```

Below is the handling function I'm using to handle the request:

```python
def test_multipart_endpoint_post(payload=None, binary_file=None):
    """test_multipart_endpoint_post

    Multipart Request Test Endpoint.

    :param payload: 
    :type payload: dict
    :param binary_file: 
    :type binary_file: strstr

    :rtype: None
    """
    print(payload)
    print(type(payload))
    
    return 'hello'
```

Below is the request I'm sending to the server:

```
curl -X POST "http://localhost:8080/test-api/test_multipart_endpoint" \
    -H  "accept: */*" \
    -H  "Content-Type: multipart/form-data" \
    -F "payload={\"field1\": \"string\", \"field2\": \"string\"};type=application/json" \
    -F "binary_file=@binary.bin;type=application/macbinary"
```

### Expected behaviour
The ```payload``` argument of the handling function is parsed from the raw request, validated using the format specified in the specification and then fed to the handling function.

### Actual behaviour
The ```payload``` argument of the handling function is parsed from the raw request, validated using the format specified in the specification, but is never fed to the handling function: it is always gets the null value, so ```None``` is always printed. The ```binary_file``` argument always gets the correct value instead.

Trying to trace the flow of the Connexion code handling the incoming request, I landed to this source:

```bash
$CONNEXION_BASE_DIR/connexion/operations/openapi.py
```

more specifically to the [_get_body_arguments](https://github.com/zalando/connexion/blob/main/connexion/operations/openapi.py#L274) function.
Following the code and by some trials, added this return statement after line 300:

```python
        res = {}
        if body_props or additional_props:
            res = self._get_typed_body_values(body_arg, body_props, additional_props)
            return res
```
After this change, the very same request is handled correctly and the ```payload``` argument of the handling function gets the expected value.

### Additional info:

Output of the commands:

- `python --version`: Python 3.9.1
- `pip show connexion | grep "^Version\:"`: Version: 2.9.0

Could the above fix solve the issue?

Thank you

**Comment by RobbeSneyders** [comment]
Hi @AlbyST 

The request body here is not
```
{
  "field1": "string",
  "field2": "string
}
```
but
```
{
  "payload": {
    "field1": "string",
    "field2": "string"
  }
}
```
You can read more [here](https://flask.palletsprojects.com/en/2.0.x/api/?highlight=request#flask.Request.files) about how form & files are parsed for `multipart/form-data` are parsed by Flask.

This also means that the requestBody does not have a name defined. Read in our [docs](https://connexion.readthedocs.io/en/latest/request.html):
> In the OpenAPI 3.x.x spec, the requestBody does not have a name. By default it will be passed in as ‘body’. You can optionally provide the x-body-name parameter in your requestBody schema to override the name of the parameter that will be passed to your handler function.

So you can either change the name of the `payload` parameter in your function to `body`, or add `x-body-name: payload` to your spec and it will work.

**Comment by AlbyST** [comment]
Hi @RobbeSneyders,

thank you for the reply, as you suggest by renaming the parameter ```payload``` to ```body``` everything works as expected.

Thank you
