### ISSUE TITLE
Question: Dynamic Fixtures for Operations

### ISSUE THREAD

**Issue by MarcoRizk** [zalando/connexion#1433]
### Description
I am trying to find a way to add dynamic example data to responses. My schema is loaded from an Swagger 2.0 file generated by django so it usually doesn't have any examples and this would make the examples static anyways. My end goal was to implement some CI pipeline where the open api schema is extracted from django and is fed some sets of fixtures that I already have prepared.

The way I was going to approach this to have json fixtures named like each `definition` that is loaded when an operation with this definition is being called. My problem is I can't find a way to tell which definition is referenced in an operation. so how can I find which definition is being referenced or is there a better way to achieve the same goal ?

**Comment by RobbeSneyders** [comment]
Hi @MarcoRizk. I don't completely understand what you're trying to do, but it sounds like something connexion is not specifically made for. You might be able to use internal components to achieve your goal. You can have a look at the connexion `Operation` classes [which contain linked information from the openapi spec](https://github.com/zalando/connexion/blob/main/connexion/operations/abstract.py#L299).

**Comment by MarcoRizk** [comment]
> Hi @MarcoRizk. I don't completely understand what you're trying to do, but it sounds like something connexion is not specifically made for. You might be able to use internal components to achieve your goal. You can have a look at the connexion `Operation` classes [which contain linked information from the openapi spec](https://github.com/zalando/connexion/blob/main/connexion/operations/abstract.py#L299).

I ended up using `operation_id` as a unique identifier to load my fixtures. Thanks anyways
