### ISSUE TITLE
Question: Python3 Connexion CSRF Protection

### ISSUE THREAD

**Issue by imxari** [zalando/connexion#1438]
Hi,

I'm creating an application which uses Connexion with the swagger-ui as an API for a frontend using Flask and was wondering how would I go about implementing CSRF protection as I can't seem to find anything in the documentation that helps with doing so. Basically what I want to be able to do is on every request be able to send a state variable e.g: http://127.0.0.1/v1/create-user?state=arandomlygeneratedstatefromtheclientthatmachestheserver

Would anyone be able to assist/give me an idea on how to go about doing this? Many thanks!

**Comment by Ruwann** [comment]
Hi @imxari , unfortunately I'm not really familiar with CSRF protection myself.
Could you give an example of the corresponding OpenAPI spec? I think that should give us a good starting point.

What you could do, is add the query parameter `state` to every endpoint (although this is cumbersome)
