### ISSUE TITLE
Can't see 2.10 on pypi

### ISSUE THREAD

**Issue by NobbZ** [zalando/connexion#1443]
On the GitHub releases page I see there is a 2.10 released, which seem to fix a problem we have with some python reserved names.

Sadly on pypi 2.9 seems to be the most recent release:

https://pypi.org/project/connexion/#history

**Comment by RobbeSneyders** [comment]
Due to unavailability of maintainers with access to the connexion PyPi project, this version has been released under a new PyPi project connexion2 for now:
https://pypi.org/project/connexion2/

You can install it using
```pip install connexion2```

https://github.com/zalando/connexion/releases/tag/2.10.0

**Comment by RobbeSneyders** [comment]
@hjacobs @jmcs Any help getting this on the original PyPi would be appreciated.

**Comment by NobbZ** [comment]
This is unfortunate. This would be considered a new dependency rather than an update to fix a bug and requires an extended review process.

Is this expected to stay like this, or will it move back to `connexion` eventually? Or might there be just another name change in the foreseeable future? As I have seen there is a ticket for moving `connexion` out of the `zalando` organisation, as well as there is a ticket for a 3.0…

**Comment by matthewdeanmartin** [comment]
Y'all might be able to a 541 takeover. https://www.python.org/dev/peps/pep-0541/  It depends on if the person controlling the account has creative differences or if they have just disappeared or literally died. 541 seems to be for the later case.

**Comment by hjacobs** [comment]
We resolved the PyPI access and @Ruwann & co can release a proper new version under `connexion` :smile:

**Comment by RobbeSneyders** [comment]
Thanks @hjacobs!

2.10.0 is now available on the `connexion` PyPi:
https://pypi.org/project/connexion/2.10.0/

**Comment by sr-verde** [comment]
Shouldn't one delete the old `connexion2` package on pypi? Or – at least – leave a notice that one should not use this but the other package?

**Comment by RobbeSneyders** [comment]
Thanks for the reminder @sr-verde. I yanked the `connexion2` release and people installing it will get a message linking to the `connexion` package instead. Unfortunately, I can't update the PyPi readme for the project without pushing a new release.
