### ISSUE TITLE
Cannot make multipart/form-data content type to work

### ISSUE THREAD

**Issue by dimaa6** [zalando/connexion#1444]
### Description
I'm trying to write method which serves `multipart/form-data` request, but getting `validation error: ... is not of type 'object'`

### Expected behaviour
Validation must be passing.

### Actual behaviour
Validation fails.

### Steps to reproduce
I'm following [https://swagger.io/docs/specification/describing-request-body/multipart-requests/](url)

swagger snippet:

```
  /test:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
            encoding:
              address:
                contentType: application/json
      responses:
        '200':
          description: Success

      operationId: api_worker.test

```

curl:

`curl --location --request POST 'http://localhost:8088/api/test' --header 'Content-Type: multipart/form-data' --form 'address="{\"street\": \"mne\", \"city\": \"passp\"}";type=application/json'`

Output:

```
{
  "detail": "'{\"street\": \"mne\", \"city\": \"passp\"}' is not of type 'object'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

```

### Additional info:

Output of the commands:

- `python --version`

Python 3.6.2

- `pip show connexion | grep "^Version\:"`

Version: 2.9.0

**Comment by dimaa6** [comment]
Just tried using swagger UI and it fails with curl request generated by Connexion itself:

curl -X POST "http://localhost:8088/api/test" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "address={ "city": "string", "street": "string" }"

**Comment by dimaa6** [comment]
Workaround is to refuse from complex object address and bring its properties at upper level, then it works.

**Comment by RobbeSneyders** [comment]
Hi @dimaa6 

I can't reproduce this. Could you post a minimal working example?

This works for me:
`openapi/openapi.yaml`
```
openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"

paths:
  /test:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
            encoding:
              address:
                contentType: application/json
      responses:
        '200':
          description: Success

      operationId: main.test
```

`main.py`
```
import connexion


def test(body: dict) -> str:
    return f'Received {body}'


if __name__ == '__main__':
    app = connexion.FlaskApp(__name__, specification_dir='openapi/')
    app.add_api('openapi.yaml')
    app.run()
```

**Comment by dimaa6** [comment]
Hi @RobbeSneyders. I have tried with your exact code without any modifications. The only thing which you have not mentioned in curl. In my case it is:

`curl -X POST 'http://ip:5000/test' -H 'x-body-name: body' --form 'address="{\"street\": \"mne\", \"city\": \"passp\"}";type=application/json'`

and I got:

```
{
  "detail": "'{\"street\": \"mne\", \"city\": \"passp\"}' is not of type 'object'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

```

If it works for you, can you please show curl you are using?

**Comment by dimaa6** [comment]
Here is curl trace:

== Info:   Trying host...
== Info: TCP_NODELAY set
== Info: Connected to host (ip) port 5000 (#0)
=> Send header, 194 bytes (0xc2)
0000: POST /test HTTP/1.1
0015: Host: host:5000
002f: User-Agent: curl/7.58.0
0048: Accept: */*
0055: Content-Length: 208
006a: Content-Type: multipart/form-data; boundary=--------------------
00aa: ----1d48591dc3b23bf3
00c0:
=> Send data, 208 bytes (0xd0)
0000: --------------------------1d48591dc3b23bf3
002c: Content-Disposition: form-data; name="address"
005c: Content-Type: application/json
007c:
007e: {"street": "mne", "city": "passp"}
00a2: --------------------------1d48591dc3b23bf3--
== Info: HTTP 1.0, assume close after body
<= Recv header, 26 bytes (0x1a)
0000: HTTP/1.0 400 BAD REQUEST
<= Recv header, 40 bytes (0x28)
0000: Content-Type: application/problem+json
<= Recv header, 21 bytes (0x15)
0000: Content-Length: 155
<= Recv header, 38 bytes (0x26)
0000: Server: Werkzeug/0.16.0 Python/3.6.2
<= Recv header, 37 bytes (0x25)
0000: Date: Sun, 16 Jan 2022 08:24:35 GMT
<= Recv header, 2 bytes (0x2)
0000:
<= Recv data, 155 bytes (0x9b)
0000: {.  "detail": "'{\"street\": \"mne\", \"city\": \"passp\"}' is n
0040: ot of type 'object'",.  "status": 400,.  "title": "Bad Request",
0080: .  "type": "about:blank".}.
== Info: Closing connection 0

**Comment by dimaa6** [comment]
OK, upgraded connexion to 2.10.0 and it worked.

**Comment by RobbeSneyders** [comment]
Ok great to hear! thanks @dimaa6
