### ISSUE TITLE
Add example code that works with setup.py installation as egg/zip file

### ISSUE THREAD

**Issue by chrisinmtown** [zalando/connexion#1445]
### Description
Please consider this enhancement to the examples in the documentation. The basic examples that show `add_api('openapi.yml')` assume the user's module is installed into a directory.

### Expected behaviour
The Flask-connexion server should launch and run as expected no matter how it is installed, assuming of course the setup.py file is reasonable.

### Actual behaviour
The server launches and runs as expected on example (simple) code if the module is installed via `pip3 install .` 

Using example (simple) code, the server fails to launch if the module is installed via `python setup.py install` with this kind of error because it cannot find a yaml file in an egg file:
```
NotADirectoryError: [Errno 20] Not a directory: '/Users/me/.virtualenvs/py39/lib/python3.9/site-packages/mysrv-0.0.1-py3.9.egg/mysrv/openapi.yml'
```

### Steps to reproduce
Most example code that hooks the server to the open API spec file looks like this:
```
app = connexion.App(__name__, specification_dir="./")
app.add_api('openapi.yml')
```

I suggest use of a library like `importlib_resources` so installed servers work whether installed by pip3 or setup.py, here's my proposed code:
```
import importlib_resources

app = connexion.App(__name__)
yaml_path = importlib_resources.files('mysrv').joinpath('openapi.yml')
with importlib_resources.as_file(yaml_path) as yaml:
    conn_app.add_api(yaml)
```
I'm sure this can be improved further too.

### Additional info:
```
% python --version
Python 3.9.7
% pip show connexion | grep "^Version\:"
Version: 2.9.0
```

I hope this is clear, I'll be glad to revise/update, thanks in advance for considering this.

**Comment by RobbeSneyders** [comment]
Hi @chrisinmtown 

When packaging python code, you'll always have to pay special attention to including and accessing non python files as part of the package. I don't think we should complicate all examples for this edge case.
