### ISSUE TITLE
[Feature Request] Enable strict data validation in put/post body json

### ISSUE THREAD

**Issue by linhandev** [zalando/connexion#1449]
### Description
Currently the strict_validation set during app creation seem not to restrict put/post body data. Would be really nice if strict_validation can also be enforce there.

### Expected behaviour

Enforce strict_validation in put/post body data

### Actual behaviour

Currently strict_validation seems not to be enforced in put/post body

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`
pip show connexion | grep "^Version\:"
Version: 2.10.0

**Comment by RobbeSneyders** [comment]
Hi @linhandev 

You can use the `additionalProperties` flag in your json schema to control strict validation of request bodies.
For more info, please refer to #837.

**Comment by linhandev** [comment]
Got it. I was using yaml, adding at the same level as properties does the trick. In case any newbies like me is looking for this
![image](https://user-images.githubusercontent.com/29757093/151337415-7f718cc2-6892-4301-a0ae-b25a8bb377c5.png)
