### ISSUE TITLE
Remove usage of HTTP_TOKENINFO_URL environment variable

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#148]
Follow up to #146 

This should be done not before March 2016.

**Comment by rafaelcaricio** [comment]
Why it shouldn't be done before March 2016?

**Comment by hjacobs** [comment]
@rafaelcaricio that's just an arbitrary date to give people the chance to see the warning (if they always rely on the latest version) --- we could do it anytime :smirk:

**Comment by hjacobs** [comment]
I'm personally relying on latest versions of many libraries and I don't like it if they break suddenly without any prior deprecation warnings..

**Comment by rafaelcaricio** [comment]
Ok. I was just curious why that specific date. :+1: I understand your concern and support the idea. :smiley:
