### ISSUE TITLE
Consider bravado-core to manage OpenAPI/Swagger 2.0 validation/parser

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/connexion#151]
I have found that we are dealing a lot with OpenAPI/Swagger 2.0 Specification validation and parsing in Connexion code. I was willing to implement an library independent of Connexion code that would manage all those reference checks and validations in a way that could be used by Connexion and other packages that want to deal with OpenAPI Specification. I have found that there is already a package that does exactly what I was looking for. It is called [bravado-core](https://github.com/Yelp/bravado-core) by Yelp. 

The question is, have you already considered that before? If so, why not reuse that code? If not, what do you think about that idea?

There are many advantages and disadvantages of going that way. Like the core functionality of Connexion being dependent of an external library being the biggest concern. But there are also great benefits like a lot of work is done ahead on supporting the OpenAPI specification.

**Comment by hjacobs** [comment]
@rafaelcaricio thanks for the hint, I'm planning on writing a library to automatically have a convenient command line client for Swagger APIs: https://github.com/zalando/openapi-cli-client

**Comment by rafaelcaricio** [comment]
I will try to fit `bravado-core` into Connexion code and see what happens.

**Comment by rafaelcaricio** [comment]
I started working on it and seems like we are already supporting some invalid definitions. I am thinking about creating a compatibility layer over the invalid declarations we are supporting and throwing a warning for those while fixing them automatically whenever possible. Also I am fixing our code to work only with valid specification. I just wanted to update you all with the status of this task.

**Comment by rafaelcaricio** [comment]
I have backed up on using `bravado-core` since it's propose is other than being used in backend applications to handle specs. We would need to call their internal functions/methods that could change anytime and make bad impact in how we would use it in Connexion codebase.

Instead I decided to just use the [`swagger_spec_validation`](https://github.com/Yelp/swagger_spec_validator) package which will guarantee that we stick to the proper valid Swagger/OpenAPI 2.0 specification. That addition is ready to be merged in the pull request #160. Please review and/or give feedback on that.
