### ISSUE TITLE
Log details of response validation errors?

### ISSUE THREAD

**Issue by danballance** [zalando/connexion#153]
Hi guys,

I'm not sure if I'm missing an option here - or maybe I can add something in for you? So I haven't upgraded in a while and now when I run my code I get this error message:

500, "Response body does not conform to specification"

Tracing this back through the code, this seems to be generated at lines 54-56 of decorators/response.py. If I examine the error returned, there is plenty of information to help me fix my broken response, but there doesn't seem to be any way for me to discover what the underlying issue is without inspecting the code.

Shall I submit a pull request with some extra debug logging there? IMO it would be useful to check your logs at this point and see exactly what the validation problem is - even if we are only returning the generic error to the end user.

Let me know your thoughts!

**Comment by hjacobs** [comment]
@danballance I guess that sounds reasonable :smile:

**Comment by rafaelcaricio** [comment]
Hi @danballance! It makes total sense what you wrote. If you can send a PR with your suggestions would be even better. Anyway, submitting an example of what your are experiencing would help to learn how we can improve.

**Comment by danballance** [comment]
Hi guys,

I got sidetracked with other work, but hope to get a pull request in this week. It's only quite a simple change to add the extra logging.

**Comment by rafaelcaricio** [comment]
Solution for this issue being discussed in https://github.com/zalando/connexion/pull/186
