### ISSUE TITLE
Silencing ImportErrors raised in modules referenced by operationId

### ISSUE THREAD

**Issue by jkozlowicz** [zalando/connexion#155]
To reproduce simply create an incorrect import that will raise an ImportError in a module that is referenced by operationId of an endpoint specified in a swagger API.

```
project/swagger/api.yaml
---------------------------------
...
paths:
    /scms:
         get:
             operationId:
                  api.scms.test
...



project/src/api/scms.py
---------------------------------
#broken import
import something_broken

def test():
    return {'test': 'ok'}, 200

```

When URL `/api/scms` is requested the module raises an `ImportError` and the test method is not reachable, but connexion proceeds and it says:
```{"status": 404, "type": "about:blank", "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.", "title": "Not Found"}```
without re-raising the exception so it is not clear what failed.

**Comment by hjacobs** [comment]
:+1: good point, better error messages would be helpful here --- maybe just log an error?

**Comment by jkozlowicz** [comment]
I would rather re-raise the ImportError. Logging the error would have the following meaning for me:
Some of your views could not be imported, but the applications has been started anyway.

I'd rather prevent application from starting when something could not be imported and show why and where it failed. To me that seems to be the most reasonable choice.

**Comment by rafaelcaricio** [comment]
I agree with @jkozlowicz even more because it is a route that will be unavailable and your specification is saying that it should be available. So it should fail badly and not start the server in that case.

**Comment by rafaelcaricio** [comment]
That is actually the problem: https://github.com/zalando/connexion/pull/28

It was intentionally added to keep the application going, there is even a [test for it](https://github.com/zalando/connexion/blob/master/tests/fakeapi/api.yaml#L433-L450). Connexion keeps going even if there is a problem adding a operation. @hjacobs @jmcs Should we change that?

I still agree that this kind of problem should not be silenced. But maybe you have any use case where it is useful?
