### ISSUE TITLE
Proposed Tagline change 

### ISSUE THREAD

**Issue by LappleApple** [zalando/connexion#158]
The current tag -- "Python Flask Framework to automagically handle REST API requests based on OpenAPI/Swagger"—doesn't completely convey all that Connexion does, or what makes it particularly useful. 

The tagline at Swagger.io—"A Swagger-first REST framework on top of Flask with validation and OAuth 2 support"—brings in the OAuth 2 support, which is good. 

But I'm wondering if the focus should be more along the lines of, "with Connexion, you write the Swagger spec, then it calls your Python code, handling the mapping from the specification to the code--not the other way around." In more concise language, obviously. :) Thoughts?

**Comment by jmcs** [comment]
Maybe we can include "Api First"®™ there to be buzzword compliant :)

**Comment by hjacobs** [comment]
Uppercase "API" please... :smirk:

**Comment by LappleApple** [comment]
"API First" is subjective -- I'd stick to functionality

**Comment by rafaelcaricio** [comment]
My 2 cents:

> Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation and OAuth2 support

or

> Automatic Swagger/OpenAPI specifications to Python functions with payload validation and OAuth2 support

**Comment by rafaelcaricio** [comment]
Any decision on that?

**Comment by LappleApple** [comment]
I think #1 is clearer
