### ISSUE TITLE
Global response definitions not supported

### ISSUE THREAD

**Issue by ja-b** [zalando/connexion#180]
When response validation is enabled, we trigger the `$ref needs to point to definitions or parameters` when using global response definitions. The swagger [spec](http://swagger.io/specification/) contains the responses field as global and should support references to global responses.

This is a matter of copying the behavior for definitions and parameters to handle responses. I can add a pull request for this.

**Comment by hjacobs** [comment]
@rafaelcaricio @jmcs could you check this?

**Comment by rafaelcaricio** [comment]
@ja-b please check #187 .

**Comment by ja-b** [comment]
lgtm, this issue can be closed on merge.
