### ISSUE TITLE
How are new releases to PyPI indicated?

### ISSUE THREAD

**Issue by dfeinzeig** [zalando/connexion#183]
i love the momentum that is gaining with this package. how can i tell which code is included in which releases to pypi? can we maybe use tags or have PRs that include the version increment and release or such?  thanks!

**Comment by hjacobs** [comment]
We are using release tags, these are automatically created by our Continuous Delivery pipeline (as soon as I press the "release" button): https://github.com/zalando/connexion/releases

**Comment by hjacobs** [comment]
NOTE: the release description on GitHub is not automatic, so I add bullet points manually with a short summary :smile:

**Comment by hjacobs** [comment]
FYI: the release process steps are basically in here: https://github.com/zalando/connexion/blob/master/release.sh

* replace the version number in __init__.py
* upload to PyPI (python3 setup.py sdist bdist_wheel upload)
* git tag && git push --tags

Afterwards I add the release note on GitHub manually.

**Comment by hjacobs** [comment]
If you want to be notified, either watch this repository or see e.g. https://stackoverflow.com/questions/17395151/how-can-i-subscribe-to-updates-of-a-package-on-pypi

**Comment by dfeinzeig** [comment]
Awesome!  Thanks for the pointer to /releases !

**Comment by WouterVH** [comment]
for releasing, you might look into the zest.releaser-package.
