### ISSUE TITLE
Is a standalone Framework in top of Flask o can be implemented as a Flask Blueprint?

### ISSUE THREAD

**Issue by srlopez** [zalando/connexion#188]
Just my question.

Is there a sample with connexion implemented as a Blueprint for Flask.
Could be interesting to use existing server apps to server api too with connexion.

Thanks

**Comment by jmcs** [comment]
You can instantiate an [Api object](https://github.com/zalando/connexion/blob/master/connexion/api.py#L48) and use the `Api.blueprint` to add the API blueprint to Flask. At least for simple applications you can also use the App object from connexion as you would use a Flask App object.

**Comment by srlopez** [comment]
Thanks @jmcs  Joao . Don`t know too much about Api.object. I'll try to doit.
Close the issue.
Thanks again

**Comment by jasonrhaas** [comment]
I'm managing all my different endpoints (using different flask extensions) with blueprints so this is super helpful.  

As far as this statement goes:

> you can also use the App object from connexion as you would use a Flask App object

Make sure you use `connection.App().app` for this.  `connection.App()` is not an instance of `flask.Flask`, but `connection.App().app` is.

**Comment by sxslex** [comment]
"""Implement load api from swagger using template import yam."""
    import yaml
    import connexion
    from jinja2 import FileSystemLoader
    from jinja2.environment import Environment
    
    
    def connexion_register_blueprint(app, swagger_file, **kwargs):
        con = connexion.FlaskApp("api", app.instance_path)
        env = Environment(loader=FileSystemLoader(
            app.config.get('SWAGGER_ROOT_TEMPLATE') or
            app.config['PROJECT_ROOT']
        ))
        swagger_string = env.get_template(swagger_file).render(**kwargs)
        specification = yaml.safe_load(swagger_string)
        api = super(connexion.FlaskApp, con).add_api(specification, **kwargs)
        app.register_blueprint(api.blueprint)
        return api
    
    ...
    connexion_register_blueprint(app, 'api/v1/swagger/main.yaml')
    ...
