### ISSUE TITLE
Python3 syntax used in exception

### ISSUE THREAD

**Issue by d6e** [zalando/connexion#190]
In `connexion/api.py::add_paths()`, the following statement is used in an `except` block:
```
raise ei.with_traceback(tb)
```
This statement will fail with an AttributeError when using python2.

**Comment by dfeinzeig** [comment]
This is now fixed in master with PR #186 .

**Comment by d6e** [comment]
Nevermind, this appears to be fixed in a recent commit 191ec9aeda283d20dc56c55e74ab477511f1faf5.
