### ISSUE TITLE
version-mismatch: v1.0.33 in master, while v1.0.76 was already released

### ISSUE THREAD

**Issue by WouterVH** [zalando/connexion#194]
On pypi I see as latest release v1.0.76
https://pypi.python.org/pypi/connexion/1.0.76

yet  in github-master I see 1.0.33
https://github.com/zalando/connexion/blob/master/connexion/__init__.py

this breaks my setup when using addon packages like swagger-tester
https://github.com/Trax-air/swagger-tester

this depends on connexion >=1.0.37, so when I switch to master, 
my setup stops working because of broken dependencies.

The fact that the version-number is incorrect seems to indicate a broken release-process?

**Comment by hjacobs** [comment]
We patch the version number during the release process, but the change is not pushed to master (only tagged) --- I guess we can replace the version number in `__init__.py` with something like "dev" or "unknown".

You can verify that the version number is correct in the PyPI sdist Tar GZip: https://pypi.python.org/packages/source/c/connexion/connexion-1.0.81.tar.gz#md5=f02832b1e329257af48d2b8e5487c05b

@jmcs @rafaelcaricio what about changing the version number in "master" to something unspecified? I don't want to push the version number bumps, that just generates unnecessary commits (and we have the tags).

**Comment by rafaelcaricio** [comment]
@hjacobs I added a PR to try to avoid those kind of problems from now on. Please take a look at #201

**Comment by WouterVH** [comment]
please take a look at PEP 0386: https://www.python.org/dev/peps/pep-0386
version-numbers should be comparable,and where :
master dev-version  >  v1.0.76

is v0.0.0 >  v1.0.76?  Definitelety not, and this will break dependencies

**Comment by WouterVH** [comment]
a good dev-version-number is
next release + ".dev0"

it should be rather  v1.0.77.dev0

**Comment by rafaelcaricio** [comment]
@WouterVH Not sure if you read the @hjacobs comment previously. This value is replaced during the release processes before publishing into [pypi](https://pypi.python.org/pypi). So it will not break anything.

Please use the Connexion package from *pypi* (oficial published version) and not a local clone to avoid this kind of problems. Or since you want to use a local version of Connexion change the version number manually for yourself.

**Comment by rafaelcaricio** [comment]
In the PR #201 the version **placeholder** was updated to `2016.0.dev1` to be complaint with PEP-440.
