### ISSUE TITLE
Not possible to return Decimals from the controller

### ISSUE THREAD

**Issue by kmoppel** [zalando/connexion#196]
I'm getting a serialization error when returning python Decimal data types with the built in automatic JSON serialization.
I guess one solution would be to add special handling in JSONEncoder and convert to str or float or maybe just make it possible to provide a custom JSON serializer.

  File "/usr/local/lib/python3.4/dist-packages/connexion/decorators/produces.py", line 44, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('1') is not JSON serializable

**Comment by rafaelcaricio** [comment]
Hi @kmoppel thank you for bringing up this issue. Would it be better for you to convert your `Decimal` value to string yourself and then return in your view? I say that because `Decimal` conversion to string is tricky since every usage needs a different precision.

**Comment by kmoppel** [comment]
Hi, thanks for the reply! Well, converting myself would be of course doable but could definitely get tricky with nested datatypes and such...so I think being able to provide a custom serializer would be the best. Flask already supported something like that (http://flask.pocoo.org/snippets/119/), but when I tried like described it didn't have an effect.

**Comment by rafaelcaricio** [comment]
@kmoppel Got it. I tried to reproduce and then sent a PR to fix that. Please check the #199.
