### ISSUE TITLE
JSON generated not in order with respect to the YAML file

### ISSUE THREAD

**Issue by jerameelsaavedra** [zalando/connexion#213]
### Description
Json that is generated is out of order then output on the swagger ui is not in order with respect to the yaml file

### Expected bahaviour
to follow the order that is assigned on the yaml file

### Actual behaviour
random order of the operations

### Steps to reproduce
I followed the tutorial and the examples that are on this repo

### Additional info:

Output of the commands:

- `python --version` : 3.4
- `pip show connexion | grep "^Version\:"` : 1.0.84

**Comment by rafaelcaricio** [comment]
JSON objects should not rely on ordering of members. Ref.: https://tools.ietf.org/html/rfc7159#page-6

This is **not** an issue/bug.

What is your problem with that not being ordered?

**Comment by jerameelsaavedra** [comment]
yes you are right it not an issue but i would like to have it in order as when i create a yaml and they show in order( as on the swagger ui website ). .  its not a big deal but i would like to show them organize and not randomly in different places. do you know a way that i can show them in order using connexion ?thank you

**Comment by rafaelcaricio** [comment]
Not with Connexion.

You can run your own Swagger UI instance that reads your API JSON spec and customise the frontend code to render it the ordering you want. It has nothing to do with Connexion.
