### ISSUE TITLE
How is Connexion doing in production?

### ISSUE THREAD

**Issue by nickdirienzo** [zalando/connexion#221]
I'm considering using Connexion in production for similar reasons [Zalando's blog post](https://tech.zalando.de/blog/meet-connexion-our-rest-framework-for-python/) outlines.

I have a couple of questions before actually doing that, none of which are actually issues, but this seems like the best medium to get in touch with the team behind this project to help shed some light here.

Given that the post is from January (but commit history goes back a year), I'm interested in how Connexion has served Zalando in a production environment:
- Is this project used in production?
- If so, how is it performing? 
 - How many requests does it handle over a given day (or hour)?
 - Do you have percentile breakdowns of the time it takes to service a request?
- What's the progress on #124? It seems that the only way to implement our own authentication is to decorate functions explicitly.

If other organizations use this in production, I'm interested in hearing your thoughts on how it's served your production environments as well.

Thanks.

**Comment by hjacobs** [comment]
We are using it in "production" at Zalando, at least for low-traffic services (not anything customer facing). One example is Lizzy: https://github.com/zalando/lizzy (both traffic and latency do not matter in this case)

I'll try to find out what use cases Connexion is used for in Zalando...

**Comment by nickdirienzo** [comment]
Thanks for the quick reply, @hjacobs. Oh, okay. Thanks for digging up more use cases / data on it.

**Comment by nickdirienzo** [comment]
This is a bit of an aside, but because of your experience with API First / Swagger-first services, what project is running your customer-facing API gateway?

**Comment by drummerwolli** [comment]
@nickdirienzo e.g. our spark-appliance is using connexion as a http interface for handling request in a restful manner: https://github.com/zalando/spark-appliance

several teams are using this for production usecases, mostly in analysis and reporting. again: latency, traffic and speed do mostly not matter here. but connexion is serving us well there ... @chutium can tell you more about it ...

**Comment by chutium** [comment]
Hi @nickdirienzo , yes, our team is using Connexion for some low-traffic services, non-customer-facing API, such as the spark-appliance mentioned by @drummerwolli , there is a REST API built with Connexion (https://github.com/zalando/spark-appliance/blob/master/webapp.py) for providing an OAuth/JWT protected gateway for spark cluster.

but yes, latency, traffic or speed are no matter here, all of REST API call to this spark-appliance are async.

**Comment by hjacobs** [comment]
@nickdirienzo here the other API First frameworks (JVM based) we use: https://github.com/zalando/restful-api-guidelines/blob/tooling-section/tooling/Tooling.md

**Comment by nickdirienzo** [comment]
Ah alright. Thanks for the info on how you use Connexion internally, @drummerwolli and @chutiu. And thanks for the extra info on API First frameworks, @hjacobs!

**Comment by cadupont** [comment]
Great thread, thanks for sharing. Has anyone done a benchmark to see the real cost of connexion? (Maybe it isn't that expensive?)
ps. @hjacobs Your last link is dead.

**Comment by hjacobs** [comment]
@cadupont thanks, I updated my comment :smile:
