### ISSUE TITLE
AWS API Gateway, Lambda & DynamoDB

### ISSUE THREAD

**Issue by rog555** [zalando/connexion#230]
Would be interesting to have another server mode that could run this as on AWS Lambda behind API Gateway, loading its YAML files from another datasource such as DynamoDB or S3 (could adding yaml files/datasources be pluggable perhaps rather than filesystem?)

https://zappa.gun.io/ does something similar with Flask, though it creates all the API Gateway configuration - something which Terraform and Apex can also do, but in a lighter weight deployment mechanism (ie without virtualenv) and with more control.

API Gateway of course now has Swagger import also, but this has to be done upfront with creation of API Gateway infrastructure so less dynamic in nature than what Connexion could potentially offer (plus ability to run APIs locally or on non-serverless based VMs/containers as it currently does)

Any thoughts on the feasibility / interest on this appreciated

**Comment by rog555** [comment]
managed to do something similar to zappa and invoke out-of-the-box connexion running as lambda behind API Gateway using apex
https://4wf2zjem76.execute-api.us-east-1.amazonaws.com/dev/greeting/bob
would need to do all the middleware mapping as zappa however (might just be easier to user zappa to call connexion :-) )

**Comment by rafaelcaricio** [comment]
@rog555 That sounds like an interesting setup. But I cannot imagine how Connexion could change to help on that. It sounds more like a separated tool that would deploy Connexion apps in AWS Lambda and as you said seems like Apex did the job. I will give a try to this use case to get more familiar with this idea.

**Comment by rafaelcaricio** [comment]
@rog555 it was pretty straight forward to deploy the connexion example project with zappa https://vgd8lgzajc.execute-api.us-east-1.amazonaws.com/dev/pets

I will close this issue since it has nothing to do with Connexion.
