### ISSUE TITLE
dynamically add_api based on http header

### ISSUE THREAD

**Issue by rog555** [zalando/connexion#231]
Hi, i'm trying to add different APIs dynamically based on the basic auth user or oauth token being sent in the request.  Is there any way to do this?
thanks
roger

**Comment by rafaelcaricio** [comment]
That is more a question on the Flask side. We translate your Swagger definition to Flask blueprint before running the Flask app instance.

To change that blueprint in runtime I would recommend you to look how to do it in Flask first. I found that http://stackoverflow.com/questions/16016060/change-blueprints-or-reload-flask-app-during-runtime might be what you want.

Anyway personally I think you should probably think about scopes of authenticated users to allow users to call different endpoints of your API than changing the API server in runtime. More on that: http://zalando.github.io/restful-api-guidelines/security/Security.html#must-define-and-assign-scopes

**Comment by rog555** [comment]
Thanks, someone on the pocoo channel pretty much said its not possible with flask, as the blueprint is instantiated before the request comes in.  I'd be calling this via AWS API Gateway / Lambda, so would actually have the request header before starting up connexion.  

The use case i'm chasing here, is a form of service virtualisation - where i can define APIs that emulate services and test data sets, and where the dataset is defined by the user (which is often the only thing that can be changed outside of the already established API and client SDKs).  Swagger/API definition would be loaded in from another config source (ie DynamoDB) based on the user authenticating

**Comment by rog555** [comment]
btw - is there a better place for raising questions on connexion - or github issues OK? (i have another one already!)

**Comment by hjacobs** [comment]
@rog555 GitHub issues are OK IMHO (we can flag those issues as "question") :smile:
