### ISSUE TITLE
multiple operationId's to same function

### ISSUE THREAD

**Issue by rog555** [zalando/connexion#233]
Hello, I'm trying to find a way to have multiple API endpoints reuse the same operationId / method (ie like a generic handler), however get an error back from Flask:

  AssertionError: View function mapping is overwriting an existing endpoint function

It looks like its possible in blueprint add_url_rule:  http://stackoverflow.com/questions/17256602/assertionerror-view-function-mapping-is-overwriting-an-existing-endpoint-functi

perhaps via a custom resolver - or is there an easier way?

Sort of coupled to this, is there anyway to add additional configuration into the swagger yaml that could get passed to the generic function / handler?

thanks

roger

**Comment by rafaelcaricio** [comment]
It is not allowed by [swagger specification](http://swagger.io/specification/#operationObject) thus Connexion does not support that. From the specification:

#### operationId (*string*)
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

You are probably looking for [vendor extensions](http://swagger.io/specification/#vendorExtensions). But Connexion currently does not pass any metadata of vendor extension to the handlers. Maybe that something that could change, but currently I do not see how it could work. If you are interested in that, you can suggest something for discussion.

**Comment by rog555** [comment]
Thanks for confirming, maybe if something like x-connexion-operation is optionally supplied, then this is used instead of operationId, which is left as whatever it is defined as (and as you highlight, has to be unique)

Eg:

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: something-unique
      x-connexion-operation: hello.post_greeting
      x-connexion-operation-params:
        -name: someKey1
         value: someValue1
         type: string
        -name: someKey2
         value: someValue2
         type: string
      }
      
Maybe also, x-connexion-operation-params could be used to additional pass params/configuration to the operation as a dict, additionally available somehow to the operation (worse case, written into flask.request perhaps...)

thanks

**Comment by rafaelcaricio** [comment]
@rog555 With Connexion we try to stay as close as possible with Swagger specification and handle creation of standard REST API's. What you are proposing here goes far beyond what Connexion suppose to support. In that case I would recommend you to maybe fork Connexion and modify it to behave the way you are trying to describe here.
