### ISSUE TITLE
Don't send back entire schema after validation errors

### ISSUE THREAD

**Issue by jvinet** [zalando/connexion#234]
### Description

When Connexion validates incoming data and finds a property is missing, it will dutifully report this back to the caller. However, it will include the entire swagger spec/schema as part of the response. For large APIs, this can be tens of KB of text, which is not ideal for debugging or logging.

### Expected behaviour

Expect to only receive the error portion, eg: "Missing required property 'email'"

### Actual behaviour

I receive the error portion following by a long JSON string that is my Swagger spec.

### Steps to reproduce

The actual generation of this error appears to occur in *jsonschema*, but this can be solved within Connexion by only sending back the `.message` attribute in the `problem()` call, rather than the string-representation of the entire exception object.

    def validate_schema(self, data):
        """
        :type schema: dict
        :rtype: flask.Response | None
        """
        if self.is_null_value_valid and is_null(data):
            return None

        try:
            validate(data, self.schema, format_checker=draft4_format_checker)
        except ValidationError as exception:
            logger.error("%s validation error: %s" % (flask.request.url, exception))
            return problem(400, 'Bad Request', str(exception))

        return None

Instead, the second-to-last line could read:

            return problem(400, 'Bad Request', exception.message)

Which will return the expected (and succinct) error message without the Swagger spec included.

### Additional info:

Output of the commands:

- `python --version`
  - Python 3.5.1

- `pip show connexion | grep "^Version\:"`
  - Version: 1.0.88

**Comment by jvinet** [comment]
I should mention that this `str(exception)` behaviour occurs in a second place in the `decorators/validation.py` file as well, in the `validate_parameter()` method of the `ParameterValidator` class.

This is likely the spot where I was seeing this behaviour, not the schema validation itself.

**Comment by hjacobs** [comment]
Thanks for your issue report! I haven't tried it myself, but it sounds reasonable.

**Comment by jvinet** [comment]
Great! As a little addendum, I'll include the relevant part of jsonschema's code that is shoving the whole schema into the error response.

    def __unicode__(self):
        essential_for_verbose = (
            self.validator, self.validator_value, self.instance, self.schema,
        )
        if any(m is _unset for m in essential_for_verbose):
            return self.message

        pschema = pprint.pformat(self.schema, width=72)
        pinstance = pprint.pformat(self.instance, width=72)
        return self.message + textwrap.dedent("""

            Failed validating %r in schema%s:
            %s

            On instance%s:
            %s
            """.rstrip()
        ) % (
            self.validator,
            _utils.format_as_index(list(self.relative_schema_path)[:-1]),
            _utils.indent(pschema),
            _utils.format_as_index(self.relative_path),
            _utils.indent(pinstance),
        )

As you can see, the str/unicode representation of the exception object is the concatenation of the error message itself _and_ the entire schema.

If Connexion were to use the inner `.message` attribute instead of the str/unicode representation, then I think we'd be good.

Alternatively, that `essential_for_verbose` test seems to alter the behaviour here, though I'm not yet sure if it's intended to be manipulated by the calling module or not...

Thanks again.

**Comment by pkjg** [comment]
The entire schema is
1. poorly formatted with '\n's and tabs.
2. too much information to the consumer from a production setup point of view.

something like this to extract the first line of the message should help.
str(exception)[:(str(exception).find('\n'))]

**Comment by pkjg** [comment]
The entire schema is
1. poorly formatted with '\n's and tabs.
2. too much information to the consumer from a production setup point of view.

something like this to extract the first line of the message should help.
`str(exception)[:(str(exception).find('\n'))]`

**Comment by pkjg** [comment]
The entire schema is
1. poorly formatted with '\n's and tabs.
2. too much information to the consumer from a production setup point of view.

something like this in **validation.py** to extract the first line of the message should help.
`str(exception)[:(str(exception).find('\n'))]`

I am looking forward for this issue's resolution.
