### ISSUE TITLE
Stricter requirements.txt?

### ISSUE THREAD

**Issue by dimbleby** [zalando/connexion#246]
The recent release of flask 0.11.0 required Connexion changes, per #240.

Since your `requirements.txt` says [`flask>=0.10.1`](https://github.com/zalando/connexion/blob/1.0.88/requirements.txt), the result was that all versions of Connexion that do not include that fix are broken.

As it happens this isn't a big deal this time; upgrading has just been a matter of figuring out what has happened and moving to a more recent version of Connexion.  But if, for instance, Connexion had changed more in the meantime then it might easily have been awkward.

This project can't predict what breaking changes might be released by upstream projects, so it would be more prudent to make upgrade of dependencies be explicit and not, as this time, accidental.

Therefore suggest that requirements.txt should contain exact rather than minimal requirements.  

(Probably it's OK to allow variation in minor releases so long as we can trust upstream to have some adherence to semantic versioning so eg something like `flask>=0.10.1,<0.10.99` would be reasonable).

**Comment by hjacobs** [comment]
I would like to keep the relaxed requirements (mostly for convenience), in real world scenarios this is not a problem as you always can pin your application dependencies to something fixed. I'd like to avoid a dependency hell where my app requires Connexion==123 and libfoo=456, but Connexion wants libfoo==789.

**Comment by dimbleby** [comment]
This absolutely is a problem in real world scenarios.  There was a period (between the releases of flask 0.11 and, I think, connexion 1.0.98) where typing `pip install connexion` resulted in a setup that was broken.

I know this because it happened to the chap who sits next to me, and who was consequently not too impressed by my suggestion that he try connexion out!

**Comment by dimbleby** [comment]
So as to make the discussion concrete, I've opened #247

**Comment by rafaelcaricio** [comment]
@dimbleby IMHO your application is what should have strict version dependencies (do a `pip freeze`) with each dependency package pointing to a specific version you tested your app with.

If a new version of the packages that Connexion uses have a new release we will fix Connexion to be compatible as soon as possible as we did with the latest version of "requests". We have CI for catching those kind of problems + active community of users that will report/solve the problem if it arises.

**Comment by dimbleby** [comment]
(You mean `flask`, not `requests`).

I can only reiterate that for about two weeks, `pip install connexion` gave a broken installation.  It would surely be a good thing if such things could be prevented in advance rather than eventually fixed.

If you think that this is not important, or not important enough: well, fair enough.  I've said my piece here - if you all don't agree, then please feel free to reject the issue and pull request.  No hard feelings!

**Comment by rafaelcaricio** [comment]
Yes, I meant `flask` sorry.

We could set strictly versions of each dependency and guarantee that Connexion would work always when installed. But as Connexion is a package that will be deployed together with your own code we leave to you the freedom and responsibility to choose to use the latest version of the dependencies you want.

Anyway, If you want to guarantee that Connexion installation will always works, you can use the specific minimal versions declared in the `requirements.txt`. Just do:

```
$ curl https://raw.githubusercontent.com/zalando/connexion/master/requirements.txt | sed s/\>=/==/ | xargs pip install
```

**Comment by dimbleby** [comment]
Yes, but... are you seriously suggesting that this is how new users should install Connexion?  

(If so I guess you should update the README).

**Comment by rafaelcaricio** [comment]
Of course I am not suggesting that new users should install connexion that way. I am suggesting it to you.

**Comment by dimbleby** [comment]
OK, I think we're talking slightly past one another.  

I understand this issue completely, and can absolutely freeze my requirements and not have more problems in the future.  The issue isn't about me.

Rather, I've raised it in the hope of making Connexion better for future users; and in particular because of the experience of the [chap sitting next to me](https://github.com/zalando/connexion/issues/246#issuecomment-225239563) who was indeed unfortunate enough to `pip install connexion` during the time when it was broken.

It seems to me that you should want to avoid this sort of problem.  

But I think your position is something like: 

- that's not a very serious problem because it doesn't happen often
- we think it's more important that users have absolute flexibility to upgrade dependencies

If that's so: well then, I think you're mistaken, but it's your project and you should just reject the issue - with, as I say, no hard feelings on my part.
