### ISSUE TITLE
access to Model objects

### ISSUE THREAD

**Issue by jaconstantine** [zalando/connexion#255]
### Description

I'm trying to extend a swagger-codegen app replacing the generated controller functions with real code.  So for example I want to expand:

```
def site_name_get(name) -> str:
    return 'do some magic!'
```
with something that does real work.  I'd like to have access to Model objects, the ones that I defined in the ```definitions:``` section of the swagger yaml file.  In that section I have specified that I have a Site model that has a bunch of fields. How can I create a new Site?

### Expected bahaviour

I'd expect to be able to say:

```
s = Site()
```

### Actual behaviour

???

### Steps to reproduce

* run the app

### Additional info:

Output of the commands:

- `python --version` 3.5.2
- `pip show connexion | grep "^Version\:"`  1.0.103

**Comment by hjacobs** [comment]
@jaconstantine short answer: there is AFAIK currently no way in Connexion to conveniently use Swagger schema objects as Python objects, i.e. if your function returns a "Site" you will have to create a proper `dict` manually (or by other means). Please check this example for one way of mapping DB objects "automatically": https://github.com/zalando/connexion/tree/master/examples/sqlalchemy

**Comment by jaconstantine** [comment]
Thanks for the tip.  I'll look for another way to get what I need to get done done.

**Comment by rafaelcaricio** [comment]
Connexion validates the fields, do type conversions, and pass along a valid `dict` (following your spec) there is not object mapping.
