### ISSUE TITLE
GET route with parameter in .yaml file don't show 200 as an possible HTTP Status Code response

### ISSUE THREAD

**Issue by abnerjacobsen** [zalando/connexion#263]
### Description
In my connexion API yaml file I have this:

```
    /{database_id}:
        get:
            tags: [Databases]
            operationId: modules.databases.api.get_database
            summary: Get a single database
            parameters:
                - $ref: '#/parameters/database_id'
            responses:
                200:
                    description: Return database
                    schema:
                        type: object
                        $ref: '#/definitions/Database'
                404:
                    description: Database does not exist
```

but, when I go to swagger ui I only can see in the "Response Messages" section the 404 response as sole type of response

if my .yaml file have only

```
            responses:
                200:
                    description: Return database
                404:
                    description: Database does not exist
```

the swagger ui show avaiable responses as 200 and 404 as expected.

### Expected bahaviour

I want so see that the rest call can return 200 or 404

### Actual behaviour

I only can see in the swagger ui the 404 as only response for the rest call

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by jmcs** [comment]
Can you check the generated `/swagger.json` to see if it matches the yaml?

**Comment by rafaelcaricio** [comment]
@abnerjacobsen First I would like to remind you how the Swagger interface display this kind of data. 

Please notice that when a response status has a object associated to it, the format to display the responses is not in a list format.

When **there is *not* a object schema** defined by response status is displayed as list:

![](https://gist.githubusercontent.com/rafaelcaricio/7d5d7b70526770c4088410a5c3518c48/raw/9d76c40a4fb6f4fe53e9492f090f15d33462ab57/cnx_object_schema_not_defined.png)

When **there is a object schema** associated to the response status, the interface shows what is the expected schema:

![](https://gist.githubusercontent.com/rafaelcaricio/7d5d7b70526770c4088410a5c3518c48/raw/9d76c40a4fb6f4fe53e9492f090f15d33462ab57/cnx_object_schema_defined.png)

Could you please let us know more about the bug you found with screenshots?

**Comment by abnerjacobsen** [comment]
@rafaelcaricio thanks, you are right. This is not an issue but an design implementation of the swagger-ui.

this issue can be closed.
