### ISSUE TITLE
Small error in documentation

### ISSUE THREAD

**Issue by the01** [zalando/connexion#265]
### Description
I believe there is a small error in the documentation at [L192](https://github.com/zalando/connexion/blame/master/README.rst#L192) / [L193](https://github.com/zalando/connexion/blame/master/README.rst#L193)

### Expected bahaviour
either

```yaml
     get:
          # Implied operationId: api.foo.get
```

or

```yaml
     search:
          # Implied operationId: api.foo.search
```

### Actual behaviour
```yaml
     get:
          # Implied operationId: api.foo.search
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by rafaelcaricio** [comment]
Thanks for caring to report, but that is not an error. Please notice that the HTTP method "GET" is interpreted here as a kind of search by [it's definition](http://zalando.github.io/restful-api-guidelines/http/Http.html#get) in the context of REST APIs.

**Comment by the01** [comment]
Sorry for the confusion. From the rest of the doc, I thought it had to match the implied operationId..

And thank you, very interesting framework!

**Comment by rafaelcaricio** [comment]
@the01 No, you can have the `operationId` value with whatever name your function have.

Thank you!
