### ISSUE TITLE
Async work with tornado

### ISSUE THREAD

**Issue by masterandrey** [zalando/connexion#267]
If I add @gen.coroutine to generated by connexion request handling method, it doesn't work - break connect with the client, does not return anything.

How to use connexion+tornado anyncronously? gen.sleep for example?
If I yield gen.sleep in the request handler without  @gen.coroutine, it does not wait.

**Comment by hjacobs** [comment]
@masterandrey thanks for your interest in Connexion --- I haven't used Connaxion+Tornado myself (only gevent and uwsgi), so I hope somebody else might help out here...

**Comment by funseiki** [comment]
From Tornado's [documentation](http://www.tornadoweb.org/en/stable/wsgi.html)

> In WSGI mode asynchronous methods are not supported. This means that it is not possible to use AsyncHTTPClient, or the tornado.auth or tornado.websocket modules.

So it doesn't look like this is possible :(

**Comment by rafaelcaricio** [comment]
@funseiki have you tried with the latest Connexion version ([1.0.112](https://github.com/zalando/connexion/releases/tag/1.0.112))?

**Comment by funseiki** [comment]
@rafaelcaricio I haven't, but looking through the `Connexion` source, it looks like `Tornado` is still being instantiated with a WSGI `flask` container. 

Unless `Tornado` changes the way it handles WSGI containers or `Connexion` foregoes the usage of WSGI for a more open-ended approach (async-friendly), I don't see how this would work. 

Here's the bit of `Connexion` code I was looking (from the head of master).
In [app.py](https://github.com/zalando/connexion/blob/master/connexion/app.py):
```
elif self.server == 'tornado':
            try:
                import tornado.wsgi
                import tornado.httpserver
                import tornado.ioloop
            except:
                raise Exception('tornado library not installed')
            wsgi_container = tornado.wsgi.WSGIContainer(self.app)
            http_server = tornado.httpserver.HTTPServer(wsgi_container, **options)
            http_server.listen(self.port)
            logger.info('Listening on port %s..', self.port)
            tornado.ioloop.IOLoop.instance().start()
```

**Comment by rafaelcaricio** [comment]
@funseiki True, and giving it more though we would need to actually do quite some changes in other parts of the Connexion code to support Tornado async. For now the answer is "not possible". :/

**Comment by funseiki** [comment]
@rafaelcaricio Hmm yeah it looks like flask is sprinkled over a few different files. :/. 

On the bright side, it looks like there are really only a few flask methods in app.py that Connexion is utilizing (there are other places that look to be utilizing response/request - related things, but that might be okay). You may be able to get away with using a wrapper/facade around the http server as opposed to importing flask directly and then just use Flask to format request/response messages.

**Comment by soloz** [comment]
Hi,
Any progress on this? As I'm looking to implement API-first async application based on Connexion/Swagger, could @hjacobs or anyone please advise on the amount of effort to integrate Tornado AsyncHTTPClient? I'm happy to help with this.

PS: I think the [README](https://github.com/zalando/connexion/blob/552d1b57b0d4c89c0f0d5e35bef5c074dc0976d9/README.rst) could be a bit misleading, as it says Connexion supports asynchronous apps via Tornado.

**Comment by braco** [comment]
@soloz did you ever find an answer for this?

**Comment by rafaelcaricio** [comment]
I don't have any update on this. But connexion has changes a lot since the time this issue was opened.
