### ISSUE TITLE
Check if a value passed inside body matches pattern described in `definitions`

### ISSUE THREAD

**Issue by phoracek** [zalando/connexion#280]
### Description

According to Ron from swagger's IRC and http://editor.swagger.io/, this is a valid API configuration and it should check if passed value matches given pattern:

```yaml
---
swagger: '2.0'
info:
  version: 1.0.0
  title: Test API
paths:
  /:
    post:
      parameters:
        - in: body
          name: data
          schema:
            $ref: '#/definitions/Test'
      responses:
        200:
          description: OK
definitions:
  Test:
    type: string
    pattern: '^[01]{1,9}$'
```

Unfortunately, connexion does ignore pattern check with such API definition and lets user pass whatever he or she wants.

### Expected behaviour

Check if received values matches pattern defined in `definitions`.

### Actual behaviour

Connexion does not compare received value with pattern.

### Steps to reproduce

Use mentioned config with connexion, start server and call:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '"abcd"' 'http://0.0.0.0:8080/'
```

It should return an error, but it passes data to controller function instead.

**Comment by hjacobs** [comment]
Yes, I think the validation does not work if the body schema itself is a simple `string` type (it works for bodies of type `object`).

**Comment by rafaelcaricio** [comment]
@phoracek What version of Connexion are you using?

I have tried exactly the same code and command you posted here and I cannot reproduce. It works exactly as expects:

```
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '"abcd"' 'http://0.0.0.0/bodytest'
{
  "status": 400,
  "detail": "'abcd' does not match '^[01]{1,9}$'",
  "type": "about:blank",
  "title": "Bad Request"
}
```
Dump of my testing env:
```
$ docker exec -it thirsty_pasteur bash -c "pip freeze"
click==6.6
connexion==1.0.112
Flask==0.11.1
gevent==1.1.2
greenlet==0.4.10
itsdangerous==0.24
Jinja2==2.8
jsonschema==2.5.1
MarkupSafe==0.23
PyYAML==3.12
requests==2.11.1
six==1.10.0
strict-rfc3339==0.7
swagger-spec-validator==2.0.2
Werkzeug==0.11.11
```

**Comment by hjacobs** [comment]
@rafaelcaricio sounds good, I actually did not test myself yet :see_no_evil: :

**Comment by rafaelcaricio** [comment]
The code I used to reproduce can be found in: https://github.com/rafaelcaricio/connexion-example/tree/connexion-280

**Comment by phoracek** [comment]
Thanks for the quick response guys!

Sorry about the noise, while trying to create a reproducer I noticed that the bug is not in connexion, but in http://editor.swagger.io/. If you paste mentioned config there and let it create 'Python Flask' server, it removes the line with 'pattern'.

I will open an issue on https://github.com/swagger-api/swagger-codegen/.
