### ISSUE TITLE
Better handling of configurations

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/connexion#283]
### Description

TL;TR: Move Connexion's configurations to the config attribute of the Flask object.

Currently we have over 10 parameters for the constructor of `connexion.app.App`, `connexion.api.API` classes and `connexion.api.App.add_api`. Most of those parameters are configurations that can be set for a specific API definition or globally in the Connexion server instance. This set of configurations are passed along one-by-one and it was OK for a small set of possible configurations, but now we are constantly increasing the possibilities of how to configure Connexion and adding new options to configure. To permit a more flexible and clean way to move forward whether when adding more features or maintaining the current code base we need to change how we deal with configuration options. ~~Flask already has [a built-in](http://flask.pocoo.org/docs/0.11/config/) configuration handling module and we could make use of that for Connexion.~~

**Comment by rafaelcaricio** [comment]
I started working in a first proposal for that and will be sending a PR as soon as possible.

**Comment by rafaelcaricio** [comment]
To gather feedback from our community I am posting here my proposal of the new style of passing options to Connexion. It will look like:

```python
from connexion import FlaskApp

app = FlaskApp(__name__)
app.add_api(my_opan_api_spec, options={
    'openapi_console_ui_available': True,
    'openapi_console_ui_path': '/console'
})
app.run(port=8080)
```

If you have any comments about that, please reply here.

**Comment by jmcs** [comment]
That doesn't seem better than replacing the current option with 
**kwargs (or **options).

**Comment by rafaelcaricio** [comment]
@jmcs The code base is terrible to maintain with methods/constructors with >10 parameters. It is a effort to make the codebase of Connexion better.

That's is exactly why I am suggesting this approach, so it is extremely simple for users to upgrade. 😉

**Comment by bobh66** [comment]
+1 for **kwargs, **options is good too

**Comment by hjacobs** [comment]
@rafaelcaricio I think @jmcs is proposing to use `**kwargs` in the signature, so you don't have to handle a signature with a large parameter list.

**Comment by rafaelcaricio** [comment]
@hjacobs It does not improve the codebase. We will still have methods expecting many parameters and possible mix of ordering in case you pass them without `abc=1`. Believe me, it is currently a mess and headache to maintain.

**Comment by rafaelcaricio** [comment]
Besides that, every new option we add is a new parameter in multiple methods and constructors.

**Comment by rafaelcaricio** [comment]
Having a heavy bag of data inside a `kwargs` and passing it around is very bad in my opinion. A better approach in is to have an specific parameter `options` where we have information that we know are options for configuring different behaviour of Connexion.

It could be a specific class `ConnexionOptions` to be expected as parameter. But it would be bad to ask for users to know how to manipulate one more custom class to configure Connexion that's why using a simple `dict` sounds better.

Do you still think `**kwargs` is the way to go?

**Comment by danballance** [comment]
I agree @rafaelcaricio - this has been a headache for me adding a couple of configuration options recently. I needed to access these options inside one of the decorators and it felt like a bad code smell to me adding yet more options to those constructors and passing them all through to other objects used internally.

However, If we are decoupling Flask, shouldn't we be looking for a non-Flask solution to application wide configurations?

Whatever approach is ultimately agreed on I would rather see us move towards some kind of configuration file where lots of different configuration options can be managed. This has the additional benefit of meaning that a set of options used to bootstrap an application an be kept in a configuration file that is not under version control and separate from the python file that starts Connexion. I find this useful when running applications in different environments such as developer, jenkins, staging, production etc.

**Comment by rafaelcaricio** [comment]
@danballance I first opened this issue on Sep 10, 2016 so this decoupling was still not on the plate. So the initial description of this issue is outdated.

My first attempt to fix this was expecting a configuration file (PR #367). Although, I have realised later that expecting configuration files, environment variables, etc is a decision of whoever is writing the applications. So I gave up on that idea.

Now decided to go on the direction of using basic Python data structures (in this case `dict`) to expect the options to be present. That way we allow developers to use whatever configuration loading library they want.

**Comment by danballance** [comment]
I see @rafaelcaricio  - it's true that I already have implemented my own configuration file in my own application.

**Comment by jasonrhaas** [comment]
@rafaelcaricio Does this new approach subclass the actual `Flask` class so we can use the built in `.config` method of the instance?

I use the `.config` method to keep track of my different Flask configurations (test, dev, prod), but currently connexion does not seem to support it.

For example,
```
        app = connexion.FlaskApp(__name__)
        app.config.update(defaults)
```

Gives this:
```
AttributeError: 'FlaskApp' object has no attribute 'config'
```

**Comment by jasonrhaas** [comment]
In looking at the code, it appears that `connexion.FlaskApp().app` is an instance of `flask.Flask`.

**Comment by hjacobs** [comment]
@jasonrhaas yes, this should work.

**Comment by rafaelcaricio** [comment]
@jasonrhaas As @hjacobs pointed out already. It should work fine if you use `connexion.FlaskApp().app`.

**Comment by RobbeSneyders** [comment]
Closing this since #436 was merged to address this.
