### ISSUE TITLE
basePath: / makes endpoints unreachable

### ISSUE THREAD

**Issue by RichardBrown384** [zalando/connexion#290]
### Description
Using a forward slash as the basePath in a swagger API definition makes endpoints unreachable.

```
basePath: /
paths:
   /myendpoint:
       get:
...

```

### Expected behaviour

Endpoints get added as DEBUG:connexion.api:Adding /myendpoint...

GET request returns 200

### Actual behaviour

Endpoints get added as DEBUG:connexion.api:Adding //myendpoint...

GET request returns 404

### Steps to reproduce
Set the basePath to '/' in the swagger definition.

**Comment by rafaelcaricio** [comment]
Thanks for reporting that. As a temporary workaround simply does not set the `basePath` in case it is the default "/".
