### ISSUE TITLE
Support for mocking API based on spec

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/connexion#292]
### Description

Recently we added support for applying a stub to unimplemented operations (https://github.com/zalando/connexion/pull/278). Following that line, I think would be interesting to add support for automatic mocking of a API based on the specification.

This mocking feature would work as the stub, only activated to not implemented operations. This is powerful because allows a broader use case for Connexion.

- Developers would get a better insight on how the API should look like after complete implementation;
- Frontend engineers could mock easily all APIs necessary to develop the client UI;
- Mobile and backend peers would be able to mock dependent services for testing;

### Expected bahaviour

```python
app = connexion.Api(__name__)
app.add_api("my_api.yaml", mock_operations=True)
```

and 

```bash
$ connexion run my_api.yaml --mock
```

**Comment by hjacobs** [comment]
Mocking should return example data (["examples" property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject)) as specified in the OpenAPI spec.
