### ISSUE TITLE
Support app.add_api() with API-dictionary as an alternative to file path

### ISSUE THREAD

**Issue by phoracek** [zalando/connexion#296]
### Description

It would be handy to support `app.add_api()` with parsed API as a parameter as an alternative to file path. It can be used when the application does some additional changes on the API and doesn't want to save it again in a temporary file.
### Expected bahaviour

``` python
api = {...}  # yaml.load(file)
app.add_api(api)
```
### Actual behaviour

`add_api()` accepts only path to file with API definition.

**Comment by hjacobs** [comment]
I think this is a good suggestion. Connexion should not purely rely on a file-based API.

**Comment by DDEFISHER** [comment]
I would like to work on this if no one else has started if that is okay.

**Comment by rafaelcaricio** [comment]
@DDEFISHER it is ok to work on it. Just send the PR whenever you are ready. 😃
