### ISSUE TITLE
Blueprint routing

### ISSUE THREAD

**Issue by ibigpapa** [zalando/connexion#299]
### Description
Enable Blueprint routing ie
bp = Blueprint('bp', _ _ name _ _, url_prefix='/bp')

@bp.route('/')
bp_get():
    code here

### Actual behaviour
Not sure if connexion can accomodate a blueprint

### Additional info:
if we can example would be great.

**Comment by rafaelcaricio** [comment]
@ibigpapa Connexion is based on Flask. So you can use Flask routing directly additionally to your OpenAPI routes. Example: https://github.com/zalando/lizzy/blob/master/lizzy/service.py#L29-L42

**Comment by sxslex** [comment]
"""Implement load api from swagger using template import yam."""
    import yaml
    import connexion
    from jinja2 import FileSystemLoader
    from jinja2.environment import Environment
    
    
    def connexion_register_blueprint(app, swagger_file, **kwargs):
        con = connexion.FlaskApp("api", app.instance_path)
        env = Environment(loader=FileSystemLoader(
            app.config.get('SWAGGER_ROOT_TEMPLATE') or
            app.config['PROJECT_ROOT']
        ))
        swagger_string = env.get_template(swagger_file).render(**kwargs)
        specification = yaml.safe_load(swagger_string)
        api = super(connexion.FlaskApp, con).add_api(specification, **kwargs)
        app.register_blueprint(api.blueprint)
        return api
    
    ...
    connexion_register_blueprint(app, 'api/v1/swagger/main.yaml')
    ...
