### ISSUE TITLE
204 responses have wrong Content-Type

### ISSUE THREAD

**Issue by jakul** [zalando/connexion#321]
### Description
HTTP 204 responses have the wrong `Content-Type`.

### Expected bahaviour
`Content-Type` is `application/json`

### Actual behaviour

`Content-Type` is `text/html; charset=utf-8`

### Steps to reproduce
* Create a DELETE endpoint
* Send a request to it and check the response headers

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
$ pip show connexion | grep "^Version\:"
Version: 1.0.129
$ python --version
Python 2.7.9
```

**Comment by zbyte64** [comment]
Interestingly it is now sending "application/json"
