### ISSUE TITLE
Resolving partial YAML files into a single files

### ISSUE THREAD

**Issue by mcorbe** [zalando/connexion#338]
Would be nice to be able to split and reuse definitions and / or info across APIs. Ideally I would like to be able to do something like this:
http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html

Did I miss something in the doc ? (I did not see anything like this in the docs so far)

Looking forward to your opinion and ideas on the topic.

**Comment by rafaelcaricio** [comment]
This is a duplication of #254. Currently Connexion does not support that. But we would happy merge a PR that covers this feature. Please follow up with the discussion at #254.
