### ISSUE TITLE
Internal Go CD pipeline broken since #316 (no releases)

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#341]
Our Zalando internal Go CD pipeline (used for releasing) is broken since #316, therefore we did not release any new Connexion version for 28 days.

**Comment by hjacobs** [comment]
Our pipeline still assumes to have `requirements.txt`.

**Comment by rafaelcaricio** [comment]
I think we should consider https://docs.travis-ci.com/user/deployment/pypi/ for releases.

**Comment by dtkav** [comment]
Closing this because it's very old. Please re-open if I made a mistake!
