### ISSUE TITLE
Pip install issue in virtual environment? (python 2.7)

### ISSUE THREAD

**Issue by danballance** [zalando/connexion#345]
### Description
Has anything changed relatively recently with the pip install process? I'm trying to install within a virtual environment and without requiring sudo.

### Expected bahaviour
Package installs without without error.

### Actual behaviour
Install dies with error:

distutils.errors.DistutilsError: Setup script exited with error: could not create '/usr/local/share/man/man1': Permission denied

### Steps to reproduce
virtualenv --no-site-packages env2
. env2/bin/activate
pip install connexion

### Additional info:
So the install seems to be looking outside of virtual environment for this file:
/usr/local/share/man/man1/flake8.1

If it doesn't find this. then it doesn't have the permissions to create it, and bombs out. My workaround just then was to do a global install first, outside of the virtual env, with:

sudo pip install connexion

and then go back into my virtual env and install again - this time the file is found and the install completes.

This issue seems like something introduced in the last few weeks. Is it just my systems or can others verify this? (I've had the same issue on my local dev machine - Ubuntu 16.04 and my Jenkins server Ubuntu 14.04)

thanks in advance,

Dan

**Comment by jmcs** [comment]
I can't reproduce it:

    $ virtualenv --no-site-packages env2
    $ . env2/bin/activate
    $ pip install connexion
    Collecting connexion
    Downloading connexion-1.0.129.tar.gz (971kB)
        100% |████████████████████████████████| 972kB 1.6MB/s 
    Collecting jsonschema>=2.5.1 (from connexion)
      Using cached jsonschema-2.5.1-py2.py3-none-any.whl
    Collecting flask>=0.10.1 (from connexion)
      Using cached Flask-0.11.1-py2.py3-none-any.whl
    Collecting PyYAML>=3.11 (from connexion)
    Collecting requests>=2.9.1 (from connexion)
      Using cached requests-2.12.1-py2.py3-none-any.whl
    Collecting six>=1.7 (from connexion)
      Using cached six-1.10.0-py2.py3-none-any.whl
    Collecting strict-rfc3339>=0.6 (from connexion)
    Collecting swagger_spec_validator>=2.0.2 (from connexion)
      Using cached swagger_spec_validator-2.0.2-py2-none-any.whl
    Collecting clickclick>=1.2 (from connexion)
      Downloading clickclick-1.2.1.tar.gz
    Collecting pathlib (from connexion)
    Collecting functools32; python_version == "2.7" (from jsonschema>=2.5.1->connexion)
    Collecting itsdangerous>=0.21 (from flask>=0.10.1->connexion)
    Collecting click>=2.0 (from flask>=0.10.1->connexion)
    Collecting Werkzeug>=0.7 (from flask>=0.10.1->connexion)
      Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
    Collecting Jinja2>=2.4 (from flask>=0.10.1->connexion)
      Using cached Jinja2-2.8-py2.py3-none-any.whl
    Requirement already satisfied: setuptools in ./env2/lib/python2.7/site-packages (from swagger_spec_validator>=2.0.2->connexion)
    Collecting MarkupSafe (from Jinja2>=2.4->flask>=0.10.1->connexion)
    Building wheels for collected packages: connexion, clickclick
      Running setup.py bdist_wheel for connexion ... done
      Stored in directory:     /home/jsantos/.cache/pip/wheels/9a/03/77/b0dc5072717865f2a19f788f6f31830f3b0e866afff6f5a2df
      Running setup.py bdist_wheel for clickclick ... done
      Stored in directory: /home/jsantos/.cache/pip/wheels/9f/00/93/3f0d7f7045b4fbea9ab05a1656fdfb03425d768066825f5af1
    Successfully built connexion clickclick
    Installing collected packages: functools32, jsonschema, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, flask, PyYAML, requests, six, strict-rfc3339, swagger-spec-validator, clickclick, pathlib, connexion
    Successfully installed Jinja2-2.8 MarkupSafe-0.23 PyYAML-3.12 Werkzeug-0.11.11 click-6.6 clickclick-1.2.1 connexion-1.0.129 flask-0.11.1 functools32-3.2.3.post2 itsdangerous-0.24 jsonschema-2.5.1 pathlib-1.0.1 requests-2.12.1 six-1.10.0 strict-rfc3339-0.7 swagger-spec-validator-2.0.2

**Comment by danballance** [comment]
Thanks for taking a look. I seem unable to recreate this error now as well. It's strange because I had the same issue on the same day on two different Ubuntu distributions. It's working for me now though so I will close.
