### ISSUE TITLE
Trailing slash endpoint routing returns 404

### ISSUE THREAD

**Issue by tomas-fp** [zalando/connexion#346]
### Description

It's well-known that most HTTP routers deals with the trailing slash accordingly, matching both `/foo` or `/foo/` path expressions.

I'm not sure if this was already supported and can be easily enabled programmatically.

### Expected behaviour

Matching the route and reply with a `301` status and redirect it accordingly to `/foo` (however redirection can be optional).

### Actual behaviour

`404` status code is returned instead.

### Steps to reproduce

Just make an HTTP request against a valid endpoint in a connext+Flask app adding a final slash.

### Additional info:

- `python 3.5.2`
- `connexion version 1.0.129`

**Comment by tomas-fp** [comment]
Yes, I'd prefer do not redirecting requests, but some implementations did it.

**Comment by tomas-fp** [comment]
Apparently Flask, based on Werkzeug’s routing module, does a redirection only if a trailing slash is present, otherwise, the expected behaviour would be a 404 response error, as we have now. 
See section "Unique URLs / Redirection Behavior":
http://flask.pocoo.org/docs/0.11/quickstart/#variable-rules

I suspect that `connexion` should register an additional route that matches the same route with a trailing slash, but I think that behaviour should not be supported by default, instead, it should be explicitly enabled, perhaps via a custom `x-*` directive at OpenAPI spec endpoint level.

What do you guys think?

**Comment by tomas-fp** [comment]
Moreover, if we agree about an implementation strategy, I'm very open to provide a PR with the enhancement.

**Comment by akhilbatra898** [comment]
Any update on this?

**Comment by rafaelcaricio** [comment]
We register the urls in the Flask app router exactly as defined in the provided OpenAPI specification. So it works as described in the Flask documentation.

I don't understand why we should change Connexion to do differently. Although I am open to understand better why this should be changed.

**Comment by tomas-fp** [comment]
One core reason would be for API UX quality reasons. Most HTTP API are still consumed by humans as the entry point and humans are more prone to make mistakes, such as adding a trailing slash. If you're using a web browser, the history is going.

This is not an isolated issue: the majority of HTTP routers/path multiplexers fixes the trailing slash transparently for the developer.

I don't think forcing people adding boilerplate within their Swagger specs is going to help here.

Let's make things more human friendly :)

**Comment by rafaelcaricio** [comment]
So the change would be If the URL ends without trailing slash and the operation is `GET` we append an `/` before registering the path in the Flask app router?

**Comment by tomas-fp** [comment]
I think it can be as simple as: 
- Register **any endpoint route** for **any HTTP verb** within Flask app router for both trailing and non-trailing slash.

Also supporting the following conditions:
- If the route defined in the Swagger spec already has a trailing slash (probably due to human mistake), normalize it first and process it accordingly as described above.
- DO NOT support HTTP redirection at all.

**Comment by akhilbatra898** [comment]
The issue also comes when we create a uniy test using app.app.test_client.
When u request /name instead of /name/ 
It gives 301 when unit test need to test the outouy from same endpoint.

**Comment by akhilbatra898** [comment]
And I tried using flask strict_slash =  False.
In connexion.app.app.url_mapping.strict_slash.

Its not working

**Comment by JohnPaton** [comment]
I agree that `connexion` should at the very least respect the `app.app.url_map.strict_slashes` flag. I would actually argue that `strict_slashes` should be false by default; see e.g. [Zalando's RESTful API Guidelines](https://opensource.zalando.com/restful-api-guidelines/zalando-guidelines.pdf):
> **Must: Avoid Trailing Slashes**
> The trailing slash must not have specific semantics. Resource paths must deliver the same results
whether they have the trailing slash or not.

Is it not possible to follow this guideline with `connexion`?
