### ISSUE TITLE
questions on mapping endpoints to python functions

### ISSUE THREAD

**Issue by lmeroc** [zalando/connexion#354]
### Description
hello,
       I have had a basic understanding of this tool, but I have a question,why we need to map the endpoints to python functions? I can understand swagger generate sepcification from the api to release programmers from file burder, but i don't know the purpose to map endponts to functions? what have you down after the mapping?
      Thank you for your time!

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by rafaelcaricio** [comment]
You will want to map the endpoints to functions to be able to actually have the logic of your API implemented. If you don't need that, your API sounds not so useful.
