### ISSUE TITLE
Incorrect set http response data when returning flask.Response objects

### ISSUE THREAD

**Issue by heyglen** [zalando/connexion#356]
### Description

Incorrect set http response data when returning flask.Response objects

### Expected bahaviour

From the [documentation](https://connexion.readthedocs.io/en/latest/response.html#response-serialization):

> "If the endpoint returns a Response object this response will be used as is."

### Actual behaviour

The response is parsed in connexion.decorators.decorator.BaseDecorator.get_full_response() and the [response object itself is mistakenly set as the response's data instead of response.data](https://github.com/zalando/connexion/blob/master/connexion/decorators/decorator.py#L27):

This later throws a JSON serialize error when trying to [JSON serialize the data variable](https://github.com/zalando/connexion/blob/master/connexion/decorators/response.py#L47) (mistaken Response object)

### Additional info:

Output of the commands:

- `python --version`
Python 2.7.12
- `pip show connexion | grep "^Version\:"`
Version: 1.0.129

**Comment by heyglen** [comment]
I got it to work by [replacing these lines](https://github.com/zalando/connexion/blob/master/connexion/decorators/decorator.py#L27-L29)

with this:

```python
response = data
data = response.data
status_code = response.status_code
headers = response.headers
```

**Comment by rafaelcaricio** [comment]
@heyglen Thank you for reporting it.
