### ISSUE TITLE
oauth2 client_id fixed

### ISSUE THREAD

**Issue by pingf** [zalando/connexion#361]
### Description

the swagger ui only generate the fixed client_id & client_secret for oauth2

### Expected behaviour

make me able to modify the client_id & client_secret from the init config or the yaml file

### Actual behaviour

because in the index.html for swagger ui, they are all fixed

```html
   if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              clientSecret: "your-client-secret-if-required",
              realm: "your-realms",
              appName: "your-app-name",
              scopeSeparator: " ",
              additionalQueryStringParams: {}
            });
          }
```

### Steps to reproduce

just use oauth2

### Additional info:

Output of the commands:

- `python --version`

Python 3.5.2

- `pip show connexion | grep "^Version\:"`

Version: 1.0.129

**Comment by rafaelcaricio** [comment]
Related issue #406

**Comment by dtkav** [comment]
swagger-ui is no longer vendored in connexion, and relies on the swagger-ui-bundle package.
