### ISSUE TITLE
Type for money (decimal)

### ISSUE THREAD

**Issue by worldmind** [zalando/connexion#376]
Now connexion cast number to float, but for money parameters needed decimal type

**Comment by rafaelcaricio** [comment]
@worldmind please take a look at http://connexion.readthedocs.io/en/latest/cookbook.html#custom-type-format . Let me know if it does not help.

**Comment by worldmind** [comment]
If i understood right is only part of solution - it is only about validation, but user shoud be manually convert goted string to decimal type for using it.
I think it framework job - it must return value with right type.

**Comment by rafaelcaricio** [comment]
I think if we would do this in Connexion we would need to carry out all the responsibility to handle precision, etc. Not sure how we would tackle this issue.

**Comment by rafaelcaricio** [comment]
Also OpenAPI spec does not provide the `decimal` type.

**Comment by rafaelcaricio** [comment]
Due to no support for decimals in the OpenAPI spec, I think this issue should be closed. You can support decimal in your API, but you need to implement yourself the conversion.

**Comment by worldmind** [comment]
Create https://github.com/OAI/OpenAPI-Specification/issues/889

**Comment by worldmind** [comment]
As I understood they think that frameworks must create decimal values from `type: number, format: decimal` and some people do it https://github.com/OAI/OpenAPI-Specification/issues/607#issuecomment-200267864
They move formats from specification to separate registry in https://github.com/OAI/OpenAPI-Specification/issues/845 and add format decimal in https://github.com/OAI/OpenAPI-Specification/issues/607
I think that will be not bad if connexion will support format decimal and convert `type: number, format: decimal` to [Decimal](https://docs.python.org/3/library/decimal.html) type.
