### ISSUE TITLE
Incorrect Mimetype/Content-Type Handling

### ISSUE THREAD

**Issue by patrickw276** [zalando/connexion#381]
I think there may be a bug in Content-Type/Mimetype handling.

If an operation has a single `produces` type defined in swagger and the implementation returns a flask Response object, both the swagger `produces` value and the Response object's `content-type` are returned. Example:

```yaml
operationId: app.get_greeting
produces:
  - text/plain
```

with the implementation:

```python
def post_greeting(name):
    response = flask.make_response('Hello {}\n'.format(name))
    response.headers['content-type'] = 'text/plain'
    response.mimetype = 'text/plain'
    return response
```

`curl -v` request to the route returns:

```
< Content-Type: text/plain; charset=utf-8
< Content-Length: 11
< Content-Type: text/plain; charset=utf-8
< Content-Length: 11
```

If you don't specifically set the Response object's content-type or mimetype, then the following is returned. 

```
< Content-Type: text/plain; charset=utf-8
< Content-Length: 11
< Content-Type: text/html; charset=utf-8
< Content-Length: 11
```

This is a bigger issue when an operation has multiple `produces` values. If you use the same code as above with an added `application/json` to the `produces` values, `application/json` is always returned in addition to `text/plain`. 

```
< Content-Type: application/json
< Content-Length: 11
< Content-Type: text/plain; charset=utf-8
< Content-Length: 11
```

I suspect that the code causing this issue is in `connexion/decorator.py::BeginOfRequestLifecycleDecorator.get_response_container`.

**Comment by hjacobs** [comment]
@patrickw276 thanks for reporting, I guess we introduced it with #365.

cc @rafaelcaricio
