### ISSUE TITLE
Support all JSON schema validation and parsing attributes

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#39]
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject

Currently missing:

* allowEmptyValue
* default
* maximum
* exclusiveMaximum
* minimum
* exclusiveMinimum
* maxLength
* minLength
* pattern
* maxItems
* minItems
* uniqueItems
* enum
* multipleOf
* maxProperties
* minProperties
* allOf
* additionalProperties
* discriminator

(striked through entries are already done)

**Comment by hjacobs** [comment]
The following properties are now supported:

* pattern
* maximum
* minimum

**Comment by hjacobs** [comment]
The following properties are now additionally supported:
* minLength
* maxLength
* enum

**Comment by jmcs** [comment]
Isn't this fixed by #108 and #114 ?

**Comment by rafaelcaricio** [comment]
Can we close this issue?

**Comment by hjacobs** [comment]
@rafaelcaricio I guess we need to go through all properties defined in Swagger Spec and check :smirk:

**Comment by jmcs** [comment]
Anything missing here is now a bug on jsonschema and not in connexion.
