### ISSUE TITLE
Running Connexion as an extension

### ISSUE THREAD

**Issue by tarekziade** [zalando/connexion#393]
It would be nice to be able to pass an existing Flask app instance to connexion.

A use case is a Flask application that implements other stuff than swagger-based API endpoints.

This is my lame attempt to do it: https://gist.github.com/tarekziade/595f003c0a9b9aa0934f21b814717441

It "works" but I think we'd need something self-contained to the Blueprint, and I was not able to do that kind of integration.

**Comment by hjacobs** [comment]
You should be able to use the `Api` class of Connexion without the `App`: https://github.com/zalando/connexion/blob/master/connexion/api.py#L57

**Comment by tarekziade** [comment]
Yes I was able to do it eventually. I updated the gist. Thanks!

**Comment by jasonrhaas** [comment]
Note that the way to do this as of the version 1.1.15 is `from connexion import Api`
