### ISSUE TITLE
Downloads not shown in swagger ui

### ISSUE THREAD

**Issue by thedylman** [zalando/connexion#399]
### Description
The swagger ui version 2.2.5 has incomplete support for downloads via the ui.

### Expected behaviour
In the _Response Body_ section there should be a download link in the swagger ui.

### Actual behaviour
No download link and progress animation does not stop.

### Additional info:
Output of the commands:
- `python --version` == 3.5.2
- `pip show connexion | grep "^Version\:"` == 1.1.4

### Possible fix
Upgrading the swagger ui to version 2.2.8 in the vendor directory with `./update.sh 2.2.8`.
This fixes the issue for me.

Should I send a pull request of would you rather update it yourself?

**Comment by rafaelcaricio** [comment]
Related issue #406

**Comment by dtkav** [comment]
swagger-ui is no longer vendored, and has been updated.
I think this ticket is no longer relevant, but feel free to re-open if i got it wrong.
