### ISSUE TITLE
swagger-ui 3.x support

### ISSUE THREAD

**Issue by vimalloc** [zalando/connexion#418]
swagger-ui 3.x recently dropped. It has enough changes that the ```update.sh``` script cannot automatically upgrade it. It would be cool if we could get this in here.

**Comment by rafaelcaricio** [comment]
Related to #406

**Comment by dtkav** [comment]
swagger-ui 3.x is now available in Connexion 2.0 through the swagger-ui-bundle package.
If you are using an openapi 3 specification it will automatically use swagger-ui v3.x.
