### ISSUE TITLE
App has no attribute config

### ISSUE THREAD

**Issue by bioslikk** [zalando/connexion#438]
### Description

I want to save a string in the app object like in flask

### Expected behaviour
I expect to save it like
app.config['UPLOAD_FOLDER'] = 'some/path/name_of_folder'

### Actual behaviour

AttributeError: 'FlaskApp' object has no attribute 'config'

### Steps to reproduce

app = connexion.App(__name__)
app.add_api('swagger.yaml')
app.config['UPLOAD_FOLDER'] = 'some/path/name_of_folder'

### Additional info:

Output of the commands:

- Python 3.4.2

- connexion -> Version: 1.1.9

**Comment by rafaelcaricio** [comment]
You can access it via "connexion.App().app"

**Comment by bioslikk** [comment]
Thank you, so the command is:
->$ app.app.config['UPLOAD_FOLDER'] = 'some/path/name_of_folder'

**Comment by randyesq** [comment]
So how do you access the `UPLOAD_FOLDER` config value in, say, a controller?

**Comment by djhaskin987** [comment]
@randyesq I did this successfully from a controller file, found under `<project>/controllers/default_controller.py`:

```python
from flask import current_app

def read(limit=1):
    return current_app.config['FOO_BAR']
```
