### ISSUE TITLE
[question] access to parsed swagger spec [solved]

### ISSUE THREAD

**Issue by brightwrite-admin** [zalando/connexion#444]
is here a way to access parsed swagger spec? i know we can pass params from outside, but what if I want to access some info from the spec?

**Comment by rafaelcaricio** [comment]
@brightwrite-admin Currently there is no way to access it.

**Comment by brightwrite-admin** [comment]
@rafaelcaricio Thanks for your answer. I can parse swagger spec one more time. Not an issue.

**Comment by jmcs** [comment]
The API object (returned by `add_api`) has a `specification` property. @brightwrite-admin is that what you need?

**Comment by brightwrite-admin** [comment]
@jmcs Thanks! Yes that's it :)
