### ISSUE TITLE
Relation of connexion and swagger code generator

### ISSUE THREAD

**Issue by unuseless** [zalando/connexion#446]
### Description
Connexion can be used standalone, or you can use the online swagger code generator at http://editor.swagger.io/ . The online generator generates a bunch of files for use with connexion.

My questions are:
Why would you use the code generator at http://editor.swagger.io/ instead of connexion directly?

Can you explain the difference in use case?

**Comment by roman-telepathy-ai** [comment]
I follow mixed approach: models are generated, but the rest of code is custom. Since I dont like the way swagger-codegen gives me the project.

**Comment by RobbeSneyders** [comment]
Connexion can be used independently. 
The code generator generates a code skeleton for a Connexion application based on your spec. You can use it to speed up your development.
