### ISSUE TITLE
cannot import name 'JSONEncoder' 1.1.4 -> 1.1.9

### ISSUE THREAD

**Issue by mohabusama** [zalando/connexion#453]
### Description

Upgrading from 1.1.4 to 1.1.9 leads to:

```python
from connexion.decorators.produces import JSONEncoder 
cannot import name 'JSONEncoder'
```

### Expected behaviour

To work, since there is no Major version upgrade.

### Actual behaviour

``cannot import name 'JSONEncoder'``

### Steps to reproduce

```python
from connexion.decorators.produces import JSONEncoder 
cannot import name 'JSONEncoder'
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"` 
`Version: 1.1.9`

**Comment by hjacobs** [comment]
Thanks for reporting this breaking change!

**Comment by kinow** [comment]
Here's where it happened https://github.com/zalando/connexion/commit/7ffa3d4221f1e2aaff819a651758667f558964e3

Unfortunately the commit is quite fat. I think maybe related to this line: "moved the jsonifier from produces to flask api;"? Not really much to be fixed, perhaps someone could simply cut a 1.2 version, or just add a note that unfortunately there was a breaking change (I remember seeing a recent comment in one Apache Software Foundation Java project, from Commons)., and then close this ticket?

**Comment by mohabusama** [comment]
Was/is there a reason for not directing the refactoring/flask-decoupling effort to version 2.x?

**Comment by rmundkowsky** [comment]
Does this work until you fix things?

from connexion.apps.flask_app import FlaskJSONEncoder

class JSONEncoder(FlaskJSONEncoder):
...

**Comment by rafaelcaricio** [comment]
As @rmundkowsky pointed out, this just moved to another file. This object should not be used directly outside Connexion code itself. That's why this change was not added to any release notes.
