### ISSUE TITLE
Question: is there a guide to running the tests?

### ISSUE THREAD

**Issue by MikeRalphson** [zalando/connexion#455]
### Description

Re: #454 I'd like to be able to run the test suite locally and update it

### Expected behaviour

Test suite passes on unmodified code

### Actual behaviour

```
ImportError while importing test module 'D:\python\connexion\tests\test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_api.py:11: in <module>
    from connexion.apis.abstract import canonical_base_path
E   ImportError: cannot import name 'canonical_base_path'
_____________________ ERROR collecting tests/test_cli.py ______________________
ImportError while importing test module 'D:\python\connexion\tests\test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_cli.py:10: in <module>
    from mock import MagicMock
E   ImportError: No module named 'mock'
___________________ E
```

### Steps to reproduce

Have run setup.py and installed pytest
`pytest` in connexion directory

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

Python 3.5.2 
Version: 1.1.9

Windows 10.

**Comment by rafaelcaricio** [comment]
You need `tox` run the tests:
```
pip install tox
```
Then run:
```
tox
```
That is all. But I would recommend you to do that in a clean Python virtual environment (`python -m venv`).

**Comment by MikeRalphson** [comment]
@rafaelcaricio Many thanks!

**Comment by MikeRalphson** [comment]
tox output on windows is unreadable, possibly due to this bug https://github.com/tox-dev/tox/issues/250 - helps to tee the output
