### ISSUE TITLE
access to custom vendor extension properties

### ISSUE THREAD

**Issue by rog555** [zalando/connexion#460]
Hello, is there any way to access custom vendor extension properties, or else the swagger doc for the current operation (or even whole swagger doc) ?

eg:

```
paths:
  /foo/{id}:
    get:
      x-foo: bar
      operationId: api.get_foo
      parameters:
      - in: path
        name: id
      responses:
        200:
          description: OK
```

```
def get_foo(id):
   x_foo = something.get("x-foo")
   assert x_foo == "bar"
```

**Comment by hjacobs** [comment]
The API object is your friend, see answer on #444

**Comment by rog555** [comment]
Great, thanks for the hint. have managed to make it work with @before_request and flask.g to store/retrieve the during the operation.
