### ISSUE TITLE
return value-format of endpoints

### ISSUE THREAD

**Issue by roman-telepathy-ai** [zalando/connexion#466]
### Description
What should / can be the return value of an endpoint?

E.g.:
```
def hello():
  return {'greet': 'hello'}, 200
```
The return value is a tuple with data + status code.

### Questions
- is the return tuple passed to the `flask.Response(...)` as arguments?
- how to add custom headers, mimetypes, etc to the response? (if the response insternally not handled as flask.Response)
- or should I use standard `flask.Response(response, status, headers, mimetype, content_type, direct_passthrough)` instead by default?

Thanks in advance!

**Comment by vimalloc** [comment]
The possible values when using flask are here:
https://github.com/zalando/connexion/blob/master/connexion/apis/flask_api.py#L177

It looks like you can return a flask response, a tuple with a flask response and status_code and/or headers, a tuple of (data, status_code, headers), a tuple of (data, status_code), or just the data.

**Comment by roman-telepathy-ai** [comment]
thanks! got it.
