### ISSUE TITLE
Client SDK examples?

### ISSUE THREAD

**Issue by JHibbard** [zalando/connexion#468]
Are there examples/documentation for using the swagger-codegen python client for connexion servers?

**Comment by roman-telepathy-ai** [comment]
client works out of the box.
with codegen you get both client and server.
steps:
- start server
- add a test case to generated clients tests and simply use generated api

Example:
```
from microservice_disney_client import Hero
from microservice_disney_client import DisneyApi
h = Hero('MickeyMouse')
a = DisneyApi()
r = a.microservice_disney_api_hero_get(s)
print(r)
```

**Comment by JHibbard** [comment]
If your spec doesn't define the host or basePath, how would you configure the client?  Is there a list of what configuration values need to be set for the client to work properly or a way to see the http request generated by the client for troubleshooting purposes?

I'm having trouble setting up the client in this situation.  Thank you!

**Comment by roman-telepathy-ai** [comment]
the host and port are defaults in your YAML. When client is generated, it uses these default values.
But you can change them, depending where you deploy your service.
```
from microservice_disney_client import Hero
from microservice_disney_client import DisneyApi
from microservice_disney_client import DisneyApiClient
h = Hero('MickeyMouse')
c = DisneyApiClient(host='0.0.0.0:8080')
a = DisneyApi(c)
r = a.microservice_disney_api_hero_get(h)
print(r)
```

**Comment by JHibbard** [comment]
Thank you, this was very helpful!  The only gotcha I found was that the 'host' parameter to an API client is actually the 'host'+'basePath' from the swagger spec:

    from microservice_disney_client import DisneyApi
    from microservice_disney_client import DisneyApiClient

    # host = host + basePath
    c = DisneyApiClient(host='0.0.0.0:8080/v0')
    a = DisneyApi(c)
