### ISSUE TITLE
Requests from remote client return 404

### ISSUE THREAD

**Issue by remintz** [zalando/connexion#471]
### Description
Application runs fine when client is on same computer and access is done using "localhost" on the URL. When client is on a remote computer OR if the client is on the same computer but access is done using "127.0.0.1" the application returns the 404 message below for the previously running url paths (including /ui)

```
{
  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}
```
I've tested using both app.run(host='0.0.0.0') and app.run(host='127.0.0.1'). 

I'm using flask.

I'm running using "python app.py".

Any help would be appreciated.

Thanks

Output of the commands:

> python --version
Python 3.6.1

> pip show connexion
Name: connexion
Version: 1.1.9
Summary: Connexion - API first applications with OpenAPI/Swagger and Flask
Home-page: https://github.com/zalando/connexion
Author: Zalando SE
Author-email: UNKNOWN
License: Apache License Version 2.0
Requires: swagger-spec-validator, inflection, flask, clickclick, PyYAML, requests, jsonschema, six

**Comment by hjacobs** [comment]
Could you provide some more information/details? The described issue sounds a bit weird to me and I have no good clue on how to help you. Maybe try to reproduce the problem with a minimal set of code/swagger and put this somewhere public (so we can reproduce the problem too).

**Comment by remintz** [comment]
Thanks @hjacobs. I've created a minimal app to demonstrate this.

The source code is published at https://github.com/remintz/connexion-test.git

You may check it behavior at this URL: http://34.203.30.75:8080/ui

No matter what request I send it always returns the same error.

The application console shows

INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO:werkzeug:186.213.122.244 - - [23/Jun/2017 20:33:58] "GET /ui HTTP/1.1" 404 -

Tested with both .../ui and .../ui/

Thanks

**Comment by remintz** [comment]
Sorry... closed by mistake

**Comment by hjacobs** [comment]
@remintz see https://github.com/remintz/connexion-test/pull/1 . You are overwriting the `SERVER_NAME` and this causes the problem. I'm not sure why you do it (also other configs are not necessary IMHO).

**Comment by remintz** [comment]
It worked! Thanks a lot @hjacobs ! This code came from some sample I've found on internet. I'll be cleaning it up.
