### ISSUE TITLE
Query and Path Parameter Validation

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#48]
Only "body" parameters are validated right now, we need to validate other parameters ("path", "query") too.

**Comment by hjacobs** [comment]
Basic query parameter validation is now part of Connexion 0.9.1, I will add basic path parameter validation next.

**Comment by cansik** [comment]
:+1:

**Comment by hjacobs** [comment]
Path and header parameters are now also validated in Connexion 0.9.2.
Note that some less common Swagger validation rules are not yet implemented.

**Comment by samuelvonstachelski** [comment]
:+1:

**Comment by samuelvonstachelski** [comment]
I get the following exception on all path parameters even though the swagger editor tells me, that my file is correct...

    ERROR:connexion.api:Failed to add operation for PARAMETERS /containers/<id>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/connexion/api.py", line 131, in add_paths
        self.add_operation(method, path, endpoint)
      File "/usr/local/lib/python2.7/dist-packages/connexion/api.py", line 112, in add_operation
        parameter_definitions=self.parameter_definitions)
      File "/usr/local/lib/python2.7/dist-packages/connexion/operation.py", line 72, in __init__
        self.operation_id = operation['operationId']
    TypeError: list indices must be integers, not str

**Comment by hjacobs** [comment]
@samuelvonstachelski  can you paste your swagger.yaml here?

**Comment by hjacobs** [comment]
It looks like your operation is not a map, but a list (this would not conform with Swagger spec).

**Comment by samuelvonstachelski** [comment]
swagger: "2.0"
info: 
  title: "FLARECAST pipeline service"
  version: "0.1"
consumes: 
  - application/json
produces: 
  - application/json
paths: 
  /:
    get:
      operationId: pipeline.routes.root
      responses:
        200:
          description: List of base resources
          schema:
            type: array
            items:
              enum:
                - algorithms
                - containers
                - pipeline
  /algorithms: 
    get: 
      operationId: pipeline.routes.algorithms
      responses: 
        200: 
          description: List IDs of all algorithm images
          schema: 
            type: array
            items:
              $ref: "#/definitions/DockerId"
  /algorithms/{id}: 
    get: 
      operationId: pipeline.routes.get_algorithm
      responses: 
        200: 
          description: Description of algorithm image
          schema:
            properties:
              DockerInspect:
                type: object
              UserParams:
                type: string
        404:
          description: Id not found
    put:
      operationId: pipeline.routes.start_algorithm
      responses: 
        200: 
          description: Start a new instance of an algorithm
          schema:
            $ref: "#/definitions/DockerId"
        404:
          description: Id not found
      parameters:
        - name: UserParams
          in: body
          required: true
          description: Represents the content of the user_config.py which will be used by the algorithm instance
          schema:
            properties:
              UserParams:
                type: string
    parameters:
      - $ref: "#/parameters/DockerId"
  /containers:
    get: 
      operationId: pipeline.routes.containers
      responses: 
        200: 
          description: List IDs of all containers (algorithm instances)
          schema: 
            type: array
            items:
              $ref: "#/definitions/DockerId"
  /containers/{id}: 
    get: 
      operationId: pipeline.routes.get_container
      responses:
        200: 
          description: Description of container
          schema:
            properties:
              Id:
                $ref: "#/definitions/DockerId"
              Algorithm:
                $ref: "#/definitions/DockerId"
              ExitCode:
                type: string
              Log:
                type: string
              Name:
                type: string
              Pipe:
                type: string
              Running:
                type: boolean
        404:
          description: Id not found
    post:
      operationId: pipeline.routes.stop_container
      responses:
        200:
          description: Interrupt a running container
        404:
          description: Id not found
    delete:
      operationId: pipeline.routes.delete_container
      responses:
        200:
          description: Remove an interrupted container
        404:
          description: Id not found
    parameters:
      - $ref: "#/parameters/DockerId"
      
  /pipeline: 
    get: 
      operationId: pipeline.routes.pipes
      responses: 
        200: 
          description: List IDs of all pipeline steps
          schema: 
            type: array
            items:
              type: string
  /pipeline/{id}: 
    get: 
      operationId: pipeline.routes.pipe
      responses: 
        200:
          description: Description of algorithm image
          schema:
            properties:
              Id:
                type: string
              name:
                type: string
              pipeNumber:
                type: integer
              algorithms:
                type: array
                items:
                  $ref: "#/definitions/DockerId"
        404:
          description: Id not found
      parameters:
        - name: id
          description: Id of pipe
          in: path
          required: true
          type: string
          
parameters:
  DockerId:
    name: id
    description: Id of algorithm
    in: path
    required: true
    type: string
    minLength: 64
    maxLength: 64



definitions:
  DockerId:
    type: string
    minLength: 64
    maxLength: 64

**Comment by hjacobs** [comment]
Your Swagger YAML is wrong in line 65: https://dev.flarecast.eu/stash/projects/INFRA/repos/pipeline/browse/pipeline/swagger.yaml#65

The "parameters" key is on the same level as the HTTP verbs.

**Comment by samuelvonstachelski** [comment]
Swagger specs 2.0 says this is ok:
http://swagger.io/specification/#pathItemObject

**Comment by hjacobs** [comment]
Oh, true, i.e. we have missing support in Connexion for that right now.

**Comment by samuelvonstachelski** [comment]
Okay, no problem. I am going update our swagger file. This is anyway just a "shortcut"-feature, explicit description for each http verb may be better...
Btw: In earlier versions it worked, but I suppose the path-validation which you introduced shortly broke this.

**Comment by rafaelcaricio** [comment]
This is now supported after #152 got merged.
