### ISSUE TITLE
[question] Hide some ui endpoints

### ISSUE THREAD

**Issue by ex-Dev** [zalando/connexion#481]
Hi,
There is a way to hide some endpoints in ui via connexion api?
For instance, we want to hide /\_\_heartbeat\_\_ from ui in https://aus5.mozilla.org/ui/#/default

Thanks.

**Comment by hjacobs** [comment]
@ex-Dev that's not directly possible in Connexion right now, but this might be a feature request for Swagger UI (e.g. to recognize some property to hide it)?

**Comment by ex-Dev** [comment]
Thanks, @hjacobs.
I'll learn more how to I can pass a property to UI and will ask at swagger-ui repo a possible feature.
Maybe the #483 can help me too.

**Comment by bagrat** [comment]
[Here is how we implemented this](https://ntropy.com/post/evolving-an-api-while-keeping-backwards-compatibility) at @ntropy-network using a `x-hidden` field.
