### ISSUE TITLE
transitive dependencies not picked up by pip breaks installation

### ISSUE THREAD

**Issue by lsh-0** [zalando/connexion#484]
### Description
connexion has a transitive dependency on a specific version range of the library `mccabe` via `flake8` that is specified here: https://github.com/zalando/connexion/blob/master/setup.py#L94

pip doesn't recognize that `setup_requires` though and uses `easy_install` to handle it: https://pip.pypa.io/en/latest/reference/pip_install/#controlling-setup-requires

if connexion is being installed into a project that already has mccabe installed (or any of it's other dependencies: https://github.com/PyCQA/flake8/blob/master/setup.py#L19), but not within the required version ranges, it breaks with an error like: 

```
pkg_resources.VersionConflict: (mccabe 0.5.2 (/path/to/virtualenv/lib/python2.7/site-packages), Requirement.parse('mccabe<0.7.0,>=0.6.0'))
```
the library `pylint` happens to depend on `mccabe` but not any specific version: https://github.com/PyCQA/pylint/blob/master/pylint/__pkginfo__.py#L28

the issue is explored here somewhat: https://github.com/pypa/pip/issues/410

### Expected behaviour

If I `pip install connexion` I expect it's dependencies to be correctly recognised so pip can do what it does best and satisfy them.

**Comment by hjacobs** [comment]
Any suggestions for possible fixes?

**Comment by lsh-0** [comment]
this is what I did: https://github.com/elifesciences/connexion/commit/995ebab9a5731c664434f0fc8f8fd1bc1acfa5b0

nothing fancy. 

the docs (first link in post above) suggest this:

> The solution is to configure a “system” or “personal” Distutils configuration file to manage the fulfillment.

but I figure if I need it to install connexion, and installing connexion involves running setup.py via pip, then it's just another requirement to go in the list of requirements.

**Comment by lsh-0** [comment]
hrm - I see an example now where my fix isn't working. let me dig a little more.

**Comment by dphopkins** [comment]
Any update on this? Eliminating the use of `setup_requires` entirely would be great!

**Comment by lsh-0** [comment]
I think this can be closed now. Our project using connexion isn't using our forked/patched version and we're not having any problems with installation any more.
