### ISSUE TITLE
Cross-origin resource sharing support

### ISSUE THREAD

**Issue by cansik** [zalando/connexion#50]
Is it planned to build CORS into connexion? The only way I found was to use the app (flask) attribute of the app (connexion) and [flask-cors](https://flask-cors.readthedocs.org/en/latest/):

```python
import connexion
from flask.ext.cors import CORS

app = connexion.App(__name__, port=8080, specification_dir='swagger/')
app.add_api('test.yaml')

# add CORS support
CORS(app.app)

app.run()
```

**Comment by hjacobs** [comment]
Using the flask-cors extension does not look too ugly, but we could also enable CORS by default as Connexion supports OAuth (but I'm not sure if this is a good idea as not everybody uses OAuth)

**Comment by dfeinzeig** [comment]
thanks @cansik !  just used flask-cors myself.

**Comment by hjacobs** [comment]
I guess the flask-cors approach is good enough, closing this issue :smile:

**Comment by dfeinzeig** [comment]
I think it makes sense to use that package, especially given the flask philosophy of minimalism.  But maybe we can update the docs recommending it and with the example from above?

**Comment by 31z4** [comment]
I wonder what should I do when using Tornado as a server?

**Comment by hjacobs** [comment]
@31z4 `flask-cors` should AFAIK work independent of the server implementation, i.e. also with Tornado. Or I'm I missing something?

**Comment by 31z4** [comment]
@hjacobs As I understand it only works for a Flask app instance.
