### ISSUE TITLE
Support for Open API Spec v3.0.0

### ISSUE THREAD

**Issue by jakul** [zalando/connexion#502]
[OpenAPI Spec v3.0.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) is now the current version of the specification. Are there plans for Connexion to support it?

**Comment by rafaelcaricio** [comment]
We should. But no work was started yet.

**Comment by tomas-fp** [comment]
Duplicated. See: #420

**Comment by hjacobs** [comment]
Closing as duplicate of #420
