### ISSUE TITLE
overriding json encoder

### ISSUE THREAD

**Issue by lucas03** [zalando/connexion#509]
### Description
Overriding `json_encoder` is not propagated everywhere.
### Expected behaviour
connexion is using same dump encoder
### Actual behaviour
It uses flasks
### Steps to reproduce
We have a custom encoder for json to encode enum. 
So using 
```
      gender:
        type: string
        enum:
          - m
          - f
```
I got error `TypeError: <Gender.m: 'm'> is not JSON serializable`
According to docs, I overriden default encoder:
```python
application = connexion.App(__name__)
application.app.json_encoder = CustomJSONEncoder
```
but this introduces new problem:  
`On instance['passengers'][0]['gender']:\n    None`
For some reason Flask json encoder dumps enum as `null`. This happens in `/lib/python2.7/site-packages/connexion/apis/flask_api.py:_jsonify_data`.
`flask.json.dumps(data, indent=2)` returns `"gender": null`.  
`flask.json.dumps(data, indent=2, default=custom_encoder)` returns `"gender": "f"` as expected. 

(`custom_encoder` is function used in `CustomJSONEncoder` as default method.)
### Additional info:

Output of the commands:

- `python --version`
Python 2.7.13
- `pip show connexion | grep "^Version\:"`
Version: 1.1.14

**Comment by mvalkon** [comment]
@lucas03 sorry for the delay in responding. Could you provide a more complete example for reproduction, including the `CustomJSONEncoder`?

**Comment by lucas03** [comment]
Thanks for replying, I can try to create a minimal example of connexion app with this issue, in few days I guess.   
This is `CustomJSONEncoder`:  
```
class CustomJSONEncoder(FlaskJSONEncoder):

    def default(self, o):  # pylint: disable=E0202
        json.default_encoder(o)
```
where `default_encoder(o)` would be something like this:

```
def default_encoder(obj):  # pylint: disable=method-hidden
    if type(obj) == Decimal:
        return str(float(obj))

    if hasattr(obj, 'isoformat'):
        return str(obj)

    if isinstance(obj, enum.Enum):
        return obj.name
    raise TypeError(repr(obj) + " is not JSON serializable")
```

**Comment by mvalkon** [comment]
@lucas03 thanks for the detailed response, I've verified that you're correct. Would you like to contribute a a fix by opening a PR? If you do not wish to do so, I can assign this to myself.

**Comment by lucas03** [comment]
Yes, I can open a PR. But is overriding init best way how to solve this?

**Comment by mvalkon** [comment]
@lucas03 I had to recheck this as I felt that overriding the `__init__` did not sound like the approach we should take. I think that you're missing a `return` in `CustomJSONEncoder.default()`, currently it calls `default_encoder()` and returns a `None`

```python
class CustomJSONEncoder(FlaskJSONEncoder):
    def default(self, o):
        return default_encoder(o)
```

**Comment by lucas03** [comment]
Oh my god, thanks. :(

**Comment by mvalkon** [comment]
@lucas03 no worries, it was a sneaky issue :)
