### ISSUE TITLE
JSONEncoder datetime.date encoding fails

### ISSUE THREAD

**Issue by cansik** [zalando/connexion#51]
The default function of the [JSONEncoder](https://github.com/zalando/connexion/blob/master/connexion/decorators/produces.py) does only handle `datetime.datetime` types in a special way. So if you insert a `datetime.date` the method fails.

Would be great if you could extend the default function with a special treatment for `datetime.date` objects:

```python
def default(self, o):
    if isinstance(o, datetime.datetime):
        # only supports UTC timestamps
        return o.isoformat('T') + 'Z'
        
    if isinstance(o, datetime.date):
        return o.isoformat()
    return json.JSONEncoder.default(self, o)
```

This converts the `date` into a [W3C](http://www.w3.org/TR/NOTE-datetime) conform string format.

**Comment by hjacobs** [comment]
Your fix looks straight forward :-)
