### ISSUE TITLE
Supply a changelog with each new release

### ISSUE THREAD

**Issue by danfairs** [zalando/connexion#519]
### Description

As a connexion user, it would be great to have a simple document outlining high-level changes and backwards-incompatibilities for each release. It certainly doesn't need to be extensive, but it would be very useful when guiding our application's regression testing and indeed highlighting new features in connexion that we could take advantage of.

Thanks!

**Comment by jmcs** [comment]
We document releases in https://github.com/zalando/connexion/releases .

**Comment by danfairs** [comment]
OK, I didn't know about that - so used to looking for a CHANGES.txt or similar! Maybe a line in the docs pointing to that would be helpful. Thanks.

**Comment by hjacobs** [comment]
@danfairs feel free to create a PR with a proposed change to the README and/or docs --- you know best where you expected the hint :smirk:

**Comment by jmcs** [comment]
@danfairs thanks for PR, but you need to target master in zalando/connexion.

**Comment by danfairs** [comment]
Woops! My bad. Serves me right for trying to edit a file and submit a PR through the GitHub interface for the first time. Hopefully this one is better!

**Comment by hjacobs** [comment]
@danfairs thanks for your contribution! Even those small PRs are really valuable as you are helping the next person find the changelog right away.
