### ISSUE TITLE
Endpoint isn't receiving body as input because underscore inputs are converted to camelcase

### ISSUE THREAD

**Issue by Brian-Williams** [zalando/connexion#537]
EDIT: Look at newest comment first

### Description
An endpoint isn't receiving the body as an input. If the input isn't set with a default of None the method fails with missing positional argument. If None is set as default None is only ever used.

### Expected behaviour
That the body will be passed to the method to use.

### Actual behaviour
No input is handed to the controller methods.

Endpoints with no inputs work as intended.

### Steps to reproduce
Make a call to an endpoint that uses a body input.

With no default arg...
```
def robot_post(robotInput) -> dict:
    print(f"input is {robotInput}")
    return run_command(robotInput, 'robot')
```

It gets a TypeError:
`TypeError: robot_post() missing 1 required positional argument: 'robotInput'`

With a default arg...
```
def robot_post(robotInput=None) -> dict:
    print(f"input is {robotInput}")
    return run_command(robotInput, 'robot')
```

It uses None instead of the send body:

Call:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "name": "name" \ 
 }' 'http://localhost/robot'`

Response:
```
172.17.0.1 - - [07/Nov/2017 05:02:49] "POST /robot HTTP/1.1" 415 -
INFO:werkzeug:172.17.0.1 - - [07/Nov/2017 05:02:49] "POST /robot HTTP/1.1" 415 -
input is None
```

Here is the relevant part swagger definition that generated the above:
```
  /robot:
    post:
      tags:
      - "robot"
      summary: "robot commands"
      description: "Runs a robot command"
      operationId: "controllers.robot_controller.robot_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "robot_input"
        required: false
        schema:
          $ref: "#/definitions/robot_input"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/cli_response"
        400:
          description: "invalid input"
      x-tags:
      - tag: "robot"
```

### Additional info:

I'm using python3.6.3 on debian.

You can pull the image `brianwilliams/robotframework-server` if you need to investigate. Here is the dockerfile:
```
FROM python:3.6.3-stretch

RUN mkdir -p /robot /usr/src/app/

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
COPY . /usr/src/app

WORKDIR /robot

CMD [ "python", "/usr/src/app/app.py" ]
```

The app is the default by the generator:
```
#!/usr/bin/env python3

import connexion

if __name__ == '__main__':
    app = connexion.App(__name__, specification_dir='./swagger/')
    app.add_api('swagger.yaml', arguments={'title': 'Simple RobotFramework API'})
    app.run(port=8080)
```

Here is all of controllers/robot_controller.py:
```
from controllers import run_command
import subprocess
import re


def robot_post(robotInput=None) -> dict:
    print(f"input is {robotInput}")
    return run_command(robotInput, 'robot')


def robot_versions_get() -> dict:
    complete_process = subprocess.run(['robot', '--version'], stdout=subprocess.PIPE, universal_newlines=True)
    versions = re.finditer('([\d+\.]+)', complete_process.stdout)
    return {'robot': next(versions).group(0),
            'python': next(versions).group(0)}
```

Connexion:
Version: 1.1.16

**Comment by Brian-Williams** [comment]
Ooops, this was my fault. The docker image was build with mismatched swagger and input variables.

**Comment by Brian-Williams** [comment]
The real bug is that swaggerhub autogenerated controllers use incorrect inputs when using underscores instead of camelCase.

When you use lowercase_with_underscores naming style the autogenerator changes it to camelCase while still expecting lowercase_with_underscores.

So this spec:
```
  /rebot:
    post:
      tags:
      - "rebot"
      summary: "rebot commands"
      description: "Runs a rebot command"
      operationId: "controllers.rebot_controller.rebot_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "rebot_input"
        required: false
        schema:
          $ref: "#/definitions/rebot_input"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/cli_response"
        400:
          description: "invalid input"
      x-tags:
      - tag: "rebot"
```
With the important line being ` name: "rebot_input"`

Will generate this in rebot_controller:
```
def rebot_post(rebotInput = None) -> str:
    return 'do some magic!'
```

When it should be:
```
def rebot_post(rebot_input = None) -> str:
    return 'do some magic!'
```

More of a minor annoyance than a serious bug. I've reopened anyway for visibility. Feel free to close again if desired.

**Comment by mvalkon** [comment]
@Brian-Williams could you provide a minimal swagger example that validates (your example refers to definitions that are not there)

**Comment by Brian-Williams** [comment]
You can omit all the parts that I didn't highlight. The only important part is `name: "rebot_input"`.

I just took the petstore example and did a replace all of `petId` with `pet_id` and then if you generate the server and look at the controller it incorrectly has the inputs as camelCase instead of underscores.

pet_controller.py generated from [this](https://app.swaggerhub.com/apis/Brian-Williams/connexion-537/1.0.0) swaggerhub repo. If that link is broken in the future it's just the petstore example with a replace all on petId with pet_id.
```

def add_pet(body) -> str:
    return 'do some magic!'

def delete_pet(petId, apiKey = None) -> str:
    return 'do some magic!'

def find_pets_by_status(status) -> str:
    return 'do some magic!'

def find_pets_by_tags(tags) -> str:
    return 'do some magic!'

def get_pet_by_id(petId) -> str:
    return 'do some magic!'

def update_pet(body) -> str:
    return 'do some magic!'

def update_pet_with_form(petId, name = None, status = None) -> str:
    return 'do some magic!'

def upload_file(petId, additionalMetadata = None, file = None) -> str:
    return 'do some magic!'
```
All instances of petId in the above spec should be pet_id as petId is no longer found in the yml file.
