### ISSUE TITLE
Expose WSGI interface

### ISSUE THREAD

**Issue by iwsmith** [zalando/connexion#54]
This bug is actually part bug, part feature request/enhancement, depending on how one wants to approach it. 

## Problem 
The Connexion app doesn't expose a WSGI interface, and as such cannot be hosted by Nginx/Apache/other WSGI compliant servers.

## Solution 1
Instead of wrapping the Flask application object, make Connexion a [Flask extension](http://flask.pocoo.org/docs/0.10/extensiondev/). I am not sure how much work this would involve, but is likely a breaking change.

## Solution 2 
Expose the WSGI interface. Note that simply adding a ``__call__`` method isn't sufficient; though the application starts everything is being pushed to Flask, not Connexion. Effectively this results in bypassing Connexion, so it doesn't really solve the problem. I don't know what is involved in exposing the full WSGI interface, but I suspect it is non-trivial.

Just as an example of what __won't__ work, I tried this fix:
```
    def __call__(self, environ, start_response):
        """
        Provide the shortcut to the underlying WSGI interface
        """
        return self.app(environ, start_response)
```
on the Connexion.app class. This is meant to mirror [what Flask does](https://github.com/mitsuhiko/flask/blob/master/flask/app.py#L1967), but as noted above ends up bypassing Connexion all together.

**Comment by hjacobs** [comment]
Definitely looks like something desirable, but actually I never used a WSGI server host such as Apache/mod_wsgi etc before. I simply use Connexion with gevent and packaged as Docker image.

**Comment by iwsmith** [comment]
Yeah this is what I ended up doing as well. So this issue isn't blocking/causing an issue, more of a "one day Connexion should probably do this" sort of thing. Maybe an enhancement instead of a bug? Some additional documentation on the matter wouldn't hurt though...

**Comment by hjacobs** [comment]
:+1: I hope "somebody" (tm) with WSGI experience can step in here :-)

**Comment by hjacobs** [comment]
@iwsmith using uWSGI is actually quite easy (just needs to expose app.app as "application" for WSGI), check my example: https://github.com/hjacobs/connexion-example#using-connexion-with-a-wsgi-container

**Comment by hjacobs** [comment]
I will close this issue as the Flask WSGI application can readily be used in WSGI containers (see connexion-example).

**Comment by iwsmith** [comment]
I haven't had time/the need to look into this, but thanks for following up!

**Comment by Majoros** [comment]
The following is all that's needed to get it working with wsgi

app = connexion.App(__NAME__)
application = app.app

**Comment by hjacobs** [comment]
:+1:

**Comment by spearsem** [comment]
Has anyone looked into how this can work with gunicorn instead of uWSGI? This is quite an important tool for deploying Flask apps, so ensuring that documentation for how to use with gunicorn might be a high priority.

**Comment by sellers** [comment]
What goes into the swagger yaml file for the module name?   I can get this to work with invoking ./python.py but not with python python.py or via WSGI.  I get the module object has no attribute XXX

**Comment by FirefoxMetzger** [comment]
@sellers are you using the flask / connexion swagger generator?
If so then that is because the generated `__main__.py` creates the app within `main()` which called within the  `if __name__ == "__main__"` statement and as such the app will only be created if it's executed directly. WSGI (uwsgi or gunicorn) will instead to load it as a module and not execute the `if` statement.

In this case the solution would simply be to modify that file so the `app` (and `application = app.app`) is created as a variable in the module's namespace (e.g. by moving it outside of `main()`). However, I would keep the `app.run()` command in the `if` =)

**Comment by hjacobs** [comment]
@FirefoxMetzger maybe do some upstream PR for the Swagger generator template to fix the issue?

**Comment by profgiuseppe** [comment]
@FirefoxMetzger I just tested your solution, while the generated code exposes the ui when running the app directly (on a custom port), requests on port 80 via wsgi always return a 404 for me, even with your code.

**Comment by profgiuseppe** [comment]
#392 may be of interest if someone (like me) stumbles in this discussion.

**Comment by aude** [comment]
This looks to work now. I can successfully run:

    $ gunicorn main:app
    [2020-07-02 13:38:08 +0000] [144535] [INFO] Starting gunicorn 20.0.4
    [2020-07-02 13:38:08 +0000] [144535] [INFO] Listening at: http://127.0.0.1:8000 (144535)
    [2020-07-02 13:38:08 +0000] [144535] [INFO] Using worker: sync
    [2020-07-02 13:38:08 +0000] [144537] [INFO] Booting worker with pid: 144537

Maybe ideas from the original post was implemented.
https://github.com/zalando/connexion/blob/bed4b95205205861bd6014282d0f61d50231d3ac/connexion/apps/abstract.py#L242-L249
This code from a7af62fbf072eef13737edec8e5c49a5ff0a7a72 could indicate that.
