### ISSUE TITLE
verify_oauth uses url params instead of Authorization headers for token info

### ISSUE THREAD

**Issue by mohabusama** [zalando/connexion#541]
### Description

``verify_oauth`` uses url params instead of Authorization headers for token info.
Using Authorization header is the recommended way for verifying tokens.

Using url params could lead to leaking access tokens to external services. We faced this issue during testing OpenTracing. Authorization headers provides a more structured way in preventing leaking access tokens (e.g. in opentracing tags).

### Expected behaviour

Using Authorization headers for verifying tokens.

### Actual behaviour

Using URL params for verifying tokens.

### Additional info:

Output of the commands:

- `python --version`
Python 3.5.2
- `pip show connexion | grep "^Version\:"`

**Comment by kislyuk** [comment]
As alluded to in the release notes, this breaks compatibility with various tokeninfo APIs, including Google. Please make this configurable.

**Comment by hjacobs** [comment]
@kislyuk contributions are welcome!
