### ISSUE TITLE
AttributeError: 'app' object has no attribute 'calc'

### ISSUE THREAD

**Issue by bharathjinka09** [zalando/connexion#544]
### Description
I created a calculator application using python and I got this error as "app object has no attribute calc"

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by hjacobs** [comment]
Could you provide some more context (Swagger file, code, ..)? Your problem description does not allow me to help you.

**Comment by bharathjinka09** [comment]
I created a calculator application using python.But it is showing an error as above .can u please help me . It is showing the calculator window ,but when I am pressing the = symbol,it is showing that error.
Tq in advance 😀

**Comment by ePaul** [comment]
Hi @bharathjinka09, unless you can make it clear how your problem relates to the connexion project (other than both being written in Python), we can't help you here. If your problem is not actually about connexion, please ask at a different place instead.

**Comment by bharathjinka09** [comment]
This is my calculator code and it is getting an error as "AttributeError: 'app' object has no attribute 'calc'
" and i have attached the image also.Can u please help me with that issue.Thank you:-)
![screenshot 1041](https://user-images.githubusercontent.com/33654188/32794235-438c9d7e-c98e-11e7-9e6a-a1067dfa66d7.png)

from tkinter import*
from tkinter import ttk
def icalc(source,side):
    storeobj = Frame(source,borderwidth=10,bd=4,bg="yellow")
    storeobj.pack(side=side,expand=YES,fill=BOTH)
    return storeobj
def button(source,side,text,command=None):
    storeobj = Button(source,text=text,command=command)
    storeobj.pack(side=side,expand=YES,fill=BOTH)
    return storeobj
class app(Frame):
    def __init__(self):
        Frame.__init__(self)
        self.option_add('*Font','arial 20 bold')
        self.pack(expand=YES,fill=BOTH)
        self.master.title('calculator')
        display = StringVar()
        Entry(self,relief=RIDGE,textvariable=display,justify='right',bd=30,bg="skyblue").pack(side=TOP,expand=YES,fill=BOTH)

        for clear in (["CL"],["C"]):
            erase = icalc(self,TOP)
            for char in clear:
                button(erase,LEFT,char,lambda storeobj=display,q=char:storeobj.set(''))
        for num in ("789/","456*","123-","0.+"):
            funnum = icalc(self, TOP)
            for char in num:
                button(funnum, LEFT, char, lambda storeobj=display, q=char: storeobj.set(storeobj.get()+q))
        Equals = icalc(self,BOTTOM)
        for iequals in "=":
            if iequals == '=':
                btnieqls = button(Equals,LEFT,iequals)
                btnieqls.bind('<ButtonRelease-1>',lambda e,s=self, storeobj=display: s.calc(storeobj),'+')
            else:
                btnieqls = button(Equals,LEFT,iequals,
                                  lambda storeobj=display, s='%s '%iequals: storeobj.set(storeobj.get()+s))

if __name__=='__main__':
    app().mainloop()
![screenshot 1041](https://user-images.githubusercontent.com/33654188/32794131-fddc1016-c98d-11e7-8891-06096d887b33.png)

**Comment by ePaul** [comment]
Hi @bharathjinka09, it doesn't look like your project is using Connexion. As such, your problem is off-topic here. Please try other places for help.

**Comment by bharathjinka09** [comment]
![screenshot 1042](https://user-images.githubusercontent.com/33654188/32795114-c7d17d00-c990-11e7-908c-86f2665b7692.png)
![screenshot 1043](https://user-images.githubusercontent.com/33654188/32795115-c811b0fa-c990-11e7-8832-9dcfbb7c85fc.png)

**Comment by hjacobs** [comment]
Closing as it does not seem to be related to Connexion.
