### ISSUE TITLE
How To Access Project Metadata

### ISSUE THREAD

**Issue by jcantu-usgs** [zalando/connexion#554]
How may I access project metadata such as version?  For example, I'd like to write an endpoint that returns information such as that defined in the setup.py file such as VERSION, etc.

**Comment by mohabusama** [comment]
If VERSION is defined in ``setup.py`` and not in your project (say in ``__init__.py``) then you may use:

```python
from pkg_resources import get_distribution

__version__ = get_distribution('INSTALLED-PACKAGE-NAME-HERE').version
```

**Comment by jcantu-usgs** [comment]
Excellent.  Thank you!
