### ISSUE TITLE
PyPI description renders incorrectly

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#584]
Connexion's PyPI description (restructured text) renders incorrectly: https://pypi.org/project/connexion/#description

I'm not sure when it broke, I detected it only yesterday.

**Comment by mohabusama** [comment]
``Unexpected indentation.`` line 126

**Comment by hjacobs** [comment]
@mohabusama can you do a quick PR?

**Comment by hjacobs** [comment]
This is now fixed :tada: 

![screenshot-2018-5-16 connexion 1](https://user-images.githubusercontent.com/510328/40106786-ee341c78-58f6-11e8-8e52-41ecd24e0361.png)
