### ISSUE TITLE
Get key of field causing the validation error

### ISSUE THREAD

**Issue by saschalocht** [zalando/connexion#594]
### Description
Is it possible to seethe field that caused the validation error in the error message?

### Expected behaviour
Example: The client entered an unknown enum 'C' for field 'letter'. Enum definition: ['A', 'B']
Error returned by Validation:
{
  "detail": "Validation of field 'letter' failed. 'C' is not one of ['A', 'B']",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

### Actual behaviour
{
  "detail": "'C' is not one of ['A', 'B']",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

### Steps to reproduce
Define a body like this:

...
letter:
        type: 'string'
        enum: ['A', 'B']
...

### Additional info:

Output of the commands:

- `python --version` Python 3.6.3
- `pip show connexion | grep "^Version\:"` 1.1.9

**Comment by palmkevin** [comment]
I would be interested in this too !

**Comment by advance512** [comment]
:+1: 
This would be super helpful.

**Comment by lumikanta** [comment]
Can be achieved by tweaking decorators/validation.py, class RequestBodyValidator
- joined jsonschema exception path elements to message

original code
```python
   def validate_schema(self, data, url):
        # type: (dict, AnyStr) -> Union[ConnexionResponse, None]
        if self.is_null_value_valid and is_null(data):
            return None

        try:
            self.validator.validate(data)
        except ValidationError as exception:
            logger.error("{url} validation error: {error}".format(url=url,
                                                                  error=exception.message),
                         extra={'validator': 'body'})
            return problem(400, 'Bad Request', str(exception.message))

        return None
```

modified code
```python
    def validate_schema(self, data, url):
        # type: (dict, AnyStr) -> Union[ConnexionResponse, None]
        if self.is_null_value_valid and is_null(data):
            return None

        try:
            self.validator.validate(data)
        except ValidationError as exception:
            logger.error("{url} - '{path}' - validation error: {error}".format(url=url,
                                                                  path=".".join(exception.path),
                                                                  error=exception.message),
                         extra={'validator': 'body'})
            return problem(400, 'Bad Request', "'{path}' - {message}".format(path=".".join(exception.path), message=exception.message))

        return None
```
