### ISSUE TITLE
Document that HEAD calls GET operationId

### ISSUE THREAD

**Issue by fdemello** [zalando/connexion#596]
### Description

Please document that the head method actually calls the operationId of the get method so developers have to do something like the below.

```
if connexion.request.method == "HEAD":  
    return None, status_code, headers_to_return
```

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.1

- `pip show connexion | grep "^Version\:"`
Version: 1.1.9 but also tested with 1.4.2

**Comment by dtkav** [comment]
hey @fdemello , are you able to make a pull request for this?

**Comment by dtkav** [comment]
yup, this is a feature of Flask
http://flask.pocoo.org/docs/1.0/quickstart/#http-methods

**Comment by dtkav** [comment]
hey @fdemello , are you still planning to update the docs, or shall I close out this issue?
