### ISSUE TITLE
Default parameters break with collectionFormat csv

### ISSUE THREAD

**Issue by RacingTadpole** [zalando/connexion#608]
### Description

Can no longer define a `default` value for a query parameter with `type: array`, `items: {type: string}` and `collectionFormat: csv`. Possibly this is because of a change in swagger-spec-validator.

### Expected behaviour

In connexion version 1.3 (and swagger-spec-validator 2.1.0), a string default value worked in the above case.
An array default value would be fine too, and be more consistent with the `collectionFormat`.

### Actual behaviour

With a string default, eg. ```default: foobar```,
```
swagger_spec_validator.common.SwaggerValidationError:
("'foobar' is not of type 'array'\n\n
Failed validating 'type' in schema:\n
    {'collectionFormat': 'csv',\n
     'default': 'foobar',\n
     'in': 'query',\n
     'items': {'type': 'string'},\n
     'name': 'bar',\n
     'type': 'array'}\n\n
On instance:\n
    'foobar'", <ValidationError: "'foobar' is not of type 'array'">)
```
With an array default, eg. ```default: ["foobar"]```
```
  File ".../connexion/decorators/validation.py", line 55, in validate_type
    parts = value.split(",")
AttributeError: 'list' object has no attribute 'split'
```

### Steps to reproduce

Use this `swagger.yaml` file: 
```
swagger: "2.0"
info:
  title: Thing
  version: "0"
paths:
  /foo:
    get:
      operationId: "test_app.api.foo"
      parameters:
        - $ref: "#/parameters/bar"
      responses:
        200:
          description: "Results."

parameters:
  bar:
    name: bar
    in: query
    type: array
    items:
      type: string
    collectionFormat: csv
    default: foobar
```
Use this `api.py`:
```
import connexion
def foo(bar):
  return bar
```
then execute:
```
import os
swagger_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'swagger.yaml')
app.add_api(swagger_path, base_path='/v0', strict_validation=True, validate_responses=False)
app.run()
```

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.5 :: Anaconda, Inc.
- `pip show connexion | grep "^Version\:"`
Version: 1.4.2

Also using swagger-spec-validator version 2.3.1.

**Comment by dtkav** [comment]
hey @RacingTadpole - please have a look at #613 and see if fixes your issue.
Thanks!

**Comment by RacingTadpole** [comment]
Hi, just tried it out, and yes, it works - thanks!
