### ISSUE TITLE
Provide examples of correctly configuring OAuth support

### ISSUE THREAD

**Issue by valgog** [zalando/connexion#61]
Documentation on how to configure the OAuth support for Greendale and STUPS would be very helpful

**Comment by hjacobs** [comment]
@valgog there is a more or less complete example in my personal repo (it's also linked from the README): https://github.com/hjacobs/connexion-example

You basically have to provide only the TokenInfo URL, see https://github.com/hjacobs/connexion-example#using-oauth2-security

**Comment by rafaelcaricio** [comment]
Can we close this issue?

**Comment by hjacobs** [comment]
Yes, I added an example recently here: https://github.com/zalando/connexion/tree/master/examples/oauth2

**Comment by rafaelcaricio** [comment]
Great! :heart:
