### ISSUE TITLE
No tar file on pypi for 1.5.0/1.5.1?

### ISSUE THREAD

**Issue by bobh66** [zalando/connexion#637]
### Description

There is no source tar file available on pypi.org for the 1.5.0 and 1.5.1 releases.  1.4.2 is the last release that
has a tar file.

**Comment by jmcs** [comment]
Hi, something went wrong uploading those two versions (probably my fault).
I made sure the source tar is available for 1.5.2:

![image](https://user-images.githubusercontent.com/3719966/43246387-c93df02c-90b1-11e8-9338-03e487c655f6.png)

**Comment by bobh66** [comment]
@jmcs Thank you!
