### ISSUE TITLE
Type warning when giving Werkzeug-specific options arguments to App.run() in development mode

### ISSUE THREAD

**Issue by paulkernstock** [zalando/connexion#645]
### Description
When one will give a Werkzeug-specific argument to `App.run()` which will be passed by the connexion app to the underlying Werkzeug server in development mode, IDEs like PyCharm will warn, that the type of the given argument does not match the expected type, which is stated in the function's docstring to be `dict`. No matter the warning everything seems to work as expected.

### Expected behaviour
No warning

### Actual behaviour
Warning

### Steps to reproduce
Insert this code in PyCharm:
```
import connexion
from connexion import RestyResolver
import pathlib

app = connexion.App(__name__, specification_dir='./')
app.add_api(pathlib.Path('swagger.yml'), resolver=RestyResolver(default_module_name='backend.api'), strict_validation=True)


if __name__ == '__main__':
    app.run(threaded=False)
```

### Additional info:

Output of the commands:

- `python --version`
Python 3.5.2
- `pip show connexion | grep "^Version\:"`
Version: 1.5.2
- `pip show flask | grep "^Version\:"`
Version: 1.0.2

**Comment by dtkav** [comment]
We could change the API to accept both `*args` and `**kwargs` and pass them both to the underlying Werkzeug server (feel free to make a pull request), but you could also just pass in **kwargs like so:
```
if __name__ == '__main__':
    werkzeug_options = {"threaded": False}
    app.run(**werkzeug_options)
```

**Comment by dtkav** [comment]
Hey @paulkernstock - did my suggestion work for you?

**Comment by paulkernstock** [comment]
Thanks @dtkav, yes, of course your workaround works in terms of eliminating the warning. But it's not that intuitive, right?

I don't know if I can find the time to contribute a pull request (never did one before, if all that is to it is to add `*args` to the signature of `FlaskApp.run()`, I will of course be glad to do it :) ).

Thanks for your work!

**Comment by jmcs** [comment]
This looks like a bug in PyCharm to me.

The extra keywords variable is a dict:

```
>>> def f(**kwargs):
...   print(type(kwargs))
... 
>>> f(name='value')
<class 'dict'>
>>> 
```

This is also how [it's documented in Python's documentation](https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments).

**Comment by paulkernstock** [comment]
I think you are right @jmcs I will try and issue this at JetBrains.

**Comment by paulkernstock** [comment]
OK from my conversation with Semyon from JetBrains I think this issue should be reopened.

He pointed out that PyCharm is only following [PEP 484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values). It is stated there, that the type of arbitrary arguments should be annotated with the expected type of the arguments given to the function, not the type of the arguments list or dict itself.

Following this, the type annotation of arbitrary Werkzeug options in the docstring of `app.run()` should not be given as `dict` because you don't expect only dicts as values of `kwargs`. It should probably just be left out instead as there are many types of arguments that can be expected.

I hope could make this clear by means of formulation.

**Comment by dtkav** [comment]
here is what I think I heard in terms of actions:
- remove type annotation for `kwargs`

Is that right?

**Comment by paulkernstock** [comment]
Yes. 😬
