### ISSUE TITLE
Swagger UI not handling array parameters correctly when sent in formData

### ISSUE THREAD

**Issue by sknick** [zalando/connexion#658]
### Description

The Swagger UI does not handle array parameters correctly when in formData.

### Expected behaviour

Array parameters can be specified that come in through formData.

### Actual behaviour

When array parameters are specified that come in through formData and consumes: multipart/form-data is specified, only a single parameter can be specified in the Swagger UI or the parameters come in as one large parameter that is malformed. For example, the following server console output shows the result of printing this parameter when one parameter "test" is given in the Swagger UI and then the result when the three parameters "test", "test2", and "test3" are provided:

```
['test']
127.0.0.1 - - [07/Aug/2018 12:55:19] "POST /test HTTP/1.1" 200 -
['test&array_values=test2&array_values=test3']
127.0.0.1 - - [07/Aug/2018 12:55:25] "POST /test HTTP/1.1" 200 -
```

### Steps to reproduce

The following simple service definition will suffice to reproduce the issue:

    swagger: "2.0"

    info:
      version: 0.0.1
      title: Test
      description: Shows the problems in the Swagger UI when you attempt to specify multiple array values in an array parameter.

    paths:
      "/test":
        post:
          description: Test service.

          consumes:
          - multipart/form-data
          produces:
          - application/json

          parameters:
          - name: array_values
            description: The array values
            in: formData
            required: false
            type: array
            items:
              type: string

          responses:
            200:
              description: All is good

The default_controller that results from using swagger-codegen on this definition can be modified to print the parameter as follows:

    import connexion
    import six

    from swagger_server import util

    def test_post(array_values=None):  # noqa: E501
        """test_post

        Test service. # noqa: E501

        :param array_values: The array values
        :type array_values: List[str]

        :rtype: None
        """
        print(array_values)
        return "Success", 200

### Additional info:

Output of the commands:

- `python --version`

Python 3.4.3

- `pip show connexion | grep "^Version\:"`

Version: 1.4

**Comment by dtkav** [comment]
I'm trying out multiple versions of swagger-ui, and they seem to behave differently depending on the version.
For reference, here's a curl command that makes sense to me (form parameters passed separately).
```
curl \
  -X POST \
  --header 'Content-Type: multipart/form-data' \
  --header 'Accept: application/json' \
  -F array_values=a \
  -F array_values=b \
  -F array_values=c \
  'http://localhost:8091/test'
```
It looks like the vendored swagger UI creates this equivalent curl command:
```
curl \
  -X POST \
  --header 'Content-Type: multipart/form-data' \
  --header 'Accept: application/json' \
  -F array_values=a%26array_values%3Db%26array_values%3Dc
  'http://localhost:8091/test'
```
Finally, using swagger-ui 3.17.1 the equivalent curl command is:
```
curl \
  -X POST \
  --header 'Content-Type: multipart/form-data' \
  --header 'Accept: application/json' \
  -F "array_values="a","b","c""
  'http://localhost:8091/test'
```
which _almost_ works, but everything is double quoted:
```
['"a"', '"b"', '"c"']
```

AFAICT this is a [swagger-ui](https://github.com/swagger-api/swagger-ui) bug. What do you think?
If you believe this to be a connexion bug, it would be really helpful if you could provide a test-case with curl or requests.

I can dig deeper later today, and see if there is a ticket over on the swagger-ui project.

- Daniel

**Comment by sknick** [comment]
No, you're right... I think the bug is specifically in the UI. I guess I got confused about what Connexion handles vs. what is handled elsewhere. Let me know if you find anything out elsewhere.

**Comment by dtkav** [comment]
so far, these seem related:
https://github.com/swagger-api/swagger-ui/issues/4741
https://github.com/swagger-api/swagger-ui/issues/4146

**Comment by dtkav** [comment]
thanks @webron - I appreciate it.

**Comment by dtkav** [comment]
I'm going to close this out, because I believe this is a swagger-ui bug.
Please feel free to re-open if I got it wrong.

**Comment by zia-devsinc** [comment]
This is how i did it for array parameters in schema
`multipart/form-data:
  schema:
    $ref: '#/components/schemas/ProjectPost'
  encoding:
    secondary_languages[]:
      style: form
      explode: true
    keywords[]:
      style: form
      explode: true
    tags[]:
      style: form
      explode: true`
