### ISSUE TITLE
aiohttp: `async def` impossible to use

### ISSUE THREAD

**Issue by diefans** [zalando/connexion#663]
### Description
It is impossible to use `async def` coroutines (https://www.python.org/dev/peps/pep-0492/#new-coroutine-declaration-syntax) for route handler.

`async def` for routes is not working due to connexions decorating of route functions and later testing for `asyncio.iscoroutinefunction()`, which is broken by loosing `object.__code__.co_flags`.
This is not relevant for `@asyncio.coroutine` decorated functions, since they own a `_is_coroutine` attribute, which is copied by `functools.wraps`. See `inspect.iscoroutinefunction()`. 

see:
- `connexion.utils.has_coroutine`
- `connexion.decorators.response.ResponseValidator.__call__`
- `connexion.decorators.decorator.EndOfRequestLifecycleDecorator.__call__`

### Expected behaviour
It works when using `async def`.

### Actual behaviour
 It simple gives a `AttributeError("'generator' object has no attribute 'status'",)` error.

### Steps to reproduce
Use `async def` for coroutines definition.

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.5

- `pip show connexion | grep "^Version\:"`
Version: 1.5.2

**Comment by dtkav** [comment]
@dutradda any ideas?

**Comment by dtkav** [comment]
Hey @diefans , does this open PR fix your issue? https://github.com/zalando/connexion/pull/600

**Comment by diefans** [comment]
@dtkav any chance the PR gets merged?

**Comment by dtkav** [comment]
@diefans I am unable to merge anything into master (I have limited permissions as a community maintainer).
It looks like @jmcs was waiting on @dutradda to add comments to the function since Jul 26.
You might be able to make your own pull request that fixes the issue - I haven't had a chance to look into it.

**Comment by dtkav** [comment]
@diefans #600 has been merged - let me know if I can close this ticket?

**Comment by diefans** [comment]
@jmcs thanks
