### ISSUE TITLE
Metrics: report correct HTTP status code

### ISSUE THREAD

**Issue by gavronek** [zalando/connexion#665]
### Description

Currently the [UWSGIMetricsCollector](https://github.com/zalando/connexion/blob/53908d30e566ccb81d73d3e27b461f407a8a8d31/connexion/decorators/metrics.py#L33) reporting will create a metrics key with status_code=500 for all exception thrown in the underlying call (BadRequest, Unauthorized, etc.)

### Expected behaviour
If an HTTPException is thrown in the underlying function, use the status code of the exception to report in the metrics. If an unknown exception is thrown map it to a specific "unkown exception" metrics key.

E.g.:
```json
"timers": {
    "connexion.response.401.GET.state.{id}": {
        "count": 2
    },
    "connexion.response.unknown-exception.GET.state.{id}": {
        "count": 2
    }
}
```

### Actual behaviour
**Any** exception is mapped to status code 500 as that is the default:
```json
"timers": {
    "connexion.response.500.GET.state.{id}": {
        "count": 2
    }
}
```

### Solution suggestion
Maybe something like this would help?
```python
from werkzeug.exceptions import HTTPException

@functools.wraps(function)
def wrapper(request):
    status = 'unknown-exception'
    start_time_s = time.time()
    try:
        response = function(request)
        status = response.status_code
    except HTTPException as http_e:
        status = str(http_e.code)
        raise http_e
    finally:
        end_time_s = time.time()
        delta_s = end_time_s - start_time_s
        delta_ms = delta_s * 1000
        key = '{status}.{suffix}'.format(status=status, suffix=self.key_suffix)
        uwsgi_metrics.timer(self.prefix, key, delta_ms)
    return response

**Comment by dtkav** [comment]
Hey @gavronek , do you mind making a pull request with your proposed change?
It sounds reasonable to me.

**Comment by dtkav** [comment]
Thanks! I added a small comment, but otherwise this is looking good!
