### ISSUE TITLE
Allow several types for a single request parameter in swagger.json

### ISSUE THREAD

**Issue by erezatiya** [zalando/connexion#666]
Using swagger2.0 with Connexion.

I'd like to be able to define a request parameter in my swagger.json which allows any type (or a list of types).
I've tried using `"type": "any"` but swagger validation does not allow this.
I'd like to be able to do this to parameters which can be in either body, path or header.

### Additional info:
Python 3.6.4
Connexion 1.5.2

**Comment by dtkav** [comment]
If what you want is [polymorphism](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schemaComposition), then there is a feature in OpenAPI v3 which allows the API to accept multiple types of objects with (using oneOf), but each type of object must still have a schema (i.e. be typed). OpenAPI v3 support is in work for connexion at the moment (https://github.com/zalando/connexion/pull/621).

Having type information is required by Swagger 2.0 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object
Connexion implements the OpenAPI spec, so your request is simply not possible with Swagger 2.0.

Good luck.

**Comment by erezatiya** [comment]
Would it be possible to have a parameter without any sort of validation? Could I create a custom validator to achieve this?

**Comment by dtkav** [comment]
> Would it be possible to have a parameter without any sort of validation? Could I create a custom validator to achieve this?
Even if you removed validation entirely, the type information is still used to deserialize/decode data provided by the user. You could potentially just type everything as "string"s and then cast them to whatever types later, but I wouldn't recommend it.

Can you say more about what you are trying to achieve?

Without understanding more about your constraints or your higher level goal, it seems like you are trying to work around the whole point of connexion.

**Comment by erezatiya** [comment]
Thank you for your response!

I have a parameter which changed its type in newer versions of my API, and I'd like to retain backwards compatibility (should be invisible to the client), by allowing the client to send the parameter in any of the allowed types.

Ways to achieve this would be to define a group of types allowed for the parameter, or allow any type, or skip validation altogether **for this specific parameter**.

**Comment by dtkav** [comment]
Ok, yeah I think I'd recommend upgrading to OpenAPI 3 when it becomes available, and using polymorphism. That way you can do something like:
```
schema:
  oneOf: {
    "$ref": "#/components/schemas/NewSchema",
    "$ref": "#/components/schemas/BackwardsCompatibleSchema"
  }
```
If you need this capability while using swagger 2, you'll probably want to fork this project. If you can provide more details (a spec, your operation code, etc) I may be able to give you more extensive guidance.

**Comment by dtkav** [comment]
Hey @erezatiya , I'm going to close this issue - please re-open if there's something I missed!
