### ISSUE TITLE
[dev-2.0] RefResolver cannot resolve yaml

### ISSUE THREAD

**Issue by dtkav** [zalando/connexion#681]
```
connexion/jsonref.py:from jsonschema import RefResolver
```

because it can't parse yaml schema files like https://opensource.zalando.com/problem/schema.yaml

I workaround'd it in the `jsonschema` module

```

+++ b/jsonschema/validators.py
@@ -2,6 +2,7 @@ from __future__ import division
 
 import contextlib
 import json
+import yaml
 import numbers
 
 try:
@@ -466,12 +467,15 @@ class RefResolver(object):
             # Requests has support for detecting the correct encoding of
             # json over http
             if callable(requests.Response.json):
-                result = requests.get(uri).json()
-            else:
-                result = requests.get(uri).json
+                try:
+                    result = requests.get(uri).json()
+                except ValueError:
+                    result = None
+            if not result:
+               result = yaml.load(requests.get(uri).content)
         else:
             # Otherwise, pass off to urllib and assume utf-8
-            result = json.loads(urlopen(uri).read().decode("utf-8"))
+           result = yaml.load(urlopen(uri).read().decode("utf-8"))
 
         if self.cache_remote:

```

But on https://github.com/Julian/jsonschema/issues/420 it seems yaml is currently out of scope.

Can we fix it in `connexion` subclassing RefResolver?

_Originally posted by @ioggstream in https://github.com/zalando/connexion/issues/678#issuecomment-421061800_

**Comment by dtkav** [comment]
Hey @ioggstream let me know if #682 fixes your issue!

**Comment by ioggstream** [comment]
Thanks @dtkav.

This generally work! You did a wonderful job!

I create a simple nosetests that could be helpful in this validating external yamls 
(this adds a FakeResolver dynamically adding functions to the module)

https://gist.github.com/ioggstream/e50ad5c1405f44e7ec266e1016fa2a29

As of now:

  - zapp.options.oas_version == (2,0) even for oas2 files.

Q: can I get the spec back from the parsing? It could be interesting to test the resulting yaml back.

**Comment by dtkav** [comment]
cool @ioggstream - If you want to, you could modify that into a unit test and submit it as a PR to run in the test suite.

> Q: can I get the spec back from the parsing? It could be interesting to test the resulting yaml back.
```python
app = connexion.FlaskApp(__name__)
api = app.add_api('openapi.yaml')
api.raw_spec       # raw spec
api.specification  # parsed spec
```

**Comment by Guru67724** [comment]
> ```
> connexion/jsonref.py:from jsonschema import RefResolver
> ```
> because it can't parse yaml schema files like https://opensource.zalando.com/problem/schema.yaml
> 
> I workaround'd it in the `jsonschema` module
> 
> ```
> 
> +++ b/jsonschema/validators.py
> @@ -2,6 +2,7 @@ from __future__ import division
>  
>  import contextlib
>  import json
> +import yaml
>  import numbers
>  
>  try:
> @@ -466,12 +467,15 @@ class RefResolver(object):
>              # Requests has support for detecting the correct encoding of
>              # json over http
>              if callable(requests.Response.json):
> -                result = requests.get(uri).json()
> -            else:
> -                result = requests.get(uri).json
> +                try:
> +                    result = requests.get(uri).json()
> +                except ValueError:
> +                    result = None
> +            if not result:
> +               result = yaml.load(requests.get(uri).content)
>          else:
>              # Otherwise, pass off to urllib and assume utf-8
> -            result = json.loads(urlopen(uri).read().decode("utf-8"))
> +           result = yaml.load(urlopen(uri).read().decode("utf-8"))
>  
>          if self.cache_remote:
> ```
> But on [Julian/jsonschema#420](https://github.com/Julian/jsonschema/issues/420) it seems yaml is currently out of scope.
> 
> Can we fix it in `connexion` subclassing RefResolver?
> 
> _Originally posted by @ioggstream in [#678 (comment)](https://github.com/zalando/connexion/issues/678#issuecomment-421061800)_

Hi @dtkav ,

How can i use this now to validate my yaml files.?
Because i got stuck up in this error.

json.loads(urlopen(uri).read().decode("utf-8"))

when it tries to work with yaml files. Any config option available to make it to work with yaml.
When i tried 
yaml.load(urlopen(uri).read().decode("utf-8"))

it worked fine for me.

Please let me know how can i proceed.

Thanks
GuruPrasad
