### ISSUE TITLE
[dev-2.0] "x-openapi-router-controller" support.

### ISSUE THREAD

**Issue by wheelsandmetal** [zalando/connexion#683]
Openapi Generator has a x-openapi-router-controller param for routing in the generated yaml spec file. Would it be possible to support this alongside x-swagger-router-controller?

I did a quick test and added the line 
`self._router_controller = self._operation.get('x-openapi-router-controller')`
 after
`self._router_controller = self._operation.get('x-swagger-router-controller')`
 in abstract.py and this successfully fixed the problem. 

Would this be the correct way to fix this issue or should the generator use x-swagger-router-controller?

**Comment by dtkav** [comment]
Good idea. We'll probably still need to support x-swagger-router-controller for backwards compatibility.
Can you make a pull request? I'm happy to review it.

**Comment by dtkav** [comment]
Hey @wheelsandmetal , can you test out and review #688 ? Thanks!
