### ISSUE TITLE
[dev-2.0] setting Api(base_path=...) does not work with swagger-ui-bundle

### ISSUE THREAD

**Issue by dtkav** [zalando/connexion#692]
Setting `Api(base_path=...)` doesn't work with `swagger-ui-bundle==0.0.2`. Swagger-ui does not get the correct base_path, and so cannot hit the API.

For example, add `my_api.yml` under `/v0`, and add swagger ui in `/v0/ui`.
```
app.add_api('my_api.yml', base_path='/v0', strict_validation=True, validate_responses=True)
```

I you click `Try it out` and the `Execute` in swagger ui, the request is sent to API without `base_path` (`/v0` in this case).

_Adapted from a post by @czchen in https://github.com/zalando/connexion/pull/619#issuecomment-423217816_

**Comment by dtkav** [comment]
This is because the `openapi.yaml` file that is served up is the `raw_spec` (i.e. the unmodified spec from disk).
I should be able to fix it relatively easily.

**Comment by dtkav** [comment]
Hmm.. while this is straightforward to fix for `swagger 2` specs, It's actually much less straightforward in `openapi 3` because of the [servers block](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject).
I guess the expected behavior would be to modify each server url, and prepend the base_path to the url path?
The server block isn't supported all that well in general (no templating yet, etc).

**Comment by dtkav** [comment]
This is the only thing in connexion that actually modifies the spec before serving it, which is very weird to me.

I think a much better solution would be to move this to 'arguments' and rely on the existing templating functionality.

ex. someone would put in their swagger 2 spec:
```
basePath: {{ base_path | default('') }}
```
and then
```
app.add_api('swagger.yaml', arguments={"base_path": "/api/v1"})
```
This would me much cleaner because the templating happens at spec load time.

**Comment by dtkav** [comment]
One of the reasons I'm struggling with this a bit is I don't have a clear picture of what the use case of `FlaskApi(base_path=...)`.

The thing that makes sense to me is that you override the `base_path` of your api _without_ modifying the spec. See the below use case as to why that makes sense to me.

What I don't get is why you would want to supply the `base_path` and have it modify the spec (which is what connexion does right now on master). Yes, modifying the spec causes swagger-ui make correct requests (as @czchen notes), but why wouldn't you specify the `basePath` in the spec in the first place?

# use case: path-modifying application load balancer
```
http://server1.something.tld/v2/
http://server2.something.tld/v2/
http://server3.something.tld/v2/
```
and then they are exposed by an application load balancer at
```
https://external.something.tld/service/v2/
```
In this case, the important thing is that connexion configures its routes to serve up content at `/v2/...`
The annoying thing is that the servers block is a `list`, and json doesn't guarantee ordering of lists, so we may start the server and it would register `/service/v2/`.

I think this is the use case for specifying the `base_path`. However, in the current connexion release, this will _overwrite_ the spec.
It seems to me that you would want to serve up the spec unmodified. This way you have the ability to set the `base_path` and still use a path-changing application load balancer.

# Help
Given my current context and understanding, this issue is a feature, and not a bug.
I'd really appreciate if someone can enlighten me on this feature, and their use case so I don't accidentally break something critical!

**Comment by dtkav** [comment]
I think part of the confusion is that connexion interprets the `basePath` in swagger 2.0 to be _for the server_.
But in the OpenAPI 3 spec, the servers block seems to be _for the client_. Each instance off connexion will only be implementing _one_ of the servers in the servers block.

The problem is, we don't know _which_ server we are implementing.

AFAICT there are two solutions to this problem:
1. Overwrite the servers block (ha ha I'm the only server now :smiling_imp: !). This is bad for the client.
2. Require the user to pass in which server we are implementing, so we know which operations we are meant to handle, and which routes to handle them on.

**Comment by jmcs** [comment]
@dtkav we can remove support for basePath in OpenAPI while keeping it for Swagger 2. That way we don't break anything that's working right now.

**Comment by dtkav** [comment]
The PR that was merged implements option 1 above (overwrites servers block).
This is probably fine for now. If anyone find themselves running into trouble with a "microservice gateway"-like 3.0 spec (i.e. one that represents multiple servers), then I guess we can add more support as the need arises.
I'll close this for now.

**Comment by trickidicki** [comment]
I have a use-case which is not currently working (Connexion v 2.0.2)

I am deploying an AWS service with multiple defined 'stages' - dev, test, prod. The URL for the service is:
`https://<random>.<region>.amazonaws.com/dev/index.html`

If I set basePath to `/dev/api/v1.0` then Connexion tries to serve the spec at:

`https://<random>.execute-api.<region>.amazonaws.com/dev/dev/api/v1.0/openapi.json`

and render the UI at

`https://<random>.<region>.amazonaws.com/dev/dev/api/v1.0/ui/`

Note the double `dev/dev` in the URL. The Swagger UI renders but with the error "Failed to load API definition. Not Found /dev/api/v1.0/openapi.json"

If I manually change the URL is the SwaggerUI to `/dev/dev/api/v1.0/openapi.json` it renders the spec, but the 'server' drop-down still says `/dev/api/v1.0` so none of the test requests go to the right URL.

Test request URL: 

`curl -X GET "https://<random>.execute-api.<region>.amazonaws.com/dev/api/v1.0/myapi" -H "accept: application/json"`

403 Forbidden

---

If I set the basePath to `/api/v1.0` then we get:

Spec URL: `https://<random>.execute-api.<region>.amazonaws.com/dev/api/v1.0/openapi.json` - correct

Swagger UI: `https://<random>.execute-api.<region>.amazonaws.com/dev/api/v1.0/ui/` - correct

Swagger UI error: `Forbidden /api/v1.0/openapi.json` - error

Change Swagger UI to `/dev/api/v1.0/openapi.json`, spec is rendered but 'Server' dropdown says `/api/v1.0` - error

Test request URL: 

`curl -X GET "https://<random>.execute-api.<region>.amazonaws.com/api/v1.0/myapi" -H "accept: application/json"`

403 Forbidden

Manually changing it to:

`curl -X GET "https://<random>.execute-api.<region>.amazonaws.com/dev/api/v1.0/myapi" -H "accept: application/json"`

200 OK
