### ISSUE TITLE
Unable to suppress annoying server requests logging with gevent backend

### ISSUE THREAD

**Issue by micmarty** [zalando/connexion#704]
### Description
Unable to customize annoying logging with `gevent` backend

### Expected behaviour
Switching between logging levels should be clear and maybe handled by connexion itself (backend independent), like:

```python
logging.getLogger('gevent').setLevel(logging.ERROR)
# or
app = connexion.FlaskApp(__name__)
app.app.logger.setLevel(logging.ERROR)
(both of these are not working)
```
### Actual behaviour
I get a huge amount of irrelevant requests information, no matter how I try to customize this default behaviour.
![image](https://user-images.githubusercontent.com/12485656/46285455-d29db400-c57b-11e8-9460-d5faa4fd207e.png)

### Steps to reproduce

Just create some example app and change backend to gevent, like:
```python
# Constants are not relevant here
app.run(server='gevent',
        host=API_SERVER.HOST,
        port=API_SERVER.PORT,
        debug=False)
```

**Full context** for my code:
```python
import logging
import connexion
from tensorhive.config import API, API_SERVER
from tensorhive.database import db_session
from flask_cors import CORS
from tensorhive.authorization import init_jwt

log = logging.getLogger(__name__)
'''
Constants are loaded from other module
API.TITLE = 'TensorHive API'
API.VERSION = 0.2
API.URL_PREFIX = 'api/0.2'
API.SPEC_FILE = 'api_specification.yml'
API.IMPL_LOCATION = 'tensorhive.api.controllers'
'''

class APIServer():
    def run_forever(self):
        app = connexion.FlaskApp(__name__)
        app.app.logger.setLevel(logging.ERROR)
        init_jwt(app.app)

        @app.app.teardown_appcontext
        def shutdown_session(exception=None):
            db_session.remove()

        app.add_api(API.SPEC_FILE,
                    arguments={
                        'title': API.TITLE, 
                        'version': API.VERSION,
                        'url_prefix': API.URL_PREFIX
                    },
                    resolver=connexion.RestyResolver(API.IMPL_LOCATION),
                    strict_validation=True)
        CORS(app.app)
        log.info('[⚙] Starting API server with {} backend'.format(API_SERVER.BACKEND))
        log.info('[✔] API documentation (Swagger UI) available at: http://{host}:{port}/{url_prefix}/ui/'.format(
            host=API_SERVER.HOST, 
            port=API_SERVER.PORT,
            url_prefix=API.URL_PREFIX))
        app.run(server=API_SERVER.BACKEND,
                host=API_SERVER.HOST,
                port=API_SERVER.PORT,
                debug=API_SERVER.DEBUG)


def start_api_server():
    APIServer().run_forever()

if __name__ == '__main__':
    start_api_server()
```

### Additional info, my analysis:
I think the problematic line is:
https://github.com/zalando/connexion/blob/1fbb1ff941dee089dcf881ef46bcb079ac52502a/connexion/apps/flask_app.py#L112

Explanation (http://www.gevent.org/api/gevent.pywsgi.html):
> log – If given, an object with a write method to which request (access) logs will be written. If not given, defaults to sys.stderr. You may pass None to disable request logging.

So it looks like you need to pass additional parameter to the WSGI constructor -> overriding default logging method

**If you have some simple workaround for this, I'll be very grateful!**

### Output of the commands:
- `python --version`
`Python 3.6.6 :: Anaconda, Inc.`
- `pip show connexion | grep "^Version\:"`
`Version: 1.4.2`

**Comment by dtkav** [comment]
Yikes, It looks like gevent pywsgi was unable to use standard python logging facilities because of locks in the library.
Luckily connexion passes `**options` to the underlying wsgi server.
We just need to pass it something with a callable `write` attribute:
```python
class devnull:
    write = lambda x: x

app.run(server=API_SERVER.BACKEND,
        host=API_SERVER.HOST,
        port=API_SERVER.PORT,
        debug=API_SERVER.DEBUG,
        log=devnull)
```

**Comment by micmarty** [comment]
✓ Thank you so much, it worked perfectly! Issue can be closed.

**Comment by bhavesh-sr** [comment]
An easier alternative is to set `log=None`
