### ISSUE TITLE
sqlalchemy example raises "sqlite3.OperationalError: no such table: pets"

### ISSUE THREAD

**Issue by vpohl** [zalando/connexion#706]
### **Description**

The sqlalchemy example (under WSL with Ubuntu distribution) raises the following error when queried for the content of `pets` (or any other entry): 

`sqlite3.OperationalError: no such table: pets`

### **Expected behaviour**

Should return an empty list.

### **Actual behaviour**

Returns 500, "Internal Server Error".
```
ERROR:flask.app:Exception on /pets [GET]
Traceback (most recent call last):
  File "/home/user/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/user/conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: pets
```

### **Steps to reproduce**

```
cd connexion/examples/sqlalchemy
python app.py
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/pets'
```

### **Additional info**

This issue has been adressed in: [https://gehrcke.de/2015/05/in-memory-sqlite-database-and-flask-a-threading-trap/](url) The in-memory database can be created on the "wrong" thread and thus, cannot be accessed.

**Fix:**

The simplest solution would be to not use an in-memory database, i.e., replace

https://github.com/zalando/connexion/blob/2b6169aade03e8a9dc7109c7ba7a224b3888e51f/examples/sqlalchemy/app.py#L50

with, for instance,
```
db_session = orm.init_db('sqlite:////tmp/db.sqlite') 
```

Output of the commands:

- `python --version`:  Python 3.6.6 :: Anaconda, Inc.
- `pip show connexion | grep "^Version\:"` Version: 1.5.3

Can also be reproduced for 
- `python --version`:  Python 2.7.12
- `pip show connexion | grep "^Version\:"` Version: 1.5.3

**Comment by dtkav** [comment]
Thanks for the ticket @vpohl , I've put up #709 for your review.
I disabled threading instead of creating a tmpfile.
