### ISSUE TITLE
Problems with array and boolean inputs from query parameters

### ISSUE THREAD

**Issue by kmoppel** [zalando/connexion#71]
Not sure if I'm using connexion incorrectly or it's a bug - from "in: query" input array seems to be just a string and boolean is always True

My test repo examplifying the issues:
https://github.com/kmoppel/connexion-test

**Comment by hjacobs** [comment]
I think at least the "query" parameters with type "array" are now (partly) supported by #90 .

**Comment by rafaelcaricio** [comment]
I cloned your project and everything works as expected on the most recent version [1.0.58](https://github.com/zalando/connexion/releases/tag/1.0.58).

**Comment by hjacobs** [comment]
:+1: great :smile:
