### ISSUE TITLE
[dev-2.0] securitySchemes not passed to operation

### ISSUE THREAD

**Issue by dtkav** [zalando/connexion#711]
### Description
@cziebuhr found that "auth all paths" wasn't working for OpenAPI specs in dev-2.0

### Expected behaviour
Providing securitySchemes should cause them to be used when auth_all_paths is true

### Actual behaviour
securitySchemes is always being set to {} in oas3

### Steps to reproduce
create API with auth_app_paths=True
include securitySchemes
use API as though there's no auth

### Additional info:
#703 includes this, and more
#710 includes just the fix, refactor/cleanup to come

Output of the commands:

- `python --version` 3.6.5
2.0.0rc1

**Comment by jmcs** [comment]
Fixed in `2.0.0rc3`.
