### ISSUE TITLE
Log validation error message

### ISSUE THREAD

**Issue by fpozzobon** [zalando/connexion#714]
### Description

In order to analyse the usual client errors using my API, I would like to log the schema / parameter validation errors.

### Expected behaviour

Getting a log (either debug or info) with the validation error message inside.

### Actual behaviour

As far as I understand, it is not possible to log the validation error messages (400 error) sent to the client (example "Wrong type, expected 'integer' for formdata parameter...").

### Additional info:

Would it make sense for you to add it ?
If yes, log that in Problem.py would it be the correct way to do it ?
Shall we create a specific logger for that use case ?

**Comment by dtkav** [comment]
I these docs might help:
https://github.com/zalando/connexion/blob/1fbb1ff941dee089dcf881ef46bcb079ac52502a/docs/exceptions.rst#default-exception-handling

**Comment by fpozzobon** [comment]
Hi, thanks for the info.
I tried to add a generic problem handler : 
```python
app.add_error_handler(ProblemException, myMethod)
```
but myMethod is not called when getting a "Missing formdata parameter" for example.
I then tried to simply override 400 but same issue...
Not sure why it doesn't do anything in my case... could it be that there is no exception thrown ?

Anyway, I found a workaround to log the failures by using a CustomParameterValidator :

```python
class CustomParameterValidator(ParameterValidator):
    @staticmethod
    def validate_parameter(parameter_type, value, param):
        result = ParameterValidator.validate_parameter(parameter_type, value, param)
        if (result is not None):
            logging.info("Validation failure : " + str(result))
        return result

validator_map = {
    'parameter': CustomParameterValidator
}

connexion.App(__name__, specification_dir='swagger/', validator_map=validator_map)
```

This is not ideal but it will do.
