### ISSUE TITLE
Documentation version is out of date / misleading

### ISSUE THREAD

**Issue by twosigmajab** [zalando/connexion#717]
https://github.com/zalando/connexion#documentation links to https://connexion.readthedocs.io/en/latest/ which appears to be docs for Connexion v0.5 (title of page is "Welcome to Connexion’s documentation! — Connexion 0.5 documentation").

Clicking the "V: latest" to change versions, the latest version available in the popup menu is 1.0.88.

According to https://github.com/zalando/connexion/releases and https://libraries.io/pypi/connexion there have been many releases since then, but apparently the accompanying docs were never published?

**Comment by hjacobs** [comment]
I think this is just a "cosmetic" problem as docs are automatically updated on readthedocs.io, but the version is hardcoded in the Sphinx config file to `0.5` (that's the version of the docs, not of Connexion itself): https://github.com/zalando/connexion/blob/master/docs/conf.py#L54

**Comment by twosigmajab** [comment]
> that's the version of the docs, not of Connexion itself

Is this intentional? Expected use is not to hard code some different version there, but rather to give the docs the same version as the package they're documenting. Like this:
https://github.com/requests/requests/blob/master/docs/conf.py#L69

Doing otherwise is really confusing.

When you click the version chooser ("V: latest") widget, the popup should allow you to easily choose the docs for the Connexion version you're trying to learn about, i.e. the choices should correspond to what's on https://github.com/zalando/connexion/releases

**Comment by twosigmajab** [comment]
Congrats on the 2.0 release! Noticed the page title of https://connexion.readthedocs.io/en/latest/ is still "Welcome to ... Connexion 0.5 documentation", which is actually two major versions behind the latest vesrion. (And the version chooser widget doesn't show anything for version 2.)
