### ISSUE TITLE
Mismatch between Swagger's curl command and the Accept header received by the server

### ISSUE THREAD

**Issue by kenneho** [zalando/connexion#722]
### Description

Consider this API yaml extract:

    /users
       put:
          produces:
             - "application/json;version=1"

In Swagger, the "Parameter content type" lists "application/json". When I execute the PUT command in Swagger, the `curl` command displays a different Accept header than what the server receives. The server receives `Accept: application/json;version=1`, even though the `curl` command in Swagger says it's using `Accept: application/json`

### Expected behaviour

The `curl` command's Accept header should match what the Accept header registered on the server. 

### Actual behaviour

The `curl` command's Accept header is `application/json`, while the server says the Accept header is `application/json;version=1`.

### Additional info:

When I copy/paste the curl command into a terminal an run it, my API throws an expected 406 error, since the Accept header `application/json` is not supported. 

Output of the commands:

- `python --version`: 3.7.0
- `pip show connexion | grep "^Version\:"`: 1.5.3

**Comment by dtkav** [comment]
Correct me if I'm wrong, but is this a bug in swagger-ui?
If so, then you'll want to file this over at https://github.com/swagger-api/swagger-ui

**Comment by dtkav** [comment]
Closing because I believe this is a bug in swagger-ui.
Please re-open if I missed something.

**Comment by kenneho** [comment]
Sorry for the late reply. The bug might be with the swagger-ui, so I'll report the issue there when I get the chance, and see how it goes. 

Thanks for the follow-up, though!
