### ISSUE TITLE
Can not access requests headers as stated in the documentation

### ISSUE THREAD

**Issue by jsvachon2** [zalando/connexion#723]
### Description
Documentation says that we should be able to access request's headers through something like the following:
    page_number = connexion.request.headers['Page-Number']

I tried to access headers through both connexion and flask and got the same result

### Expected behaviour
Receive the header's value

### Actual behaviour
I am receiving the message:

Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

### Additional info:

Output of the commands:

- `python --version` = Python 2.7.15rc1
- `pip show connexion | grep "^Version\:"` = Version: 1.5.3

**Comment by jsvachon2** [comment]
Never mind.. the code works just fine when it is located inside the handler function

**Comment by hjacobs** [comment]
Good you figured it out yourself :smile:

**Comment by kangame** [comment]
Hi guys,

Am struggling to have parameter and jwt token (via header) in this basic example:

### app.py

def get_param_and_token(**kwargs):
    try:
        auth = connexion.request.headers["Authorization"]
        print("-------------------------------------------------" + str(auth))
        data = kwargs.get("body")
        response = my_logic.compute(data)
        return web.json_response(response)
    except Exception as ex:
        print("Exception : {}".format(ex))
        return web.HTTPInternalServerError()

connexion_app = connexion.AioHttpApp(__name__, specification_dir='my-api/src/main/resources')
connexion_app.add_api('my-api.yaml', resolver=RestyResolver('api'), validate_responses=True)

if __name__ == '__main__':
    port = 8080
    if len(sys.argv) > 1:
        port = sys.argv[1]
    # run our standalone aioHttp server
    connexion_app.run(port=port)

### and my-api.py

paths:
  /test-get-token:
    post:
      operationId: app.get_param_and_token
      tags:
        - "create"
      summary: "Get param and token from request"
      description: ""
      security:
        - bearerAuth: []
      requestBody:
        description: "Param"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParamDescription"

### Got the following error:

Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

### Working with
openapi: "3.0.0"
connexion==2.5.1
Python 3.6.9

Do you have any idea of whats wrong ? May be re open the issue .. ?

**Comment by kangame** [comment]
Figured out in #1210
