### ISSUE TITLE
Connexion 2.0 release candidate: got an unexpected keyword argument 'resolver'

### ISSUE THREAD

**Issue by kenneho** [zalando/connexion#729]
### Description

I upgraded my Connexion project to use the Connexion 2.0 release candidate, and apparently the new version doesn't implement the `resolver` argument in the `FlaskApp` constructor. 

This code work for Connexion < 2.0, but not for the Connexion 2.0 release candidate:

    connexion_app = connexion.FlaskApp(__name__, specification_dir='swagger/', resolver=RestyResolver('apis'))

### Expected behaviour

No syntax errors. 

### Actual behaviour

    Traceback (most recent call last):
       File "./server/__init__.py", line 12, in create_app
          connexion_app = connexion.FlaskApp(__name__, specification_dir='swagger/', resolver=RestyResolver('apis'))
       File "/usr/local/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 21, in __init__
           super(FlaskApp, self).__init__(import_name, FlaskApi, server=server, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'resolver'

### Steps to reproduce

1. `pip install --pre connexion[swagger-ui]`
2. Run the code in the "description" section

### Additional info:

Output of the commands:

- `python --version`: 3.7.0

**Comment by dtkav** [comment]
This functionality existed 'accidentally', as it was sneaking through `old_style_options**` pre connexion 2.0, which passed all kwargs through to the `api_cls`.

I think it makes sense to be able to define a default resolver for the whole App though, so I'm happy to add that functionality explicitly.

**Comment by dtkav** [comment]
Hey @kenneho - Please check out #735 when you get a chance.

**Comment by jmcs** [comment]
@kenneho this should be fixed in `2.0.0rc5`.

**Comment by kenneho** [comment]
Sound great. I'm busy on another project at the moment, but will get back to you as soon I as get a chance to test the new rc.

**Comment by dtkav** [comment]
This is fixed in the 2.0 release.
Please reopen if you continue to have problems.
