### ISSUE TITLE
ResolverError: Empty module name

### ISSUE THREAD

**Issue by trickidicki** [zalando/connexion#733]
### Description

Trying the basic example in readme.md

### Expected behaviour

Should work.

### Actual behaviour

Throws exception:
```
ERROR:connexion.apis.abstract:Failed to add operation for GET /v1/pets
Traceback (most recent call last):
  File "d:\py\env\lib\site-packages\connexion\apis\abstract.py", line 315, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "d:\py\env\lib\site-packages\connexion\apis\abstract.py", line 273, in add_operation
    **shared_args)
  File "d:\py\env\lib\site-packages\connexion\operations\swagger2.py", line 96,
in __init__
    pass_context_arg_name=pass_context_arg_name
  File "d:\py\env\lib\site-packages\connexion\operations\abstract.py", line 99,
in __init__
    self._resolution = resolver.resolve(self)
  File "d:\py\env\lib\site-packages\connexion\resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "d:\py\env\lib\site-packages\connexion\resolver.py", line 66, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Empty module name>
```

### Steps to reproduce

On Windows 10, Python 3.6 64 bit

### Additional info:

On Windows 10, Python 3.6 64 bit

Output of the commands:

- `python --version`
Python 3.6.7rc1

- `pip show connexion | grep "^Version\:"`
Version: 2.0.0rc3
(same with 1.5.3)

**Comment by trickidicki** [comment]
Thank you, that resolves it. Perhaps the "Running it" section in the readme should be updated as there is more to it than the 4 lines of code shown there.
Many thanks!

**Comment by dtkav** [comment]
Glad it worked for you. Thanks for the feedback.

**Comment by peschue** [comment]
I think the error message should be improved. It looks like an error from within the framework, but it is an error in the combination of operationId and user-provided entry points.

**Comment by khera-shanu** [comment]
I agree Flask has great error reporting if you are adding something useful to it, don't ruin the best parts of such a good framework.
