### ISSUE TITLE
url contains path variable like  /v1/{id}/children   return 404

### ISSUE THREAD

**Issue by LmangoLemon** [zalando/connexion#734]
### Description
there is an url defined like this:   /v1/{id}/children,  when i try to call the url, it return 404. and if the url defined like: /v1/childen，it works properly

what could be the reason?

### Expected behaviour

the url define like  /v1/{id}/children can work properly

### Actual behaviour
the url define like  /v1/{id}/children return 404

### Additional info:

Output of the commands:
connexion == 1.1.15
Python 3.7.0

**Comment by bobh66** [comment]
Did you define a path parameter for {id}?

**Comment by LmangoLemon** [comment]
> Did you define a path parameter for {id}?

yes, i did

and i found the cause.  {id} is defined as number type,  i changed it to string, and it worked properly.

Thanks for replying.

**Comment by qasimalbaqali** [comment]
@LmangoLemon This was my issue as well! Thank you for pointing it out :)
