### ISSUE TITLE
How to add headers to the Response object?

### ISSUE THREAD

**Issue by danballance** [zalando/connexion#74]
Hi guys,

I'm loving this project and hoping to make some contributions. One thing I'm unclear on though, is once I have routed the request to the function listed in operationId, is there any way that I can modify the response object before it is sent to the client?

For example, I would like to add a Location header to my 201 response when a resource is successfully created. I can create a Response object myself and return that - but then I seem to lose the work that you have done - for example setting the Content-Type according to the Swagger spec. It may well be that I am doing something wrong!

Can you help me? Is there a way for the function that I implement to modify the response?

many thanks in advance :)

**Comment by danballance** [comment]
Okay, digging into the code a little more now and I can see that the operationId is the view_func for Flask.add_url_rule.

I can also see that the Operation class uses a series of decorators to transform the view_func response. And according to line 126 of decorators/produces.py when I return a flask.Response object, the code decides to just return my response with no further processing.

So should I be looking at trying to add an additional decorator that will add extra headers? Would anyone be able to point me in the right direction here and I could try and get a pull request together for you next week?

Is this functionality you'd like to see added or should I be approaching this problem differently?

**Comment by hjacobs** [comment]
Do you want to have generic logic of adding the location header (e.g. pointing to "GET" of the same path when doing a PUT)? Where do you decide how to fill the "Location" header?

**Comment by danballance** [comment]
Hi,

So I am trying to find a way to return some headers of my own, along with the response body, from the view_func specified via the operationId. Perhaps some kind of decorator on the view function might work?  Or alternatively maybe some kind of collection could be added as an attribute to the view function? So something like:

def my_view_func():
    pass
my_view_func.headers = list_of_tuples

I'm not sure what would be the best approach. So adding a Location header is my use case here, but I think having the ability to return response headers as well as a response body would be useful in a range of different scenarios.

Does that make more sense to you now?

Dan

**Comment by danballance** [comment]
Hi,

So I am trying to find a way to return some headers of my own, along with the response body, from the view_func specified via the operationId. Perhaps some kind of decorator on the view function might work?  Or alternatively maybe some kind of collection could be added as an attribute to the view function? So something like:

def my_view_func():
    pass
my_view_func.headers = list_of_tuples

I'm not sure what would be the best approach. So adding a Location header is my use case here, but I think having the ability to return response headers as well as a response body would be useful in a range of different scenarios.

Does that make more sense to you now?

Dan

**Comment by danballance** [comment]
Hi there,

I've been thinking a bit more about this. I can see in the code that a tuple of length 2 is returned from the view function. I was thinking of modifying BaseSerializer.get_data_status_code to handle a tuple of length 2 or 3 - with the third element being a list of tuples of additional headers. Once the Response object has been generated, if the headers are not an empty list, then these headers are added to the response before Produces and Jsonifier return.

Would a technique like this of adding optional headers from the view function be of interest to you? If you like I could write this and open a pull request?

Dan

**Comment by danballance** [comment]
Okay, looks like I should have referenced this issue in my pull request to link this issue in. Since I didn't do that, here's the link:

https://github.com/zalando/connexion/pull/77

**Comment by hjacobs** [comment]
@danballance thanks for the PR, we'll check it :smile:

**Comment by jmcs** [comment]
#77 was already merged.
