### ISSUE TITLE
x-nullable ignored in arrays

### ISSUE THREAD

**Issue by heinen** [zalando/connexion#741]
### Description
If x-nullable is used to specifiy that a single element can be zero, it works. If the type is 'array', though, and x-nullable is used in the items, I get a response 400 - > "None is not of type integer" (assuming the items in the array are ints).

### Expected behaviour
If a single element can be nullable, so should elements in an array be

### Actual behaviour
Elements in arrays cannot be null

### Steps to reproduce
Using this api.yaml:
```
swagger: "2.0"
info:
  description: "debug"
  version: "1.0"
  title: "Debug"

paths:
  /predict:
    post:
      operationId: debuglib.predict
      parameters:
        - in: body
          name: order
          schema:
            $ref: '#/definitions/some_object'
      responses:
        200:
          description: OK

definitions:
  some_object:
    type: "object"
    properties:
      some_element:
        type: "array"
        items:
          type: 'integer'
          format: 'int32'
          x-nullable: True
```

I can post `{'some_element': [1, 2]}` but I cannot post `{'some_element': [1, null]}`.
Specifically, I call:
```
import requests
r = requests.post("http://localhost/predict", json={'some_element': [1, 2]})  # works
r = requests.post("http://localhost/predict", json={'some_element': [1, None]})  # does not work
```

### Additional info:
I'm fairly new to web dev, maybe I'm missing something here but this seems like very unintuitive behavior.

Output of the commands:

- `python --version`: Python 3.6.3 :: Anaconda custom (64-bit)
- `pip show connexion | grep "^Version\:"`: Version: 1.5.3

**Comment by dtkav** [comment]
Can you try this on the Connexion 2.0 release candidate? All of the nullable logic has been reworked.
You can install it with `pip install --pre connexion[swagger-ui]`

**Comment by dtkav** [comment]
I can confirm this is fixed in connexion 2.0 (44ea933)

debuglib.py
```
def predict(order):
    return order
```
start server
```
$ connexion run api.yaml
```
curl
```
$ curl http://localhost:5000/predict -d '{"some_element": [1, 2]}' -H 'Content-Type: application/json'
{
  "some_element": [
    1,
    2
  ]
}
```
```
$ curl http://localhost:5000/predict -d '{"some_element": [1, null]}' -H 'Content-Type: application/json'
{
  "some_element": [
    1,
    null
  ]
}
```
```
$ curl http://localhost:5000/predict -d '{"some_element": null}' -H 'Content-Type: application/json'
{
  "detail": "None is not of type 'array'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

**Comment by heinen** [comment]
Yes, that works as expected with connexion `Version: 2018.0.dev1`. Is there a timeline for the release?

**Comment by dtkav** [comment]
it was just released!

**Comment by heinen** [comment]
Awesome, thanks!
