### ISSUE TITLE
/ui/ endpoint no longer available in Connexion 2.0

### ISSUE THREAD

**Issue by RogerTangos** [zalando/connexion#751]
### Description
Connexion 2.0 seems to hide the /ui/ endpoint.

After upgrading from connexion 1.5.3 to connexion 2.0.0, I am no longer to see the SWAGGER interface in /ui/. I've tried both my own code and an [example project](https://github.com/zalando/connexion/tree/master/examples/swagger2/sqlalchemy)

### Expected behaviour
The swagger interface should show

### Actual behaviour
404 error

### Steps to reproduce
Run the [sqlalchemy](https://github.com/zalando/connexion/tree/master/examples/swagger2/sqlalchemy) example, exactly as directed in the readme

### Additional info:
- `python --version`: Python 3.6.1
- `pip show connexion | grep "^Version\:"`: 2.0.0

**Comment by hjacobs** [comment]
You need to install with `connexion[swagger-ui]' now as it no longer includes Swagger UI by default. See https://github.com/hjacobs/connexion-example/pull/11 as example.

**Comment by dtkav** [comment]
I've updated the [release notes](https://github.com/zalando/connexion/releases/tag/2.0.0
) to include this information.

Thanks for taking the time to file this ticket. If you're curious about the history of this issue, you can ead up on the discussion in #406 .

**Comment by BLooperZ** [comment]
Trying to do `pip install connexion[swagger-ui]` gets 
> connexion 2.0.1 does not provide the extra 'swagger-ui'

**Comment by cigano** [comment]
@BLooperZ's hint was fundamental for Heroku. Besides, connexion[swagger-ui] uses version 0.0.2 of the bundle, while `swagger_ui_bundle` is at version 0.0.5.
