### ISSUE TITLE
`add_api` fails with a dict specification with TypeError

### ISSUE THREAD

**Issue by RacingTadpole** [zalando/connexion#756]
### Description

After updating to swagger 2.0.0, I get a `TypeError` when I call `app.add_api` with a spec dict.

### Expected behaviour

I do not receive an error.

### Actual behaviour

I receive `TypeError: expected string or bytes-like object` on the `add_api` call.

### Steps to reproduce

swagger file:
```yaml
swagger: "2.0"
info:
  title: Example
  description: Example
  version: "1"
paths:
  /about:
    get:
      produces:
        - application/json
      responses:
        200:
          description: About the API.
          schema:
            $ref: "#/definitions/about"
definitions:
  about:
    type: object
```

`application.py`:
```
import connexion
app = connexion.App(__name__)
import yaml
with open(swagger_path) as swagger_file:
    swagger_spec = yaml.safe_load(swagger_file)
app.add_api(swagger_spec)
```

It appears to be a problem validating a regular expression, where it expects the `200` to be a string:
```
pattern = '^([0-9]{3})$|^(default)$|^x-', string = 200, flags = 0
.../python3.6/re.py(182)search()
-> return _compile(pattern, flags).search(string)
```

If I change all the response status codes from numbers to strings in the swagger file, eg. replace `200` with `"200"`, then it works.

### Additional info:

Output of the commands:

- `python --version`: `Python 3.6.5`
- `pip show connexion | grep "^Version\:"`: `Version: 2.0.0`

**Comment by dtkav** [comment]
I can take a look at this tomorrow.
The problem is that yaml allows you to have numeric keys, but json does not.

As a workaround, if you just pass the path to the file it will work.
Another option is to change the response codes to strings in your spec.

Here's how the loader works:
https://github.com/zalando/connexion/blob/44ea9336fe79ddb9592942b405a663d2e3aa612c/connexion/apis/abstract.py#82

**Comment by dtkav** [comment]
Please take a look at #763 when you get a chance!

**Comment by RacingTadpole** [comment]
Awesome - thanks!
