### ISSUE TITLE
Documentation/release notes don't say that Connexion supports OpenAPI 3.0

### ISSUE THREAD

**Issue by uipo78** [zalando/connexion#768]
### Description

Given that [this issue was resolved and released in 2.0](https://github.com/zalando/connexion/issues/420), the documentation/release notes should probably be updated accordingly. Neither seems to mention that Connexion supports OpenAPI 3.0 ([check out the top of the welcome page](https://connexion.readthedocs.io/en/latest/index.html)).

**Comment by dtkav** [comment]
Thanks for the ticket!
I've update the release notes for https://github.com/zalando/connexion/releases/tag/2.0.0
I've also opened a PR (#771) which includes a sweep through the documentation.
