### ISSUE TITLE
token info passed as token_info argument to handler function, safe to use?

### ISSUE THREAD

**Issue by herrwagner** [zalando/connexion#775]
### Description
I try to use the basic authentication feature of connexion 2.0. I figure out that currently not only the  sub entry of the token info is passed as user argument to the handler function but also the hole token as token_info argument. Which is great because i need some additional information from the user authentication function passed to the handler function.

Is this intended and just not documented or must i be aware that this will removed in the future?

**Comment by dtkav** [comment]
@cziebuhr reworked that part, so they would know best. We'll try very hard in general to not break the interface until the next major version bump. The are some minor bugfixes that are still coming in, but everything should be pretty solid after that.

**Comment by cziebuhr** [comment]
This feature has already been there for oauth2, I just reused the same mechanism for all authentication schemes. So yes, it's intended to be used that way.

**Comment by dtkav** [comment]
Hey @herrwagner - I'm going to close out this ticket.
Hopefully you have what you need, otherwise please feel free to re-open it!
