### ISSUE TITLE
Return api from App.add_api ?

### ISSUE THREAD

**Issue by danballance** [zalando/connexion#79]
Hi,

I promise not to flood you with spammy pull requests, but would you be willing to accept another small change? I need access to the Swagger spec in other parts of my application. Now I could parse the yaml spec again myself, but seeing as you are already doing the Jinja2 parametrization, it makes sense to me to do this in just one place.

The processed spec is stored in Api.specification. Would you mind if I got App.add_api to return the generated api so that I can then get hold of the Swagger spec? I could then use this in the view parts of my application.

Does that sound a reasonable change to you guys? Or is there a better way to get hold of the Swagger specification in the view functions?

**Comment by hjacobs** [comment]
Yeah, I think app.add_api(...) can return the "Api" instance --- sounds good to me :smile:

**Comment by hjacobs** [comment]
@jmcs already did a PR to fix this issue: add_api now returns the API object :point_right: https://github.com/zalando/connexion/commit/144da03f50fd0f330eb1ccf324b43981814f3d3e
