### ISSUE TITLE
connexion run --stub raises exception when module doesn't exist

### ISSUE THREAD

**Issue by reece** [zalando/connexion#796]
### Description
Running connexion with stubs using the helloworld demo raises 
`ModuleNotFoundError: No module named 'hello'`

Secondary and tertiary exceptions are also raised why handling the above exception:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "hello.post_greeting"! Import error was "No module named 'hello'">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/home/reece/projects/variation-registry/venv/3.6/lib/python3.6/site-packages/connexion/apis/flask_utils.py", line 42, in convert_path_parameter
    swagger_type = types.get(name)
AttributeError: 'list' object has no attribute 'get'
```

### Expected behaviour
My understanding is that `--stub` is supposed to add dummy functions to any unimplemented methods. In this case, no methods (and no module) is implemented at all. I was expecting `--stub` to add dummy responses to all endpoints so that I could view the ui rendering.

### Actual behaviour
Three exceptions, above.

### Steps to reproduce

$ wget -nd https://raw.githubusercontent.com/zalando/connexion/master/examples/openapi3/helloworld/openapi/helloworld-api.yaml

$ connexion --version
Connexion 2.0.2

$ connexion run helloworld-api.yaml --stub --debug
(errors as shown above)

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.7

- `pip show connexion | grep "^Version\:"`
Version: 2.0.2

**Comment by dtkav** [comment]
Thanks for the ticket @reece - please have a look at #800 and see if that fixes your issue.

That stack trace was a bit convoluted - the first two exceptions were expected, and the actual error was in the last exception.

**Comment by reece** [comment]
@dtkav I confirmed that #800 (f6dfeef) fixes the exception and that the swagger ui rendering works. Thanks for the quick fix!
