### ISSUE TITLE
Passing access_log_class option to aiohttp

### ISSUE THREAD

**Issue by lucas03** [zalando/connexion#807]
### Description

I wanna pass custom formatting to access logs. I could not find an option to do that.

gunicorn config:
```
import os
import multiprocessing

workers = multiprocessing.cpu_count() * 2 + 1
worker_class = "aiohttp.worker.GunicornUVLoopWebWorker"
proc_name = "score_machine"

bind = ":8080"
accesslog = "-"  # send access log to stdout
```

app.py:
```
def create_app():
    connexion_app = AioHttpApp(
        __name__,
        specification_dir="schema/",
        options={"swagger_ui": True},
    )
    connexion_app.add_api(
        "schema.yml",
        validate_responses=True,
        strict_validation=True,
        resolver=RestyResolver("kw.score_machine.handlers"),
    )

    return connexion_app.app


application = create_app()
```

custom [access log class](https://docs.aiohttp.org/en/stable/logging.html):
```
from aiohttp.abc import AbstractAccessLogger

class AccessLogger(AbstractAccessLogger):

    def log(self, request, response, time):
        self.logger.info(f'{request.remote} '
                         f'"{request.method} {request.path} '
                         f'done in {time}s: {response.status}')
```

running server -> `gunicorn kw.score_machine.app --config=.misc/gunicorn_config.py`. FYI: There is related issue to `access_log_class` in [aiohttp](https://github.com/aio-libs/aiohttp/issues/3158).

### Expected behaviour

I could just put it to options as `access_log_class=AccessLogger` or `handler_args={ 'access_log_class': AccessLogger}`

### Actual behaviour
I guess it's not supported?

### Additional info:

Output of the commands:

- connexion version: 2.0.2

**Comment by dtkav** [comment]
@dutradda do you know how to do this?

**Comment by pando85** [comment]
I found in [code](https://github.com/zalando/connexion/blob/master/connexion/apps/aiohttp_app.py#L71) that you can do this doing:
```python
    app.run(port=8080, access_log=your_access_log)
```

**Comment by lucas03** [comment]
I saw this, but I am not running app, gunicorn is AFAIK. But I guess I did not dig deep enough here.

**Comment by pando85** [comment]
@lucas03 Don't use gunicorn with aiohttp, from [docs](https://docs.aiohttp.org/en/stable/deployment.html#nginx-gunicorn): `running aiohttp application under gunicorn is slightly slower`

Async implementation works better with python bin...

**Comment by lucas03** [comment]
> running aiohttp application under gunicorn is slightly slower

If I wanna sacrifice slower app for gunicorn perks?

**Comment by pando85** [comment]
Yea, it's your choose, sorry.

**Comment by lucas03** [comment]
OK, I'm resolving this issue. Thanks
