### ISSUE TITLE
No sdist available for current release

### ISSUE THREAD

**Issue by sscherfke** [zalando/connexion#808]
For the current 2.0.2 release, there is no source distribution (sdist) available.

Is this on purpose or has this just been forgotten?

Sdists are needed for redistributing connexion, e.g., via Conda, apt or dnf.

**Comment by jmcs** [comment]
`2.1.0` has a [source distribution](https://files.pythonhosted.org/packages/c1/fb/27f6183af251b9ca1075bbc1d8cf451e69838492805493547e8e6c9e9095/connexion-2.1.0.tar.gz). I don't know what went wrong with the `2.0.2` release, sorry.
