### ISSUE TITLE
No validation for path and query parameters with schemas

### ISSUE THREAD

**Issue by coreyjrobins** [zalando/connexion#811]
### Description
There doesn't seem to be any validation occurring for path or query parameters -- the schema does not get validated. I traced this through, and it looks like the schema actually gets overlooked in jsonschema/validators.py (so this may be an issue for jsonschema), because there is no validator for key "schema" in Draft4Validator, and therefore the entire schema is not validated. 

I used the following code to test:

yaml:
```
openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:5000

paths:
  /test/{test_path_param}:
    post:
      summary: Test
      description: Test
      operationId: helloworld.test_example
      parameters:
        - name: test_path_param
          in: path
          description: Test path param
          required: true
          schema:
            type: string
            enum: [test, testing, tester]
      responses:
        200:
          description: response
          content:
            text/plain:
              schema:
                type: string
```

app code:
```
import connexion

def test_example(test_path_param):
    return test_path_param

app = connexion.FlaskApp(__name__, specification_dir='openapi/')
app.add_api('helloworld.yaml')
app.run(port=5000)
```

### Expected behaviour
When a POST request is made to `http://localhost:5000/test/INVALID`, 400 BAD REQUEST should be returned.

### Actual behaviour
When a POST request is made to `http://localhost:5000/test/INVALID`, 200 SUCCESS is returned, as well as "INVALID", which is the path parameter that was passed in.

### Steps to reproduce
See code above.

### Additional info:

Output of the commands:

- `python --version` 
Python 2.7.15rc1
- `pip show connexion | grep "^Version\:"`
Version 2.0.2

**Comment by dtkav** [comment]
Hey @coreyjrobins thanks for filing this issue.
I was able to reproduce it locally, and I've put up a PR to fix it.
Please have a look at #821 and let me know if it fixes it for you as well.
