### ISSUE TITLE
Add /.well-known/schema-discovery route for queries from TWINTIP

### ISSUE THREAD

**Issue by chutium** [zalando/connexion#82]
many exceptions regularly appeared on our applications, we find they were caused by the queries from TWINTIP (https://docs.stups.io/en/latest/components/twintip.html)

we need to create a dummy response of "/.well-known/schema-discovery" for each applications, most of them are using connexion.

so it will be nice if connexion can handle those TWINTIP queries internally, or provide a template or something to users, so that we can easily fill some text and connexion generate the response internally.

**Comment by elezar** [comment]
Could one add the routes when an API is added using a call to ```add_api``` returning the required information from the api? 

What happens when one calls ```add_api``` multiple times (specifying different ```.yaml``` files each time)?

**Comment by hjacobs** [comment]
@chutium I think adding (at least allowing "opt-in") the schema-discovery URL is a good idea

**Comment by hjacobs** [comment]
For background explanation: the "/.well-known/schema-discovery" URL (https://docs.stups.io/en/latest/components/twintip.html) is our Zalando STUPS way of discovering Swagger API definitions. The STUPS TWINTIP service is regularly scanning all deployed application endpoints to find Swagger API definitions.

**Comment by hjacobs** [comment]
FYI: There is also an ongoing discussion about allowing multiple Swagger API definitions per service, see https://github.com/zalando-stups/twintip-crawler/issues/5

**Comment by hjacobs** [comment]
@chutium I now see your problem more clearly: I guess the real problem is Connexion logging HTTP 401 (unauthenticated) as "ERROR", we probably should reconsider and use "INFO" log level (as it's a client error and should not spam the server logs)

**Comment by hjacobs** [comment]
@chutium see #83

**Comment by rafaelcaricio** [comment]
Can we close this issue?

**Comment by hjacobs** [comment]
Yes, let's close it.
