### ISSUE TITLE
Need variable to alter spec path in Swagger UI Explore bar

### ISSUE THREAD

**Issue by bhechinger** [zalando/connexion#820]
I'm deploying an API written in Swagger (OAS3) behind AWS API Gateway. I can't import it into API Gateway because it seems as if they still only support 2.0.

That's fine. I don't mind that so much, but the problem is it messes with my Swagger UI. API Gateway puts the stage name in the URL but the swagger/connexion app isn't able to "see" this. As a result the Explore bar has the wrong path to the spec file.

It loads up with `/swagger_url/openapi.spec` but needs to be changed to `/aws_stage_name/swagger_url/openapi.spec` in order to load properly in the console.

I took a look at the ui stuff myself but am not a front end guy so had absolutely no idea what I was looking at. :)

**Comment by bhechinger** [comment]
I'll copy the comments here, I accidentally put them on the PR (although that's not necessarily wrong)

That fixes the Explore bar nicely so the spec is loaded into the UI Console.

That also sets the link to the spec file correctly.

The Try it out section still has the wrong URL, however.

**Comment by dtkav** [comment]
Hey @bhechinger - If you don't mind having another look at #823 I'd appreciate it.
It includes examples for both flask and aiohttp.
