### ISSUE TITLE
Response validation fails when using `problem`

### ISSUE THREAD

**Issue by alexjg** [zalando/connexion#838]
### Description
When returning a custom error using `connexion.problem` response validation fails. 

### Expected behaviour

For example, given the following openapi 3.0 spec:

```yaml
openapi: "3.0.0"
info:
  title: "Some API"
  version: "0.0.1"
servers:
- url: /
paths:
  /somepath:
    post:
      summary: "Post something"
      operationId: app.post_something
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
```

And sample application (in `app.py`)

```python
import connexion
import logging.config

logging.config.fileConfig("logging.ini")


def post_something():
    return connexion.problem(400, "Bad Request", "so bad")


app = connexion.FlaskApp(
    __name__,
    specification_dir="./")
app.add_api("openapi.yaml", validate_responses=True)
app.run(port=8080)
```

We should get a 400 response when POSTing to `http://localhost:8080/somepath`

### Actual behaviour

We get a `500` response with an error indicating that response validation failed. 

### Steps to reproduce

See above

### Additional info:

This looks to be due to these lines in `connextion/decorators/response.py`

```python
        if self.is_json_schema_compatible(response_schema):
            v = ResponseBodyValidator(response_schema, validator=self.validator)
            try:
                data = self.operation.json_loads(data)
                v.validate_schema(data, url)
            except ValidationError as e:
                raise NonConformingResponseBody(message=str(e))
```

Here `operation.json_loads(data)` is returning `None`. But I'm not sure in what circumstance it would not do that.

Output of the commands:

- `python --version`: `Python 3.7.1`
- `pip show connexion | grep "^Version\:"``Version 2.2.0`

**Comment by lsorber** [comment]
This might be because `connexion.problem` generates a response with content type `application/problem+json`, while your specification requires the response's content type to be `application/json`.

**Comment by alexjg** [comment]
Nice, setting the content type to `application/problem+json` does seem to solve the problem. Thanks!
