### ISSUE TITLE
Accepting JSON input?

### ISSUE THREAD

**Issue by deeplook** [zalando/connexion#852]
I see only YAML as accepted input, but the API specs I usually deal with are all in JSON. Is there any recommended way to work with JSON input?

**Comment by dtkav** [comment]
JSON is a subset of YAML, are you running into an error?

**Comment by dtkav** [comment]
I'm going to close this ticket since you haven't responded in a while.
Hope you were able to sort it out!
Please re-open the ticket if you are still having trouble.
