### ISSUE TITLE
Does connexion[swagger.yaml] supports Flask MethodView?

### ISSUE THREAD

**Issue by bharat-gera** [zalando/connexion#864]
### Description
I have developed API using Flask MethodView and wrapped these API using connexion Swagger.yaml, but I'm confused how to point the operationID to a specific http method(GET,POST,PUT).I have tried by just giving the class Name but unable to route request to specific method.

### Expected behaviour
It gives error TypeError: Object of type 'Resource Class Name' is not JSON serializable.

### Actual behaviour
should call that specific method of Resource class.

- Connexion version: 2.2.0

Can anybody help with the issue?

**Comment by dtkav** [comment]
Hey @bharat-gera - there is an open pull request awaiting review here: #847

**Comment by dtkav** [comment]
closing as a duplicate of #359

**Comment by bharat-gera** [comment]
Cool, I missed that pull request. Thanks!
