### ISSUE TITLE
[Question] Approach to swagger-ui documentation of API endpoint that returns a redirect.

### ISSUE THREAD

**Issue by seandavi** [zalando/connexion#865]
### Description

I have an API endpoint that looks like `/path/{id1}/{fname}` that performs a redirect to a signed s3 URL. 

### Expected behaviour

The endpoint returns a 307 and downloads the file as expected using a command-line call like:

```
wget --content-disposition http://example.com/path/id1/abc.tsv
```

It would be nice it the UI could:

1. follow the 307 redirect and download the file.
2. allow replacement of the generated curl command with alternatives.

Short of those two things, is there a mechanism for turning off the "try-it-out" functionality for a single endpoint?

### Actual behaviour

In the UI, a couple of things are problematic. First, the curl command is misleading, as it needs to specify additional command line arguments to work as expected. Second, the redirect is not followed when doing "try it out". 

### Additional info:

`python --version`: `Python 3.6.7`

```
pip show connexion | grep Version
Version: 2.2.0
License: Apache License Version 2.0
```

**Comment by dtkav** [comment]
Hey @seandavi - I think you'll want to file this issue over at https://github.com/swagger-api/swagger-ui
swagger-ui is a (optional) dependency of connexion.

**Comment by seandavi** [comment]
Thx, @dtkav. I thought so, but connexion has a lot of nice bells-and-whistles, so I thought I'd start here first.
