### ISSUE TITLE
oauth_problem_middleware not catching OauthResponseProblem in aiohttpapp

### ISSUE THREAD

**Issue by arastel** [zalando/connexion#875]
### Description

AioHttpApp is shipped with a dedicated [middleware for wrapping oauth errors](https://github.com/zalando/connexion/blob/master/connexion/apis/aiohttp_api.py#L33) in order not to send default 500 responses.
Problem is, OAuthResponseProblem seems not to be included and is then raising an error 500 when the api key is not valid.
From my perspective, adding OAuthResponseProblem as an catched exception should solve this problem.

### Expected behaviour

Providing an api key that is not valid should raise an Unauthorized 401 error.

### Actual behaviour

Error code 500 without custom description is provided

### Steps to reproduce

Using api key authentication managed by a custom x-apikeyInfoFunc, any request without a valid api key will [raise an OauthResponseProblem](https://github.com/zalando/connexion/blob/master/connexion/decorators/security.py#L270) here and won't be transformed in _aiohttp code terminology_. 

### Additional info:

python 3.7.1
connexion 2.2.0
aiohttp 3.5.4

**Comment by arastel** [comment]
Apparently solved in PR for issues #829 and #830

**Comment by dtkav** [comment]
Thanks for digging, and reporting back!
