### ISSUE TITLE
block mapping error 

### ISSUE THREAD

**Issue by Rev0kz** [zalando/connexion#880]
Hello, I tried to run the following swagger.yml but it displayed the following error. I help me out, please.

```
"expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 20, column 7:
          operationId: "authors.read"
          ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 25, column 9:
            200:
 ```           ^

**Comment by dtkav** [comment]
Hey @Rev0kz - It sounds like your yaml is invalid.
You might try pasting it into a linter like this one: http://www.yamllint.com/
Good luck.

**Comment by Rev0kz** [comment]
Thanks, @dtkav. Issue resolved. Thanks again.
