### ISSUE TITLE
Invalid Specification Error

### ISSUE THREAD

**Issue by Rev0kz** [zalando/connexion#884]
###   application/json  is not of type 'array'

Someone help me out........Thanks in advance

    raise InvalidSpecification.create_from(e)
connexion.exceptions.InvalidSpecification: '-"application/json"' is not of type 'array'

Failed validating 'type' in schema['properties']['produces']['allOf'][0]:
    {'items': {'$ref': '#/definitions/mimeType'},
     'type': 'array',
     'uniqueItems': True}

On instance['produces']:
    '-"application/json"'

**Comment by dtkav** [comment]
Hey @Rev0kz - You can use this online editor to check for schema errors: https://editor.swagger.io/
Good luck.
