### ISSUE TITLE
update the dependency

### ISSUE THREAD

**Issue by pingf** [zalando/connexion#895]
### Description
connexion 2.2.0 has requirement jsonschema<3.0.0,>=2.5.1, but you'll have jsonschema 3.0.1 which is incompatible.
openapi-spec-validator 0.2.6 has requirement jsonschema<3

### Steps to reproduce

when I use poetry or pipenv, it doesnt pass the dependency check, please update the requirements.

### Additional info:

Output of the commands:

- 3.7.2
- connexion = 2.2.0

**Comment by dtkav** [comment]
> but you'll have jsonschema 3.0.1 which is incompatible.
can you clarify what you mean by this?
jsonschema 3.0.0 introduces breaking changes, so both connexion and openapi-spec-validator pin the version to < 3.

**Comment by pingf** [comment]
sorry, it seems it's the problem of poetry, here is the related issue https://github.com/sdispater/poetry/issues/532

**Comment by dtkav** [comment]
No worries. Thanks for reporting back!
