### ISSUE TITLE
How to use connexion in application factory?

### ISSUE THREAD

**Issue by paynestrike** [zalando/connexion#908]
Hi

Am new to Flask, as Flask's document suggested its good practice to always use application factory, 

src/__init__.py
`

    import os
    from flask import Flask

    def create_app():

        app = Flask(__name__, instance_relative_config=True)
        app.config.from_mapping(
            SECRET_KEY = 'DEV',
            DATABASE = os.path.join(app.instance_path, 'gallery.sqlite'),
        )
    
        return app

but seems connexion can only be used in global.

is it true that connxion can't be used in application factory? if not please share how to use it in application factory

**Comment by dpmccabe** [comment]
This would be the general form of your app factory's __init__.py:

```python
import connexion

def create_app():
    app = connexion.FlaskApp(__name__, specification_dir='./')
    app.add_api('api.yml')
    return app

if __name__ == "__main__":
    create_app().run(port=5050)
```

**Comment by rafaelcaricio** [comment]
Hi @paynestrike ,
It seems like @dpmccabe answered your question. Please feel free to re-open the issue if it's not.
