### ISSUE TITLE
app.run starts with 0.0.0.0 not 127.0.0.1

### ISSUE THREAD

**Issue by ymaki** [zalando/connexion#915]
### Description

Hi, I've started use connexion as part of OpenAPI Generator.
I just have a question, not a bug probably.
FlaskApp.run() starts with host='0.0.0.0' by default in FlaskApp, while flask's default is 127.0.0.1. 
Is this an intended behavior?

> :param host: the hostname to listen on. Set this to ``'0.0.0.0'`` to
>  have the server available externally as well. Defaults to
>  ``'127.0.0.1'`` or the host in the ``SERVER_NAME`` config variable
>  if present.
https://github.com/pallets/flask/blob/master/flask/app.py#L874

Thank you in advance.

### Expected behaviour

FlaskApp.run() is expected to start development server on 127.0.0.1 if host parameter isn't specified because Flask does so.

### Actual behavior

FlaskApp in connexion serve on 0.0.0.0 by default.
For example using connexion/examples/openapi3/helloworld/, as we don't specify 'host' parameter, FlaskApp starts on 0.0.0.0.

```
$ git clone https://github.com/zalando/connexion.git
$ cd connexion/examples/openapi3/helloworld/
$ pip install connexion
$ cat hello.py
#!/usr/bin/env python3

import connexion


def post_greeting(name: str) -> str:
    return 'Hello {name}'.format(name=name)

if __name__ == '__main__':
    app = connexion.FlaskApp(__name__, port=9090, specification_dir='openapi/')
    app.add_api('helloworld-api.yaml', arguments={'title': 'Hello World Example'})
    app.run()
$ python hello.py
(snip)
 * Running on http://0.0.0.0:9090/ (Press CTRL+C to quit)
```

### Steps to reproduce

```
$ git clone https://github.com/zalando/connexion.git
$ cd connexion/examples/openapi3/helloworld/
$ pip install connexion
$ python hello.py
```

### Additional info:

https://github.com/pallets/flask/blob/master/flask/app.py#L924
https://github.com/zalando/connexion/blob/master/connexion/apps/flask_app.py#L83

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
$ python --version
Python 3.7.2
$ pip show connexion | grep "^Version\:"
Version: 2.2.0
```

**Comment by rafaelcaricio** [comment]
Yes, that is intentional. You can bind it to other hosts though.

**Comment by CMCDragonkai** [comment]
What's the option for binding to a different host?

**Comment by rafaelcaricio** [comment]
@CMCDragonkai https://github.com/zalando/connexion/blob/master/connexion/cli.py#L63 the `--host` flag

**Comment by selezenart** [comment]
I have the opposite problem. I am putting --host flag to 0.0.0.0 but it starts on 127.0.0.1 or 192.168.1.12.

**Comment by Ruwann** [comment]
@selezenart What do you mean with `or`? It should be one or the other, but not both.

If you set it to `0.0.0.0`, it's normal that it shows your local IP as you can connect to the app on this address.

**Comment by Ruwann** [comment]
@selezenart Can you please create a separate issue with minimal reproducible example? It's very hard to figure out what's going wrong without actual code.
