### ISSUE TITLE
Question: https configuration/documentation

### ISSUE THREAD

**Issue by hitzelbe** [zalando/connexion#916]
### Description

The current documentation announces more information about "how to start a https-server". Details, however, are missing. I miss this part very much right now. Is there any easy way to configure https for Tornado? I haven't found much on this online.

### Steps to reproduce

Cf. https://connexion.readthedocs.io/en/latest/security.html#https-support

**Comment by dtkav** [comment]
Best practice is usually to terminate ssl with a production web server like nginx.
