### ISSUE TITLE
Deploying connexion on aws

### ISSUE THREAD

**Issue by ctippur** [zalando/connexion#917]
### Description

I am using connexion to deploy a sample app using aws lambda. I am using Zappa to wrap the code and deploy. 
I am trying the sample code in the example for jwt. I seem to get a 404 error when I try to access the endpoint.
I am able to get a successful response when I try it locally.
One of the things I observed is that when I run the app locally, I need to run as

python -m swagger_server.app but the app_function I need to specify in zappa is swagger_server.app.app

### Expected behaviour

when I try the ```https://<aws api gateway endpoint>/dev/auth, I should get back a token.

### Actual behaviour

I get a 404 error

### Steps to reproduce

Steps are outlined in readme https://github.com/ctippur/zappa-connexion-sample/blob/master/README.md

### Additional info:

Output of the commands:

- `python --version`
3.6.3
- `pip show connexion | grep "^Version\:"`
Version: 2.2.0

**Comment by ctippur** [comment]
Any takers for this please?

**Comment by vincentalvo** [comment]
Hi,
I'm using the same setup (Zappa + Connexion) and it works more or less out of the box. 
Did you get the Pet project working on AWS first ?
https://github.com/zalando/connexion/issues/230

For information, my setup application is setup as : 
zappa_settings.json
```
"app_function": "app.application"
``` 

app.py
``` 
app = connexion.FlaskApp(__name__)
application = app.app
```

**Comment by ctippur** [comment]
I am using a similar example from connexion examples folder for jwt.

https://github.com/zalando/connexion/tree/master/examples/openapi3/jwt

I am initializing the app as below:

```
app = connexion.FlaskApp(__name__, specification_dir='swagger/')
if __name__ == '__main__':
    CORS(app.app)
    app.add_api('openapi.yaml')
    app.run(debug=True)

And in zappa config, I have
 "app_function": "swagger_server.app.app"

Implementation details can be found here:
https://github.com/ctippur/zappa-connexion-sample

**Comment by ctippur** [comment]
As you see, there is not much of a change in how we are initializing the app. The app works locally but when we deploy to aws, it throws a 404.

**Comment by vincentalvo** [comment]
`404` is not bad. It means it is doing something.
Make sure you call on the right URL, Gateway adds the stage name in the base path. You should use a `domain` to get rid of this problem. It is easy enough to setup, follow the instructions in Zappa.

Check your logs in CLoudWatch. I think it is working but not exactly as you expect.

**Comment by ctippur** [comment]
Vincent,
Can you please explain on how adding a domain can mitigate this problem. The cloudwatch logs do not indicate any issue.
I think I have developed a tunnel vision as I have been struggling with this for at least a week now.

Shekar

**Comment by vincentalvo** [comment]
Sure, AWS can be a nightmare to setup...!

Your Gateway will by default be accessible through :
`https://********.execute-api.eu-central-1.amazonaws.com/prod`

In this example, the zappa config is named `prod`. 

You might be trying to access 
`https://********.execute-api.eu-central-1.amazonaws.com/pets` 
hen what you mean is 
`https://********.execute-api.eu-central-1.amazonaws.com/prod/pets`.



Because of that, you can not access the `/ui` neither. You should setup the `domain` it makes everything easier because there is no longer any (stupid) `prod` at your base url.

**Comment by ctippur** [comment]
Sure.

Here is my endpoint
https://um8wz2hhyh.execute-api.us-east-1.amazonaws.com/dev/
As you see, I get a 404. The '/' endpoint does not have any additional
workflow associated with it. it just returns current time.


Shekar

**Comment by vincentalvo** [comment]
I would highly recommand you to start with the pet project. 
Give a go to the Zappa example too. 

Sorry, I can't really help more than that without the logs.

**Comment by ctippur** [comment]
Here is the log from cloudwatch

[DEBUG] 2019-04-08T22:42:26.510Z        1d11cf42-0505-427b-b7a5-eca3eaa221ac
  Zappa Event: {'resource': '/', 'path': '/', 'httpMethod': 'GET',
'headers': {'Accept':
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language':
'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7', 'CloudFront-Forwarded-Proto':
'https', 'CloudFront-Is-Desktop-Viewer': 'true',
'CloudFront-Is-Mobile-Viewer': 'false', 'CloudFront-Is-SmartTV-Viewer':
'false', 'CloudFront-Is-Tablet-Viewer': 'false',
'CloudFront-Viewer-Country': 'CA', 'dnt': '1', 'Host': '
um8wz2hhyh.execute-api.us-east-1.amazonaws.com',
'upgrade-insecure-requests': '1', 'User-Agent': 'Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/73.0.3683.86 Safari/537.36', 'Via': '2.0
cb1b3040a2f456ef6218d3d26a3e39ae.cloudfront.net (CloudFront)',
'X-Amz-Cf-Id': 'yM9NifhAbBovlwzW3LSNwb9KTixQJk2n9kpTwuEa-eMoq3JvrJiojA==',
'X-Amzn-Trace-Id': 'Root=1-5cabce52-44a8355802ba9e3bdcc58fb4', 'x-api-key':
'0YHSbevffp6luI9dLtAK81SyiTuogIRv4k6Scq8N', 'X-Forwarded-For':
'24.48.65.35, 54.182.235.74', 'X-Forwarded-Port': '443',
'X-Forwarded-Proto': 'https'}, 'multiValueHeaders': {'Accept':
['text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'],
'Accept-Encoding': ['gzip, deflate, br'], 'Accept-Language':
['fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'], 'CloudFront-Forwarded-Proto':
['https'], 'CloudFront-Is-Desktop-Viewer': ['true'],
'CloudFront-Is-Mobile-Viewer': ['false'], 'CloudFront-Is-SmartTV-Viewer':
['false'], 'CloudFront-Is-Tablet-Viewer': ['false'],
'CloudFront-Viewer-Country': ['CA'], 'dnt': ['1'], 'Host': ['
um8wz2hhyh.execute-api.us-east-1.amazonaws.com'],
'upgrade-insecure-requests': ['1'], 'User-Agent': ['Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/73.0.3683.86 Safari/537.36'], 'Via': ['2.0
cb1b3040a2f456ef6218d3d26a3e39ae.cloudfront.net (CloudFront)'],
'X-Amz-Cf-Id':
['yM9NifhAbBovlwzW3LSNwb9KTixQJk2n9kpTwuEa-eMoq3JvrJiojA=='],
'X-Amzn-Trace-Id': ['Root=1-5cabce52-44a8355802ba9e3bdcc58fb4'],
'x-api-key': ['0YHSbevffp6luI9dLtAK81SyiTuogIRv4k6Scq8N'],
'X-Forwarded-For': ['24.48.65.35, 54.182.235.74'], 'X-Forwarded-Port':
['443'], 'X-Forwarded-Proto': ['https']}, 'queryStringParameters': None,
'multiValueQueryStringParameters': None, 'pathParameters': None,
'stageVariables': None, 'requestContext': {'resourceId': '53ohx6ujnd',
'resourcePath': '/', 'httpMethod': 'GET', 'extendedRequestId':
'X10s4HrkoAMFRSg=', 'requestTime': '08/Apr/2019:22:42:26 +0000', 'path':
'/dev/', 'accountId': 'redacted', 'protocol': 'HTTP/1.1', 'stage': 'dev',
'domainPrefix': 'um8wz2hhyh', 'requestTimeEpoch': 1554763346459,
'requestId': '95427f16-5a4f-11e9-82c4-3b400df518ac', 'identity':
{'cognitoIdentityPoolId': None, 'accountId': None, 'cognitoIdentityId':
None, 'caller': None, 'sourceIp': '24.48.65.35', 'apiKey':
'0YHSbevffp6luI9dLtAK81SyiTuogIRv4k6Scq8N', 'accessKey': None,
'cognitoAuthenticationType': None, 'cognitoAuthenticationProvider': None,
'userArn': None, 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
'user': None}, 'domainName': 'um8wz2hhyh.execute-api.us-east-1.amazonaws.com',
'apiId': 'um8wz2hhyh'}, 'body': None, 'isBase64Encoded': False}

[DEBUG] 2019-04-08T22:42:26.510Z        1d11cf42-0505-427b-b7a5-eca3eaa221ac
  host found: [um8wz2hhyh.execute-api.us-east-1.amazonaws.com]

[DEBUG] 2019-04-08T22:42:26.510Z        1d11cf42-0505-427b-b7a5-eca3eaa221ac
  amazonaws found in host

[DEBUG] 2019-04-08T22:42:26.545Z        1d11cf42-0505-427b-b7a5-eca3eaa221ac
  Getting data and status code

[DEBUG] 2019-04-08T22:42:26.545Z        1d11cf42-0505-427b-b7a5-eca3eaa221ac
  Got data and status code (404)

[INFO]  2019-04-08T22:42:26.546Z        1d11cf42-0505-427b-b7a5-eca3eaa221ac
  24.48.65.35 - - [08/Apr/2019:22:42:26 +0000] "GET / HTTP/1.1" 404 205 ""
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/73.0.3683.86 Safari/537.36" 0/35.714000000000

**Comment by vincentalvo** [comment]
this looks like the log from Gateway, you should inspect the one from Lambda.

**Comment by ctippur** [comment]
This is from Lambda logs. I have turned on Zappa debug.

Shekar

**Comment by vincentalvo** [comment]
ok, so it just looks like your application is returning 404. 
Again, please try the Pet project.

**Comment by ctippur** [comment]
From what see, it is not hitting the application code beyond initializing app

**Comment by ctippur** [comment]
I think I am getting a little further.

This is what I have. I dont see the message "In Main Code" being printed.
So, via zappa, it is not main but the "__name__" is either
swagger_server.app or simply app.
if I include these in the if section, I get a deployment warning with a 504
error.

Error: *Warning!* Status check on the deployed lambda failed. A GET request
to '/' yielded a *504* response code.

########### CODE BEGIN ###########

app = connexion.FlaskApp(__name__, specification_dir='swagger/')

CORS(app.app)

app.add_api('openapi.yaml', resolver=RestyResolver('seaiceservices.api'))

print ("Before main code", __name__)

if __name__ == '__main__':

    print ("In Main Code")

    app.run()

########### CODE END ###########

**Comment by ctippur** [comment]
My bad .. I got it to work. All I needed was this..

Thanks for your input though.

```
app = connexion.FlaskApp(__name__, specification_dir='swagger/')
app.add_api('openapi.yaml')
CORS(app.app)
```
