### ISSUE TITLE
Prioritisation of similar paths

### ISSUE THREAD

**Issue by cansik** [zalando/connexion#92]
I'm currently working on an api where we have two paths which looks very similar. The only difference is the last part of the paths. In one path there is a string parameter at then end and in the other one there is a fixed path name:

```
http://myapi.com/user/{userid}
http://myapi.com/user/insert
```

So I would suggest that if I call the second path, the operation of the second path should be called. But when I try it out, connexion takes the **userid** path operation with the parameter `insert`.

I couldn't find something in the swagger specifications about this, but for swagger, the two paths are not similar. Otherwise the swagger definition would not be valid: 

[![Swagger API](http://online.swagger.io/validator/?url=http://easyguet.ch/temp/swagger_myapi.json)](http://online.swagger.io/validator/debug?url=http://easyguet.ch/temp/swagger_myapi.json)
```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'My API'
paths:
  /user/insert:
    get:
      description: Hello World
      responses:
          200:
            description: OK
            
  /user/{userid}:
    get:
      description: Hello World
      parameters:
        - name: userid
          in: path
          description: Size of array
          required: true
          type: string
      responses:
          200:
            description: OK
```

I know the API design might not be the best one, but my question is, if this is swagger valid and if yes, how does connexion prioritize this?

**Comment by jmcs** [comment]
Connexion uses Werkzeug for routing (indirectly via Flask). According to [Rule.match_compare_key](https://github.com/mitsuhiko/werkzeug/blob/5cdc596fd1b725cd25b457072e1f545958c78226/werkzeug/routing.py#L777):

> rules without any arguments come first for performance reasons only as we expect them to match faster and some common ones usually don't have any arguments (index pages etc.)

So I'm almost sure that `/user/insert` will be prioritized, but I never tested it.

**Comment by jmcs** [comment]
Connexions uses Werkzeug (indirectly via Flask) to route requests. According to [Rule.match_compare_key](https://github.com/mitsuhiko/werkzeug/blob/5cdc596fd1b725cd25b457072e1f545958c78226/werkzeug/routing.py#L777) `/user/insert` should be prioritized. I'll try to find out why it isn't.

**Comment by cansik** [comment]
Ok, very strange but it seems to work now. Maybe there was a mistake on my side. I'll check it with a my small example and give you feedback.

**Comment by hjacobs** [comment]
@cansik any update on this? I would close this issue otherwise :hourglass_flowing_sand: :

**Comment by cansik** [comment]
Sorry, I tried it and it was a mistake on my side! But thank you for the fast reply!
