### ISSUE TITLE
Swagger UI endpoint can be changed from /ui to something else in connexion 2.x ?

### ISSUE THREAD

**Issue by johanngomes** [zalando/connexion#920]
In the 1.x versions of connexion, it was possible to redirect the endpoint where the Swagger UI should expose the API documentation, passing `swagger_url` when constructing the `App` object:

```
connexion.App(__name__,
                        specification_dir='any-dir',
                        swagger_url='docs')
```

This way, for example, instead of providing the UI on `/ui` endpoint, the UI is exposed on `/docs` endpoint.

How to change that endpoint in connexion 2.2.0? I haven't found any option to do that in the documentation, neither an example.

**Comment by dtkav** [comment]
See the first dot point under "new in Connexion 2.0" in the readme.

options must be passed in via the `options` argument.

```
connexion.App(__name__, options={"swagger_url"="docs"})
```

**Comment by johanngomes** [comment]
Thanks @dtkav ! It was just that. :)
