### ISSUE TITLE
Connexion and zappa on AWS Lambda: very slow cold starts

### ISSUE THREAD

**Issue by dirkgomez** [zalando/connexion#934]
### Description

Evaluating Connexion for our microservices application which fully runs on AWS lambda.

I'm experiencing fairly slow cold starts with Connexion, e. g. it takes ~3 seconds just to run

`import connexion`

The API in case is really small as it is merely a sample project, it has 6 REST endpoints, which in turn are more or less just sample endpoints. The endpoints use operationId to associate connexion and the code itself, like this:

```
  /api/hello:
    get:
      operationId: api.hello
      summary: Say hello world
      responses:
        200:
          description: 'Hello World Flask and Zappa'
          schema:
            type: string

```
(See #306, it's fairly outdated though)

The Lambda runs with 512MB memory.

### Expected behaviour

Cold starts are faster.

### Steps to reproduce

Cold starts are very slow.

### Additional info:

Output of the commands:

Lambdas with Python 3.6
Connexion 2.2.0

**Comment by BorisCodinis** [comment]
I'm having the same problem. Any news?

**Comment by kanbber** [comment]
I run into the same problem... Any solution?
