### ISSUE TITLE
multipart/form-data content validation

### ISSUE THREAD

**Issue by maximumG** [zalando/connexion#935]
### Description

I'm trying to have some validation on a REST route accepting a multipart/form-data content. This multipart is composed of 2 contents:

* a ZIP file named `stack_zip`  (application/zip)
* a form-data named `variables` (application/json)

![multipart](https://user-images.githubusercontent.com/4469833/57282086-a2d40300-70ac-11e9-9911-61fa66f1fbbb.png)

### Expected behaviour

The `variables` content should be validated against a schema defined in openapi.yaml.

### Actual behaviour

The `variables` content is received by connexion as a raw string even if the `Content-Type` is set to `application/json`.

It also seems that Werkzeug is:

* keeping the headers when parsing the a File object  (application/zip)
* removing the headers when parsing any non-file object

### Steps to reproduce

OpenAPI schema.

```yaml

  /zones/{zoneId}/deploy_stack:
    post:
      tags:
      - Stack
      summary: Deploy a Docker Stack
      operationId: api.v1.view.deploy_stack
      responses:
        200:
          description: Successful response - Docker stack deployed.
        404:
          description: The specified `Zone` does not exist.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                variables:
                  type: object
                  properties:
                    stack_name:
                      type: string
                stack_zip:
                  type: string
                  format: binary
            encoding:
              stack_zip:
                contentType: application/zip
              variables:
                contentType: application/json

```

Client command:

```bash

curl -i -X POST 'http://localhost:9090/v1/zones/bo/deploy_stack'           -H 'Content-type:multipart/form-data'           -F 'stack_zip=@artifacts.zip;type=application/zip'           -F 'variables={"stak_name": "bar"}; type=application/json'
```

### Additional info:

 I tested this feature against the connexion 2.0 main branch as well as the branch from https://github.com/zalando/connexion/pull/760

I guess it would be nice if the library could parse the encoding section in the YAML specs and try to convert the form in a JSON object in the content-type is set to application/json. I guess I could start by tryiing to modify the code in #760 and add support for encoding.

**Comment by maximumG** [comment]
## Deserialize complex formdata

I investigated deeper this problem to find any workaround. Basically I modified the *uri_parsing.py* module with the following code in the *OpenAPIURIParser* class.

```python

   def resolve_form(self, form_data):
        if self._body_schema is None or self._body_schema.get('type') != 'object':
            return form_data
        for k in form_data:
            encoding = self._body_encoding.get(k, {"style": "form"})
            defn = self.form_defns.get(k, {})
            # TODO support more form encoding styles
            form_data[k] = \
                self._resolve_param_duplicates(form_data[k], encoding, 'form')
            if encoding.get('contentType', None) == 'application/json':
                form_data[k] = json.loads(form_data[k])
            if defn and defn["type"] == "array":
                form_data[k] = self._split(form_data[k], encoding, 'form')
        return form_data

```
This code will try to parse the form_data value as JSON if its contentType is set to application/json in the OpenAPI definition. It would be nice to know if the code is in the right place from an architectural point of view. 

A good insight on body encoding can be found here : https://swagger.io/docs/specification/describing-request-body/ (section **Complex Serialization in Form Data**)

## Strict validation on formData parameters

I also discovered that *ParameterValidator* class in *validation.py* module is OpenAPI 2.0 compliant but not OpenAPI 3.0 https://github.com/zalando/connexion/blob/1bda0659d5f4e6d1f4f30135fea241768bdae28b/connexion/decorators/validation.py#L275

The method is checking for the form keys as defined in the OpenAPI 2.0 parameters section. However in OpenAPI 3.0 the formData parameters are not used anymore but can be found in the requestBody directly.

I guess it would be easier to have an AbstractParameterValidator and use 2 subclasses for OpenAPI 3.0 and Swagger 2.0, each class using its own spec to validate parameters and form.

**Comment by rsnyman** [comment]
I appear to be running into this issue as well. I have a method that uses `multipart/form-data` and contains some parameters as well as a file that is uploaded. The parameters other than the file are discarded in the validation.

**Comment by rsnyman** [comment]
The code causing this problem is at [line 274 in connexion/operators/openapi.py](https://github.com/zalando/connexion/blob/master/connexion/operations/openapi.py#L274):

```python
        if x_body_name in arguments or has_kwargs:
            return {x_body_name: res}
        return {}
```

There is no `x-body-name` in the schema, there is no `**kwargs` and so an empty dict is returned.

**Comment by dtkav** [comment]
@rsnyman - You handler function needs to take a parameter named "body" if you don't set x-body-name.

**Comment by SyedAhmedMohiuddinPeerzade** [comment]
its not validating pattern also inside multipart/form-data
