### ISSUE TITLE
Allow specifying the default controller for an API

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [zalando/connexion#938]
### Description
If all operations of an API are handled by the same controller, we still need to define `x-swagger-router-controller` on each operation. It would be nice if instead we could specify it in one spot.

Here's my attempt:
```
class ControllerResolver(resolver.Resolver):
  """Connexion allows to specify the controller through """
  def __init__(self, controller: str, *args, **kwargs):
    self.controller = controller
    super(ControllerResolver, self).__init__(*args, **kwargs)

  def resolve_operation_id(self, operation) -> str:
    op = super(ControllerResolver, self).resolve_operation_id(operation)
    if "." in op:
      return op
    return f"{self.controller}.{op}"
```
```
app.add_api(pathlib.Path("swagger.yaml"), resolver=ControllerResolver(controller="my_service.api.rest.controller"))
```

It would be even nicer if we could pass in the actual module instead of a string.

**Comment by Abdullahabid3691** [comment]
> ### Description
> If all operations of an API are handled by the same controller, we still need to define `x-swagger-router-controller` on each operation. It would be nice if instead we could specify it in one spot.
> 
> Here's my attempt:
> 
> ```
> class ControllerResolver(resolver.Resolver):
>   """Connexion allows to specify the controller through """
>   def __init__(self, controller: str, *args, **kwargs):
>     self.controller = controller
>     super(ControllerResolver, self).__init__(*args, **kwargs)
> 
>   def resolve_operation_id(self, operation) -> str:
>     op = super(ControllerResolver, self).resolve_operation_id(operation)
>     if "." in op:
>       return op
>     return f"{self.controller}.{op}"
> ```
> 
> ```
> app.add_api(pathlib.Path("swagger.yaml"), resolver=ControllerResolver(controller="my_service.api.rest.controller"))
> ```
> 
> It would be even nicer if we could pass in the actual module instead of a string.

that's nice... does this works? I was in search of a similar case/solution. I hope I will try this. Thanks @hubertgrzeskowiak
