### ISSUE TITLE
change use of `operationId`

### ISSUE THREAD

**Issue by fehguy** [zalando/connexion#94]
The spec field `operationId` is used for client generation method names.  While connexion uses `operationId` for routing directly to a controller, it will make for some very ugly client SDK methods.

For example:

```yaml
operationId: my.controller.default_controller.getUser
```

Will generate into this for ObjectiveC:

```objc
-(NSNumber*) myControllerDefaultControllerGetUserWithCompletionBlock
```

It would be nice if connexion followed the same strategy as [swagger-inflector](https://github.com/swagger-api/swagger-inflector#locating-the-target-method) and [swagger-node](https://github.com/swagger-api/swagger-node#4-write-controller-code-in-nodejs) for locating the routing controller/method.

Specifically, I'd propose the following:

```yaml
operationId: getUser
x-swagger-router-controller: my.controller.default_controller
```

Which allows for a friendly name for the client SDK and server controller method, and uses the vendor extensions for the controller location.

**Comment by hjacobs** [comment]
I would rather like to see a pluggable solution like discussed in #89. There could be one implementation of the resolver using your suggested "x-swagger-router-controller".

**Comment by hjacobs** [comment]
Our Friboo Clojure library does it the same: the operation resolving function can be configured.

**Comment by hjacobs** [comment]
Released in https://github.com/zalando/connexion/releases/tag/1.0.9
