### ISSUE TITLE
How to change index.html in served index.html

### ISSUE THREAD

**Issue by vladdoster** [zalando/connexion#943]
### Description
We want to change the favicon and a few other things when it comes to the served index.html file. We have tried copying over our custom version to what seems to be the served index.html with the following line 

`COPY custom_python_libs/swagger_ui_bundle/vendor/swagger-ui-3.20.5/index.html /usr/local/lib/python3.7/site-packages/swagger_ui_bundle/vendor/swagger-ui-3.20.5/index.html`

It seems to have no effect. Is there some sort of index.html cleansing going on?

### Expected behaviour

Our custom index.html changes would be visible when navigating to our api url
http://localhost:8000/api/v1/ui/

### Actual behaviour

Still the default index.html being served.

### Steps to reproduce

Run any connexion app in docker and try to modify the served index.html

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by dtkav** [comment]
Hey @vladdoster - the file you want to edit is index.j2 which is a jinja2 template.

**Comment by vladdoster** [comment]
@dtkav You da man! Thanks so much!
