### ISSUE TITLE
How to choose swagger-ui ver. 2.2.10 over 3.20.5 when using connexion[swagger-ui]

### ISSUE THREAD

**Issue by vladdoster** [zalando/connexion#949]
### Description
How do I use swagger-ui-2.2.10 over 3.20.5?

### Expected behaviour

I want to have all files instead of relying on webpack to bundle the assets. I need to modify the swagger-oauth.js file.

### Actual behaviour

I have to do convoluted things with docker and it still is expecting node as a dep. I am lost. . . 

### Steps to reproduce

N/A

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by vladdoster** [comment]
Any idea?

**Comment by dtkav** [comment]
swagger-ui-bundle includes the last swagger 2 release:
```
from swagger_ui_bundle import swagger_ui_2_path

# ...

options = {"swagger_path": swagger_ui_2_path}
app.add_api('pets-api.yaml', options=options)
```
if you want to point to your own modified release of swagger-ui, then you need to download the source, build a release, and then point connexion to your local directory with the `swagger_path` option.
