### ISSUE TITLE
Request body is not valid JSON

### ISSUE THREAD

**Issue by snakecy** [zalando/connexion#965]
### Description
![image](https://user-images.githubusercontent.com/12490881/58525392-2ab9b280-81fe-11e9-8671-2f79609b8b13.png)

After i use swagger2.0 swagger-codegen generate the flask for python service, when posting data from web, the error turns out :
```
{
  "detail": "Request body is not valid JSON",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```
what can i do now ?

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by drummerwolli** [comment]
well, the error message is pretty self explanatory. other json validators are also not working with this:

![image](https://user-images.githubusercontent.com/3867569/59126130-97eae780-8964-11e9-83f8-33cf7559961d.png)

if you somehow want to make this work, then i suggest to serialize those line breaks.

**Comment by hjacobs** [comment]
@drummerwolli is right, closing.
