### ISSUE TITLE
Retire EOL Python 3.4

### ISSUE THREAD

**Issue by cognifloyd** [zalando/connexion#977]
Python 3.4 is EOL.
> Python 3.4 has now reached its end-of-life and has been retired. No more releases will be made.
https://www.python.org/dev/peps/pep-0429/

Also, the async/await keywords are nicer to work with in 3.5+ (used by the aiohttp client).
https://www.python.org/dev/peps/pep-0478/
https://www.python.org/dev/peps/pep-0492/

When can we deprecate / remove support for python 3.4?

**Comment by hjacobs** [comment]
Yes, PR is welcome I would say :smile:

**Comment by kornicameister** [comment]
I suppose we can EOL anything around 2.7 as well
It goes out with the end of the year.

@hjacobs I can do the PR if you tell me how to do that exactly ;-)
Will dropping any references (i.e. setup.py, tox) sufficient?

**Comment by kornicameister** [comment]
From what I can tell, we are talking about sth like that.
I noticed travis failing a lot because `Flask` (dev envs) does not work with Py34.

I will drop PR, maybe even today.
