### ISSUE TITLE
Expose connexion app to UWSGI

### ISSUE THREAD

**Issue by BjoernLaemmerzahl** [zalando/connexion#981]
### Description

I apologize if I misunderstood something here, as I am taking my first steps.

When running my Docker image and requesting the Swagger Ui I receive: **502 Bad Gateway** by NGINX.

I am attempting to run connexion with UWSGI on NGINX. I assume it is because Uwsgi does not correctly pick up my Flask instance. However, it appears to me that my container instance is correctly configured.

If you look here [https://github.com/Microsoft/python-sample-vscode-flask-tutorial](https://github.com/Microsoft/python-sample-vscode-flask-tutorial), the setup of my application and the configuration is similar and it works without issues.

According to the connexion documentation I should be able to expose the app instance to uWSGI using

```
app = connexion.App(__name__, specification_dir='swagger/')
application = app.app # expose global WSGI application object
```
### Expected behaviour
Expected behavior is that the Swagger UI is available at:

[http://localhost:5000/v1.0/ui/#/](http://localhost:5000/v1.0/ui/#/)

when running from a Docker container.

### Actual behaviour
When running my Docker image and requesting the Swagger Ui I receive: **502 Bad Gateway** by NGINX.

### Steps to reproduce

You can find my complete application code here:

[https://bitbucket.org/lammy123/flask_nginx_docker_connexion/src/master/](https://bitbucket.org/lammy123/flask_nginx_docker_connexion/src/master/)

The Flask/Connexion object is in application/init.py

My **uwsgi.ini** reads:

```
[uwsgi]
module = application.webapp
callable = app
uid = 1000
master = true
threads = 2
processes = 4
```
init.py
```

import connexion

app = connexion.App(__name__, specification_dir='openapi/')
app.add_api('helloworld-api.yaml', arguments={'title': 'Hello World Example'})
```
**webapp.py**

```
from . import app    # For application discovery by the 'flask' command. 
from . import views  # For import side-effects of setting up routes.
from . import app
import connexion

application = app.app

```
### Additional info:

Output of the commands:

- `python --version`
Python 3.7.1

- `pip show connexion | grep "^Version\:"`
"version": "==2.3.0" (from pipfile.lock)

Thanks for your time.

**Comment by kdebrab** [comment]
The line 'callable = app' in the `uwsgi.ini` file says that the callable is not the default callable `application` but the custom callable `app`. However, in `webapp.py`, you define the callable to be `application`. `app` is also defined, but it's a module, not a callable.

So, either you remove the line line 'callable = app' from `uwsgi.ini` or, alternatively, you include `from .app import app` in `webapp.py`.

**Comment by BjoernLaemmerzahl** [comment]
@kdebrab You are of course absolutely right. Thank you.
