### ISSUE TITLE
Optional and uppercase parameters 

### ISSUE THREAD

**Issue by generalmilk** [zalando/connexion#99]
These maybe swagger codegen issues.

Optional parameters in operation are required, otherwise produce 500 internal error
Tried adding default value for optional parameters in yaml, but it is ignored.

If a parameter have uppercase first letter, it will become lower case in controllers, and produce 500 internal error.

**Comment by hjacobs** [comment]
Can you give some examples (YAML + Python code)? Optional query parameters should work correctly as far as I know (but you need to set default value for Python keyword argument of course).

**Comment by hjacobs** [comment]
@generalmilk you can find a working example of optional (non-required) query parameters here: https://github.com/hjacobs/connexion-example

**Comment by generalmilk** [comment]
@hjacobs Thanks for quick replay.

If there is default value, then it will be automatically filled in the swagger UI, but still does not work for RESTAPI call

For eample, I have an API http://localhost/v1/getResult?num=0
where num is optional and 0 is default and means no number limit.
If I call http://localhost/v1/getResult
There will be an internal 500 error
The other problem is, 0 will be shown on Swagger UI, which is confusing without explanation.
Sometimes it is better not to have a default value for optional parameters.
A better solution would be adding "=None" for the optional parameter if there is no default value in the defualtcontoller.py

So for the above example, I would prefer "def get_result(num=None)" in the controller.
If there is a default value, then also "def get_result(num=0)"  for example.
In both case, you can actually treat num optional, and call http://localhost/v1/getResult

**Comment by hjacobs** [comment]
@generalmilk yes, the Swagger "default" values are not automatically filled right now.

**Comment by hjacobs** [comment]
Default values for query parameters should now work (fixed with #117), see my example app: https://github.com/hjacobs/connexion-example

**Comment by hjacobs** [comment]
@generalmilk could you check whether the fix (default query params) works for you?

**Comment by generalmilk** [comment]
Hi Henning,

Thanks for the notice. I can't test it in recent, but I may do it after the
vacation.

On Thu, Jan 21, 2016 at 6:50 PM, Henning Jacobs <notifications@github.com>
wrote:

> @generalmilk <https://github.com/generalmilk> could you check whether the
> fix (default query params) works for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando/connexion/issues/99#issuecomment-173536152>.
>



-- 

Best Regards,

Tao Chenhttp://www.ee.columbia.edu/dvmm/vso/~taochen/
Post Doctoral Research Scientist,
Digital Video and Multimedia Lab,
Columbia University

**Comment by rafaelcaricio** [comment]
Closing this issue since it seems fixed.

@generalmilk if you find any problem, you are welcome to open this issue again.
