### ISSUE TITLE
pytest>=5.0.0 incompatible with Flask<=1.0.4

### ISSUE THREAD

**Issue by kornicameister** [zalando/connexion#991]
### Description

Master builds are failing due to error:
```
import_name = 'conftest'
    def find_package(import_name):
        """Finds a package and returns the prefix (or None if the package is
        not installed) as well as the folder that contains the package or
        module as a tuple.  The package path returned is the module that would
        have to be added to the pythonpath in order to make it possible to
        import the module.  The prefix is the path below which a UNIX like
        folder structure exists (lib, share etc.).
        """
        root_mod_name = import_name.split('.')[0]
        loader = pkgutil.get_loader(root_mod_name)
        if loader is None or import_name == '__main__':
            # import name is not found, or interactive/main module
            package_path = os.getcwd()
        else:
            # For .egg, zipimporter does not have get_filename until Python 2.7.
            if hasattr(loader, 'get_filename'):
                filename = loader.get_filename(root_mod_name)
            elif hasattr(loader, 'archive'):
                # zipimporter's loader.archive points to the .egg or .zip
                # archive filename is dropped in call to dirname below.
                filename = loader.archive
            else:
                # At least one loader is missing both get_filename and archive:
                # Google App Engine's HardenedModulesHook
                #
                # Fall back to imports.
                __import__(import_name)
                filename = sys.modules[import_name].__file__
            package_path = os.path.abspath(os.path.dirname(filename))
            # package_path ends with __init__.py for a package
>           if loader.is_package(root_mod_name):
E           AttributeError: 'AssertionRewritingHook' object has no attribute 'is_package'
.tox/py37-min/lib/python3.7/site-packages/flask/helpers.py:682: AttributeError
```

This can be tracked to following issues:
- https://github.com/pytest-dev/pytest/issues/5532
- https://github.com/pytest-dev/pytest/issues/5542

Indeed (either one of those actions):
- restricting `flask` to be at least `1.0.4` makes tests pass.
- restricting `pytest` to be at most `4.9.x` makes test pass

Which brings us down to final question.
Should `Flask` be kept at low version (which is pretty old TBH) or should `pytest` be restricted.
Personally I favor running newer version instead of supporting older codebases.

### Expected behaviour

master branch builds correctly against `min` environments.

### Actual behaviour

master branch builds correctly against `min` fail with aforementioned error.

### Steps to reproduce

Just run `tox -e py3(X)-min` where `X` stands for `Python` minor version {4,5,6,7}.

**Comment by hjacobs** [comment]
Thanks for reporting, so just updating Flask would fix the problem?

**Comment by drummerwolli** [comment]
@hjacobs especially pinning to `Flask>=1.0.4` seems to do the job, which means abandoning old versions of Flask ...

**Comment by kornicameister** [comment]
In a defense of this approach, may I be so bold to say that dropping older Flask opens door to support newer Python that is not only faster but also typed which makes it extremely easier to maintain larger projects.

**Comment by kornicameister** [comment]
@hjacobs it did the trick for me. All we need to test IT is the PR. I will drop one later on.

**Comment by hjacobs** [comment]
Great, thanks!
