### ISSUE TITLE
Add API reference documentation

### ISSUE THREAD

**Issue by RobbeSneyders** [zalando/connexion#993]
### Description

The connexion documentation does currently not contain a section with the API reference, which should document each module, class, and function. API reference documentation is very useful when developing both on and with connexion, and might improve contributions/adoption.

API reference documentation can be generated automatically from the docstrings with Sphinx extensions:
- [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) (imports code)
- [AutoAPI](https://github.com/readthedocs/sphinx-autoapi) (parses source code statically)

This will also be an incentive to improve / add missing docstrings in the connexion code base.

### Expected behaviour

An good example can be found in the Flask documentation. http://flask.pocoo.org/docs/1.0/#api-reference

**Comment by hiboo** [comment]
I clearly agree with you as there is a lot of features which are currently not documented at all forcing me to regularly investigate source code to find some cool stuff.

Having some API reference could help showing such features to developpers without having to create more complex "human-friendly" documentation
