### ISSUE TITLE
Introduce typings

### ISSUE THREAD

**Issue by kornicameister** [zalando/connexion#998]
### Description

Long story shorts. I would like to see connexion having typings.
Reason is simple...the codebase is large and quite complicated which makes having a typed code a necessity needed to unveil the functionality behind lines of code.
Obviously speaking we would need to drop support for `2.7` which I voted for in #990 which is not that bad of an idea given that `2.7` is reaching EOL and it's been, I guess, about 10 years since `3.x` has been introduced to us.

### Expected behaviour

connexion has typed codebase

### Actual behaviour

connexion does not have typed codebase

**Comment by kornicameister** [comment]
@hjacobs what do you say. I can help with making a typings for connexion if you want to.
But let's see if can drop `2.7` first. If so, I will do just that along with creating a plan to proceed with introducing typings.

**Comment by rafaelcaricio** [comment]
We don't need to drop support for python 2.7 to start introducing typing in the Connexion codebase. https://mypy.readthedocs.io/en/latest/python2.html

**Comment by kornicameister** [comment]
@rafaelcaricio yeah, it is not needed but `2.7` goes out of the picture in few months. No reason to stick around with it.

**Comment by hjacobs** [comment]
I vote for dropping Python 2.7 support!

**Comment by rafaelcaricio** [comment]
I vote for drop 2.7 support as well.

**Comment by kornicameister** [comment]
@hjacobs @rafaelcaricio 

- https://github.com/zalando/connexion/pull/1058
- https://github.com/zalando/connexion/pull/1057

**Comment by cclauss** [comment]
The five syntax errors mentioned in #1392 might be a useful place to start the gradual adoption of type hints.

**Comment by RobbeSneyders** [comment]
Closing in favor of #1111
